import {afterEach,describe,expect,it,vi} from 'vitest';
import {voyageEmbedPassages,voyageConfig} from '@/modules/official/voyage';
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
const vector=(n=1)=>Array.from({length:1024},(_,i)=>i===0?n:0);
const reply=(body:{inputs:string[][];model:string})=>Response.json({model:body.model,data:body.inputs.map((_,i)=>({index:i,data:[{index:0,embedding:vector(i+1)}]})).reverse(),usage:{total_tokens:10}});
describe('Voyage corpus embeddings',()=>{
 it('uses only the explicit server environment and defaults to context-4',async()=>{vi.stubEnv('VOYAGE_API_KEY','');expect(await voyageConfig()).toBeNull();vi.stubEnv('VOYAGE_API_KEY','test');vi.stubEnv('VOYAGE_EMBEDDING_MODEL','');expect(await voyageConfig()).toMatchObject({model:'voyage-context-4'});});
 it('uses the contextual endpoint with independently addressable passages and preserves response order',async()=>{const f=vi.fn(async(_u:unknown,o:RequestInit)=>reply(JSON.parse(o.body as string)));const v=await voyageEmbedPassages(['first case','unrelated case'],{apiKey:'test-key',model:'voyage-context-4',fetchImpl:f as typeof fetch});expect(f.mock.calls[0][0]).toBe('https://api.voyageai.com/v1/contextualizedembeddings');const b=JSON.parse(f.mock.calls[0][1].body as string);expect(b).toMatchObject({inputs:[['first case'],['unrelated case']],input_type:'document',output_dimension:1024});expect(v.map(x=>x[0])).toEqual([1,2]);});
 it('embeds search queries in the identical model space with query intent',async()=>{const f=vi.fn(async(_u:unknown,o:RequestInit)=>reply(JSON.parse(o.body as string)));await voyageEmbedPassages(['interim injunction'],{apiKey:'test-key',model:'voyage-context-4',query:true,fetchImpl:f as typeof fetch});expect(JSON.parse(f.mock.calls[0][1].body as string).input_type).toBe('query');});
 it('rejects malformed vectors and model mismatches rather than storing misleading data',async()=>{await expect(voyageEmbedPassages(['case'],{apiKey:'test-key',model:'voyage-context-4',fetchImpl:vi.fn(async()=>Response.json({model:'other',data:[]})) as typeof fetch})).rejects.toThrow(/model/);await expect(voyageEmbedPassages(['case'],{apiKey:'test-key',model:'voyage-context-4',fetchImpl:vi.fn(async()=>Response.json({model:'voyage-context-4',data:[{index:0,data:[{index:0,embedding:[1,2]}]}]})) as typeof fetch})).rejects.toThrow(/vector/);});
 it('bounds Unicode requests by UTF-8 size without silently truncating passages',async()=>{const f=vi.fn(async(_u:unknown,o:RequestInit)=>reply(JSON.parse(o.body as string)));await voyageEmbedPassages(Array.from({length:10},()=> 'न्याय'.repeat(500)),{apiKey:'test-key',model:'voyage-context-4',fetchImpl:f as typeof fetch});expect(f.mock.calls.length).toBeGreaterThan(1);for(const [,o] of f.mock.calls){const b=JSON.parse(o.body as string);expect(b.inputs.flat().reduce((n:number,t:string)=>n+Buffer.byteLength(t),0)).toBeLessThanOrEqual(28000);}await expect(voyageEmbedPassages(['x'.repeat(30000)],{apiKey:'test-key',model:'voyage-context-4',fetchImpl:f as typeof fetch})).rejects.toThrow(/limit/);});
 it('never leaks the credential in provider errors',async()=>{await expect(voyageEmbedPassages(['case'],{apiKey:'private-key',model:'voyage-context-4',fetchImpl:vi.fn(async()=>Response.json({detail:'bad private-key'},{status:401})) as typeof fetch})).rejects.toThrow('voyage: authentication failed');});
});
