import "server-only";
import { saveWorkspace } from "@/lib/workspace";
import type { Database } from "@/lib/db";
import type { Matter, Person } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "./ids";

const people: Person[] = [
  { id: PEOPLE.arjunMehra, name: "Arjun Mehra", email: "amehra@mehrarao.example", title: "Partner", organization: "Mehra & Rao Advocates", role: "attorney", tags: ["litigation", "arbitration"] },
  { id: PEOPLE.priyaRaman, name: "Priya Raman", email: "praman@mehrarao.example", title: "Partner", organization: "Mehra & Rao Advocates", role: "attorney", tags: ["products liability", "environmental"] },
  { id: PEOPLE.dhruvOberoi, name: "Dhruv Oberoi", email: "doberoi@mehrarao.example", title: "Senior Associate", organization: "Mehra & Rao Advocates", role: "attorney", tags: ["commercial", "M&A"] },
  { id: PEOPLE.eshaMathur, name: "Esha Mathur", email: "emathur@mehrarao.example", title: "Associate", organization: "Mehra & Rao Advocates", role: "attorney", tags: ["litigation"] },
  { id: PEOPLE.sameerChawla, name: "Sameer Chawla", email: "schawla@mehrarao.example", title: "Associate", organization: "Mehra & Rao Advocates", role: "attorney", tags: ["employment", "regulatory"] },
  { id: PEOPLE.meeraLobo, name: "Meera Lobo", email: "mlobo@mehrarao.example", title: "Litigation Paralegal", organization: "Mehra & Rao Advocates", role: "paralegal" },
  { id: PEOPLE.tanmayBhatt, name: "Tanmay Bhatt", email: "tbhatt@mehrarao.example", title: "E-Discovery Project Manager", organization: "Mehra & Rao Advocates", role: "staff" },
  { id: PEOPLE.aishaKhan, name: "Aisha Khan", email: "akhan@mehrarao.example", title: "Knowledge Management Director", organization: "Mehra & Rao Advocates", role: "staff" },
  { id: PEOPLE.girishHegde, name: "Girish Hegde", email: "g.hegde@meridianfinechem.example", title: "Director, Environmental Health & Safety", organization: "Meridian Fine Chemicals Ltd.", role: "custodian" },
  { id: PEOPLE.hemaVasudevan, name: "Hema Vasudevan", email: "h.vasudevan@meridianfinechem.example", title: "Senior Toxicologist", organization: "Meridian Fine Chemicals Ltd.", role: "custodian" },
  { id: PEOPLE.nandiniBose, name: "Nandini Bose", email: "n.bose@meridianfinechem.example", title: "Product Stewardship Manager", organization: "Meridian Fine Chemicals Ltd.", role: "custodian" },
  { id: PEOPLE.anilPrasad, name: "Anil Prasad", email: "a.prasad@meridianfinechem.example", title: "VP, Textile Chemicals", organization: "Meridian Fine Chemicals Ltd.", role: "custodian" },
  { id: PEOPLE.rohitKapur, name: "Rohit Kapur", email: "r.kapur@meridianfinechem.example", title: "Associate General Counsel", organization: "Meridian Fine Chemicals Ltd.", role: "custodian" },
  { id: PEOPLE.manishSood, name: "Manish Sood", email: "m.sood@meridianfinechem.example", title: "Regulatory Affairs Counsel", organization: "Meridian Fine Chemicals Ltd.", role: "custodian" },
  { id: PEOPLE.drLeelaSundaramTox, name: "Dr. Leela Sundaram", title: "Toxicologist (Sundaram Laboratories)", organization: "Sundaram Laboratories", role: "expert" },
  { id: PEOPLE.drRajPatelHydro, name: "Dr. Raj Patel", title: "Hydrogeologist", organization: "Patel Groundwater Sciences", role: "expert" },
  { id: PEOPLE.opposingCounselKale, name: "Radhika Kale", title: "Counsel for the Claimant", organization: "Kale & Associates", role: "opposing" },
  { id: PEOPLE.arbitratorRangan, name: "Justice (Retd.) Vasudha Rangan", title: "Presiding Arbitrator", organization: "Arbitral Tribunal (Arb. Ref. 14/2024)", role: "judge" },
];

const matters: Matter[] = [
  {
    id: MATTERS.valsara,
    slug: "valsara-v-meridian-arbitration",
    name: "Valsara Textile Park Ltd. v. Meridian Fine Chemicals Ltd.",
    shortName: "Valsara v. Meridian",
    caption: "Arb. Ref. 14/2024 (seat: New Delhi)",
    client: "Meridian Fine Chemicals Ltd.",
    clientSide: "respondent",
    practiceArea: "Commercial",
    court: "Arbitral Tribunal (Arbitration and Conciliation Act, 1996; seat: New Delhi)",
    jurisdiction: "India · Arbitration",
    judge: "Justice (Retd.) Vasudha Rangan (Presiding Arbitrator)",
    status: "active",
    stage: "Tier 2 document production · expert evidence",
    openedAt: "2023-02-14",
    teamIds: [PEOPLE.arjunMehra, PEOPLE.priyaRaman, PEOPLE.eshaMathur, PEOPLE.meeraLobo, PEOPLE.tanmayBhatt],
    leadAttorneyId: PEOPLE.arjunMehra,
    description: "Fictional demo matter. Defence of Meridian Fine Chemicals (Respondent) in an arbitration brought by Valsara Textile Park Ltd. under the 1998 Supply and Technical Services Agreement: claims for breach of the Clause 9.4 substantial-risk notice obligation, product-literature warranties for the MF-3 finishing concentrate, and an indemnity for remediating the Park wellfield next to Meridian's Valsara plant. Current focus: Tier 2 document production, the Clause 9.4 knowledge timeline, and rebuttal of the Claimant's toxicology and hydrogeology experts.",
    keyDates: [
      { label: "Tier 2 production deadline", date: "2026-10-14" },
      { label: "Rebuttal expert reports due", date: "2026-11-06" },
      { label: "Objections to expert evidence", date: "2026-12-18" },
      { label: "Evidentiary hearing (Phase 1)", date: "2027-03-08" },
    ],
    tags: ["arbitration", "contract", "environmental", "indemnity"],
  },
  {
    id: MATTERS.depo,
    slug: "depo-provera-mdl-3140",
    name: "In re: Depo-Provera (Depot Medroxyprogesterone Acetate) Products Liability Litigation",
    shortName: "Depo-Provera",
    caption: "MDL No. 3140 (N.D. Fla.)",
    client: "Confidential pharmaceutical distributor",
    clientSide: "defendant",
    practiceArea: "Products Liability",
    court: "U.S. District Court for the Northern District of Florida",
    jurisdiction: "Federal · 11th Cir.",
    judge: "Hon. M. Casey Rodgers",
    status: "active",
    stage: "Pleadings · science day preparation",
    openedAt: "2025-03-03",
    teamIds: [PEOPLE.priyaRaman, PEOPLE.sameerChawla, PEOPLE.meeraLobo],
    leadAttorneyId: PEOPLE.priyaRaman,
    description: "Meningioma failure-to-warn claims. Monitoring master complaint, preemption strategy, and epidemiology literature (Roland et al. 2024, BMJ).",
    keyDates: [
      { label: "Master answer due", date: "2026-10-02" },
      { label: "Science Day", date: "2026-11-20" },
    ],
    tags: ["MDL", "pharma", "failure to warn", "preemption"],
  },
  {
    id: MATTERS.northgate,
    slug: "northgate-v-apex",
    name: "Northgate Logistics, Inc. v. Apex Freight Systems, LLC",
    shortName: "Northgate v. Apex",
    caption: "No. 1:26-cv-02218 (N.D. Ill.)",
    client: "Northgate Logistics, Inc.",
    clientSide: "plaintiff",
    practiceArea: "Commercial",
    court: "U.S. District Court for the Northern District of Illinois",
    jurisdiction: "Federal · 7th Cir.",
    judge: "Hon. Sara L. Ellis",
    status: "active",
    stage: "Summary judgment briefing",
    openedAt: "2026-01-20",
    teamIds: [PEOPLE.dhruvOberoi, PEOPLE.eshaMathur, PEOPLE.meeraLobo],
    leadAttorneyId: PEOPLE.dhruvOberoi,
    description: "Breach of a master transportation services agreement; indemnity and consequential-damages waiver dispute after cargo losses at the Joliet cross-dock.",
    keyDates: [
      { label: "MSJ opposition due", date: "2026-10-09" },
      { label: "Reply due", date: "2026-10-23" },
      { label: "Final pretrial conference", date: "2027-01-12" },
    ],
    tags: ["contract", "indemnity", "UCC"],
  },
  {
    id: MATTERS.harbor,
    slug: "project-harbor",
    name: "Project Harbor — Acquisition of Bluewater Analytics, Inc.",
    shortName: "Project Harbor",
    client: "Harborline Technologies, Inc.",
    clientSide: "buyer",
    practiceArea: "Corporate / M&A",
    status: "active",
    stage: "Confirmatory diligence · SPA negotiation",
    openedAt: "2026-07-08",
    teamIds: [PEOPLE.dhruvOberoi, PEOPLE.sameerChawla, PEOPLE.aishaKhan],
    leadAttorneyId: PEOPLE.dhruvOberoi,
    description: "$184M cash-and-stock acquisition. Open items: IP assignment chain for the core ML models, change-of-control consents in top-20 customer contracts, R&W insurance binder.",
    keyDates: [
      { label: "SPA signing target", date: "2026-10-30" },
      { label: "HSR filing", date: "2026-11-06" },
    ],
    tags: ["M&A", "diligence", "SPA"],
  },
  {
    id: MATTERS.sterling,
    slug: "sterling-medical-employment",
    name: "Sterling Medical Group — Wage & Hour Class Investigation",
    shortName: "Sterling Medical",
    client: "Sterling Medical Group, P.C.",
    clientSide: "defendant",
    practiceArea: "Employment",
    court: "Superior Court of California, County of Los Angeles",
    jurisdiction: "California",
    status: "pre-suit",
    stage: "Pre-suit investigation · PAGA notice response",
    openedAt: "2026-08-19",
    teamIds: [PEOPLE.sameerChawla, PEOPLE.arjunMehra],
    leadAttorneyId: PEOPLE.sameerChawla,
    description: "Response to a PAGA notice alleging meal-period and rounding violations across 14 clinics. Payroll data analysis and exposure modeling underway.",
    keyDates: [{ label: "LWDA cure period ends", date: "2026-10-21" }],
    tags: ["PAGA", "wage and hour", "class"],
  },
];

export function seedCore(db: Database) {
  db.people.putMany(people);
  // Demo workspace: the sample partner is the owner so the demo reads as a configured firm.
  if (!db.kv.get("workspace")) saveWorkspace({ firmName: "Mehra & Rao Advocates", owner: { id: "p_jwhitfield", name: "Arjun Mehra", email: "amehra@mehrarao.example", role: "Partner" } });
  db.matters.putMany(matters);
}
