import type { TimelineEvent } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "@/lib/seed/ids";
import { EXTRA_PEOPLE_IDS as X } from "./seed-people";

const M = MATTERS.valsara;
const P = PEOPLE;

type Src = TimelineEvent["sources"][number];
const doc = (bates: string, id: string, excerpt?: string): Src => ({ kind: "document", bates, id, excerpt });
const depo = (id: string, cite: string, excerpt?: string): Src => ({ kind: "deposition", id, cite, excerpt });
const ext = (cite: string, excerpt?: string): Src => ({ kind: "external", cite, excerpt });

let n = 0;
function ev(date: string, title: string, category: TimelineEvent["category"], significance: TimelineEvent["significance"], sources: Src[], extra: Partial<TimelineEvent> = {}): TimelineEvent {
  n += 1;
  return { id: `tl_vls_${String(n).padStart(3, "0")}`, matterId: M, date, title, category, significance, sources, createdBy: "user", verified: true, ...extra };
}

/** Valsara arbitration chronology, 1998–2027, every entry sourced to seeded Bates numbers or transcript cites. */
export const VALSARA_TIMELINE: TimelineEvent[] = [
  ev("1998-03-10", "Building 7 floor-drain routing to Lagoon 2 identified as CAP-98-114", "corporate", 2, [doc("MFC-0041988", "ed_vls_0049", "Building 7 floor drain re-route (CAP-98-114)")], { description: "Corrective-action item opened for the tote-wash floor drain that discharged to Lagoon 2; not funded until September 2001.", personIds: [P.girishHegde], precision: "month" }),
  ev("1999-06-15", "Valsara industrial hygiene survey of the blending area", "scientific", 2, [doc("MFC-0041912", "ed_vls_0011", "1999 industrial hygiene survey")], { description: "Measured operator exposures later used by Hegde to compute a 100–300× margin below the Sundaram NOAEL.", personIds: [P.girishHegde], precision: "month" }),
  ev("2000-05-16", "Orbis announces phase-out of MC-8 chemistry", "regulatory", 4, [ext("Orbis press release, 16 May 2000"), doc("MFC-0041964", "ed_vls_0033", "the same active substance that Orbis is withdrawing")], { description: "Industry-wide inflection point; Vasudevan later cites it in rejecting the 'different, biodegradable' marketing claim." }),
  ev("2000-06-05", "Sundaram Laboratories commissioned for 90-day rat study SL-2000-0417", "scientific", 3, [doc("MFC-0041898", "ed_vls_0008", "transmittal letter and invoice")], { personIds: [P.hemaVasudevan, P.drLeelaSundaramTox], precision: "month" }),
  ev("2000-12-08", "Vasudevan flags early liver findings from the Sundaram in-life phase", "scientific", 3, [doc("MFC-0041880", "ed_vls_0002", "the headline is what I flagged in December")], { personIds: [P.hemaVasudevan], precision: "month" }),
  ev("2001-03-14", "Sundaram final report: dose-related liver effects, NOAEL 0.1 mg/kg-day, ~100-day half-life", "scientific", 5, [doc("MFC-0041877", "ed_vls_0001", "FINAL REPORT SUMMARY"), doc("MFC-0041880", "ed_vls_0002", "the liver effects are real, they are dose-related, and they did not fully reverse"), depo("dep_vls_voss_v1", "Vasudevan 24:5")], { personIds: [P.hemaVasudevan, P.girishHegde, P.nandiniBose, P.drLeelaSundaramTox] }),
  ev("2001-03-15", "Prasad: 'keep the report and the summary to the four of us'", "communication", 4, [doc("MFC-0041882", "ed_vls_0004", "Do not forward it to the plant, to marketing, or to the defence qualification cell."), depo("dep_vls_pryce_v1", "Prasad 18:10")], { personIds: [P.anilPrasad, P.hemaVasudevan] }),
  ev("2001-03-16", "Friday working-group meeting: bioassay to be proposed; report held pending Legal", "corporate", 4, [depo("dep_vls_voss_v1", "Vasudevan 43:2"), doc("MFC-0041904", "ed_vls_0009")], { personIds: [P.hemaVasudevan, P.girishHegde, P.nandiniBose, P.anilPrasad, P.manishSood] }),
  ev("2001-03-16", "Vasudevan recalculates dose-response and margin of exposure in lab notebook", "scientific", 2, [doc("MFC-0041884", "ed_vls_0006")], { personIds: [P.hemaVasudevan] }),
  ev("2001-03-18", "Hegde EHS assessment DRAFT v2: 'margins for end-users cannot be established'", "communication", 4, [doc("MFC-0041965", "ed_vls_0034"), depo("dep_vls_hale_v1", "Hegde 25:1")], { personIds: [P.girishHegde] }),
  ev("2001-03-19", "Hegde EHS memo issued: 'no adverse findings at exposures relevant to occupational use'", "communication", 5, [doc("MFC-0041912", "ed_vls_0011", "no adverse findings at exposures relevant to occupational use of the product"), depo("dep_vls_hale_v1", "Hegde 22:10"), depo("dep_vls_voss_v1", "Vasudevan 39:15")], { personIds: [P.girishHegde, P.anilPrasad, X.merrick], disputed: true }),
  ev("2001-03-19", "Sood drafts Clause 9.4 Substantial Risk Notice (never served)", "regulatory", 5, [doc("MFC-0041915", "ed_vls_0013"), doc("MFC-0041914", "ed_vls_0012")], { personIds: [P.manishSood, P.rohitKapur] }),
  ev("2001-03-19", "Prasad to Kapur: commercial consequences of a Clause 9.4 notice; 'bioassay first' path", "communication", 5, [doc("MFC-0041920", "ed_vls_0015", "If there is a defensible path that involves doing the bioassay first and reporting when we actually know something, that is the path I want."), depo("dep_vls_pryce_v1", "Prasad 32:5")], { personIds: [P.anilPrasad, P.rohitKapur] }),
  ev("2001-03-22", "Sood privileged Clause 9.4 analysis memo", "regulatory", 4, [doc("MFC-0041930", "ed_vls_0018")], { personIds: [P.manishSood, P.rohitKapur] }),
  ev("2001-03-26", "Decision not to give the Park a Clause 9.4 notice on the 90-day study", "regulatory", 5, [doc("MFC-0041936", "ed_vls_0020"), depo("dep_vls_voss_v1", "Vasudevan 102:15"), depo("dep_vls_pryce_v1", "Prasad 48:12")], { personIds: [P.manishSood, P.rohitKapur, P.anilPrasad] }),
  ev("2001-04-04", "Prasad keeps MSDS Section 12 'has not been determined'; strikes 'may accumulate'", "product", 4, [doc("MFC-0041942", "ed_vls_0023", "'may accumulate' comes out"), depo("dep_vls_voss_v1", "Vasudevan 155:18"), depo("dep_vls_pryce_v1", "Prasad 49:1")], { personIds: [P.anilPrasad, P.nandiniBose, P.hemaVasudevan] }),
  ev("2001-04-09", "Vasudevan proposes ₹16.2 crore two-year bioassay with monkey kinetics and repro screen", "scientific", 3, [doc("MFC-0041945", "ed_vls_0026"), doc("MFC-0041944", "ed_vls_0025")], { personIds: [P.hemaVasudevan] }),
  ev("2001-04-11", "Prasad approves reduced bioassay design (3 groups, no interim sacrifice, ~₹9.2 crore)", "corporate", 4, [doc("MFC-0041948", "ed_vls_0027", "I will sign the bioassay. I will not sign ₹16.2 crore."), depo("dep_vls_voss_v1", "Vasudevan 48:1"), depo("dep_vls_pryce_v1", "Prasad 39:17")], { personIds: [P.anilPrasad, P.hemaVasudevan, X.merrick] }),
  ev("2001-04-12", "The Sarangpur Co-operative asks about rinse-water discharge at the Sarangpur processing unit", "communication", 3, [doc("MFC-0041950", "ed_vls_0029")], { personIds: [X.duffy, P.girishHegde] }),
  ev("2001-04-24", "Hegde responds to Sarangpur: repellent agent fate 'has not been fully determined'", "communication", 4, [doc("MFC-0041952", "ed_vls_0030", "its behaviour in soil and water has not been fully determined"), depo("dep_vls_hale_v1", "Hegde 70:8")], { personIds: [P.girishHegde, X.duffy] }),
  ev("2001-05-01", "Aqua-Guard 2001–2002 marketing plan drafted with 'biodegradable' claims (Slides 5, 8)", "product", 4, [doc("MFC-0041955", "ed_vls_0032")], { personIds: [P.anilPrasad, X.liu] }),
  ev("2001-05-04", "Vasudevan: 'Slide 8 is false' — MF-3 is the same MC-8 chemistry Orbis is withdrawing", "communication", 5, [doc("MFC-0041964", "ed_vls_0033", "Slide 8 is false."), depo("dep_vls_voss_v1", "Vasudevan 56:3"), depo("dep_vls_pryce_v1", "Prasad 56:5")], { personIds: [P.hemaVasudevan, P.nandiniBose, P.anilPrasad, X.liu] }),
  ev("2001-05-07", "Kapur gives legal advice on marketing claims", "communication", 2, [doc("MFC-0041968", "ed_vls_0036")], { personIds: [P.rohitKapur, P.anilPrasad] }),
  ev("2001-05-11", "Valsara operations review notes: 'Lagoon 2 — south third never lined?'", "corporate", 3, [doc("MFC-0041970", "ed_vls_0038"), depo("dep_vls_hale_v1", "Hegde 33:5")], { personIds: [P.girishHegde] }),
  ev("2001-06-08", "CPCB (Mahesh Phadke) asks whether Meridian has conducted subchronic or chronic studies since 1995", "regulatory", 4, [doc("MFC-0041976", "ed_vls_0040")], { personIds: [P.manishSood, P.rohitKapur, X.feld] }),
  ev("2001-06-15", "Board pre-read: MF-3 toxicology 'well characterized and supports continued sale'", "corporate", 4, [doc("MFC-0041977", "ed_vls_0041"), depo("dep_vls_pryce_v1", "Prasad 64:7")], { personIds: [P.anilPrasad] }),
  ev("2001-06-20", "Board told the rat study 'raised no issues requiring regulatory action'", "corporate", 4, [doc("MFC-0041978", "ed_vls_0042"), depo("dep_vls_pryce_v1", "Prasad 65:18")], { personIds: [P.anilPrasad, P.rohitKapur] }),
  ev("2001-08-09", "Konkan Weaves Ltd. complains of a fish kill after finish discharge", "communication", 3, [doc("MFC-0041981", "ed_vls_0044")], { personIds: [P.nandiniBose] }),
  ev("2001-08-20", "MW-7 installed downgradient of Lagoon 2", "corporate", 3, [depo("dep_vls_hale_v1", "Hegde 34:2")], { personIds: [P.girishHegde, X.nunez], precision: "month" }),
  ev("2001-09-18", "First MC-8 detection in Valsara groundwater: MW-7 at 12.0 µg/L", "scientific", 5, [doc("MFC-0041988", "ed_vls_0049", "MW-7 (downgradient of Lagoon 2, 5.5–8.5 m screen): MC-8 12.0 µg/L"), depo("dep_vls_hale_v1", "Hegde 38:9")], { personIds: [P.girishHegde, X.nunez] }),
  ev("2001-10-04", "Sundaram confirms every high-dose recovery animal retained >70% of serum MC-8", "scientific", 4, [doc("MFC-0041986", "ed_vls_0047"), depo("dep_vls_voss_v1", "Vasudevan 63:9")], { personIds: [P.hemaVasudevan, P.drLeelaSundaramTox] }),
  ev("2001-11-15", "Q3 2001 EHS quarterly report distributed with MW-7 result", "communication", 3, [doc("MFC-0041987", "ed_vls_0048"), doc("MFC-0041988", "ed_vls_0049")], { personIds: [P.girishHegde, X.merrick, P.anilPrasad, P.nandiniBose] }),
  ev("2002-02-19", "Two-year bioassay 3-month serum: not at steady state, rising in every dose group", "scientific", 3, [doc("MFC-0041999", "ed_vls_0055"), doc("MFC-0042000", "ed_vls_0056"), depo("dep_vls_voss_v1", "Vasudevan 79:3")], { personIds: [P.hemaVasudevan] }),
  ev("2002-07-03", "Beacon Q2 2002 groundwater report: MW-7 at 41 µg/L, MW-8 property line 6.8 µg/L", "scientific", 5, [doc("MFC-0052212", "ed_vls_0058"), depo("dep_vls_hale_v1", "Hegde 48:3")], { personIds: [X.nunez, P.girishHegde] }),
  ev("2002-07-08", "Hegde recommends notifying GPCB 'voluntarily, now' and sampling the Park's wells", "communication", 5, [doc("MFC-0052210", "ed_vls_0057", "we have an off-site migration of a compound we know is persistent and bioaccumulative, toward the Park's drinking-water supply"), depo("dep_vls_hale_v1", "Hegde 47:6")], { personIds: [P.girishHegde, P.anilPrasad, P.manishSood], disputed: true }),
  ev("2002-07-09", "Prasad: 'Do not put this in email … Nothing goes to the Board or to the Park until Legal has looked at it'", "communication", 5, [doc("MFC-0052217", "ed_vls_0059"), depo("dep_vls_pryce_v1", "Prasad 72:14"), depo("dep_vls_hale_v1", "Hegde 52:1")], { personIds: [P.anilPrasad, P.girishHegde] }),
  ev("2002-07-09", "2 p.m. meeting: close Lagoon 2, add wells, hold notification pending another data round", "corporate", 4, [depo("dep_vls_hale_v1", "Hegde 56:9"), doc("MFC-0052219", "ed_vls_0061"), doc("MFC-0052218", "ed_vls_0060")], { personIds: [P.anilPrasad, P.manishSood, X.merrick, P.rohitKapur, P.girishHegde] }),
  ev("2002-07-15", "GPCB (Jyoti Rathore) calls; Hegde 'did not raise MW-7'", "regulatory", 4, [doc("MFC-0052220", "ed_vls_0062"), depo("dep_vls_hale_v1", "Hegde 50:8")], { personIds: [P.girishHegde, X.rourke] }),
  ev("2002-09-11", "12-month interim: hepatocellular adenomas in mid- and high-dose males", "scientific", 5, [doc("MFC-0052226", "ed_vls_0066"), doc("MFC-0052225", "ed_vls_0065"), depo("dep_vls_voss_v1", "Vasudevan 91:18")], { personIds: [P.hemaVasudevan, P.drLeelaSundaramTox] }),
  ev("2002-09-16", "Kapur: decision to give a Clause 9.4 notice on the interim results", "regulatory", 4, [doc("MFC-0052236", "ed_vls_0067")], { personIds: [P.rohitKapur, P.manishSood, P.hemaVasudevan] }),
  ev("2002-10-07", "Prasad responds to DQA-T: no substantial-risk notice 'to date'; tumours not mentioned", "communication", 5, [doc("MFC-0052238", "ed_vls_0069"), doc("MFC-0052237", "ed_vls_0068"), depo("dep_vls_pryce_v1", "Prasad 89:10")], { personIds: [P.anilPrasad, X.whitcomb] }),
  ev("2002-10-24", "Hegde letter notifies Valsara Textile Park Ltd.; offers wellfield sampling (108 days after 'now')", "regulatory", 5, [doc("MFC-0052221", "ed_vls_0063"), depo("dep_vls_hale_v1", "Hegde 61:4")], { personIds: [P.girishHegde, X.ferrante, P.manishSood] }),
  ev("2002-10-28", "Clause 9.4 notice served on the Park on two-year bioassay interim results", "regulatory", 5, [depo("dep_vls_voss_v1", "Vasudevan 102:7"), depo("dep_vls_pryce_v1", "Prasad 210:16"), ext("Park's acknowledgement of the Clause 9.4 notice (to be confirmed)")], { personIds: [P.manishSood, P.rohitKapur], verified: false }),
  ev("2003-02-11", "Product stewardship review of MC-8 alternatives; human half-life scaled to years", "product", 3, [doc("MFC-0052239", "ed_vls_0070"), depo("dep_vls_voss_v1", "Vasudevan 72:6")], { personIds: [P.nandiniBose, P.hemaVasudevan] }),
  ev("2003-05-20", "CPCB information request response plan", "regulatory", 3, [doc("MFC-0052242", "ed_vls_0071")], { personIds: [P.manishSood] }),
  ev("2003-09-30", "Valsara worker serum biomonitoring: median MC-8 ~1,900 ng/mL", "scientific", 4, [depo("dep_vls_voss_v1", "Vasudevan 131:3")], { personIds: [P.hemaVasudevan], precision: "month", verified: false }),
  ev("2004-06-30", "MW-7 peaks at 66 µg/L", "scientific", 3, [depo("dep_vls_hale_v1", "Hegde 91:12"), doc("MFC-0052246", "ed_vls_0072")], { personIds: [P.girishHegde], precision: "month", verified: false }),
  ev("2005-02-28", "Two-year bioassay final report: positive for liver carcinogenicity in the rat", "scientific", 5, [doc("MFC-0052248", "ed_vls_0074"), doc("MFC-0052247", "ed_vls_0073"), depo("dep_vls_voss_v1", "Vasudevan 118:9")], { personIds: [P.hemaVasudevan, P.drLeelaSundaramTox] }),
  ev("2006-06-19", "Aqua-Guard MF-5 transition timeline adopted", "product", 4, [doc("MFC-0052251", "ed_vls_0075"), depo("dep_vls_pryce_v1", "Prasad 106:3")], { personIds: [P.anilPrasad] }),
  ev("2008-09-30", "Meridian joins CPCB voluntary MC-7 phase-down programme; Aqua-Guard 3/6 discontinued", "regulatory", 3, [doc("MFC-0052252", "ed_vls_0076"), depo("dep_vls_pryce_v1", "Prasad 219:8")], { personIds: [P.manishSood, P.anilPrasad] }),
  ev("2010-02-16", "Customer letter discloses MC-8 content and persistence to customers of record", "communication", 4, [doc("MFC-0052254", "ed_vls_0078"), doc("MFC-0052253", "ed_vls_0077"), depo("dep_vls_pryce_v1", "Prasad 114:9")], { personIds: [P.nandiniBose] }),
  ev("2011-08-23", "GPCB monitoring term ends; MW-7 at ~9 µg/L", "regulatory", 2, [doc("MFC-0052256", "ed_vls_0079"), depo("dep_vls_hale_v1", "Hegde 91:12")], { personIds: [P.girishHegde] }),
  ev("2012-04-11", "Litigation hold issued — Valsara / MC-8 claims", "litigation", 4, [doc("MFC-0052257", "ed_vls_0080")], { personIds: [P.rohitKapur] }),
  ev("2012-11-29", "Retrospective review of the March 2001 Clause 9.4 decision (work product)", "litigation", 3, [doc("MFC-0052258", "ed_vls_0081")], { personIds: [P.manishSood, P.rohitKapur] }),
  ev("2016-08-19", "Kapur Clause 9.4 recommendation for the Tuesday call", "regulatory", 3, [doc("MFC-0043877", "ed_vls_kaine_0001")], { personIds: [P.rohitKapur] }),
  ev("2016-09-06", "Privileged 2016 Clause 9.4 analysis (draft)", "regulatory", 3, [doc("MFC-0043902", "ed_vls_kaine_0003")], { personIds: [P.rohitKapur] }),
  ev("2016-10-03", "Decision memo — final (2016 notification review)", "regulatory", 3, [doc("MFC-0043951", "ed_vls_kaine_0006")], { personIds: [P.rohitKapur] }),
  ev("2017-11-02", "Benchmark-dose analysis: BMDL10 0.03 mg/kg-day for hepatic endpoints", "scientific", 3, [doc("MFC-0043211", "ed_vls_43211"), depo("dep_vls_voss_v1", "Vasudevan 139:4")], { personIds: [P.hemaVasudevan] }),
  ev("2017-10-11", "Q3 2017 EHS report references July/August 2017 groundwater interims that cannot be located", "litigation", 4, [doc("MFC-0043105", "ed_vls_43105"), depo("dep_vls_hale_v1", "Hegde 190:14")], { personIds: [P.girishHegde], disputed: true }),
  ev("2023-01-20", "Valsara Textile Park Ltd. serves notice of arbitration (Arb. Ref. 14/2024)", "litigation", 4, [ext("Notice of arbitration under Clause 21 of the 1998 Supply and Technical Services Agreement, 20 Jan 2023")], { personIds: [P.opposingCounselKale] }),
  ev("2023-02-14", "Mehra & Rao engaged for Meridian Fine Chemicals", "litigation", 2, [ext("Engagement letter")], { personIds: [P.arjunMehra, P.priyaRaman] }),
  ev("2026-05-13", "Deposition of Girish Hegde, Vol. I", "testimony", 4, [depo("dep_vls_hale_v1", "Hegde Vol. I")], { personIds: [P.girishHegde, P.opposingCounselKale, P.arjunMehra] }),
  ev("2026-06-17", "Deposition of Hema Vasudevan, Vol. I", "testimony", 4, [depo("dep_vls_voss_v1", "Vasudevan Vol. I")], { personIds: [P.hemaVasudevan, P.opposingCounselKale, P.arjunMehra] }),
  ev("2026-07-22", "Deposition of Anil Prasad", "testimony", 4, [depo("dep_vls_pryce_v1", "Prasad Vol. I")], { personIds: [P.anilPrasad, P.opposingCounselKale, P.arjunMehra, P.priyaRaman] }),
  ev("2026-09-10", "Deposition of Nandini Bose (rough transcript)", "testimony", 3, [depo("dep_vls_brooks_v1", "Bose Vol. I")], { personIds: [P.nandiniBose, P.priyaRaman] }),
  ev("2026-09-24", "Deposition of Girish Hegde, Vol. II (2015–2019 EHS reporting)", "testimony", 3, [depo("dep_vls_hale_v2", "Hegde Vol. II")], { personIds: [P.girishHegde, P.arjunMehra, P.opposingCounselKale], verified: false }),
  ev("2026-10-14", "Tier 2 custodial production deadline", "litigation", 4, [ext("Procedural Order No. 4 ¶ 14")], { verified: false }),
  ev("2026-10-21", "Deposition of Manish Sood (scheduled)", "testimony", 3, [depo("dep_vls_suarez_v1", "Sood")], { personIds: [P.manishSood], verified: false }),
  ev("2026-11-06", "Rebuttal expert reports due", "litigation", 3, [ext("Procedural Order No. 4 ¶ 22")], { verified: false }),
  ev("2027-03-08", "Evidentiary hearing (Phase 1)", "litigation", 5, [ext("Procedural Order No. 4, hearing schedule")], { verified: false }),
];
