import type { Deposition } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "@/lib/seed/ids";
import { KALE, MEHRA, obj, qa } from "./seed-helpers";

/**
 * Deposition of Hema Vasudevan, Senior Toxicologist, Meridian Fine Chemicals Ltd.
 * Taken by the Claimant (Radhika Kale); defended by Arjun Mehra.
 * Excerpted Q/A spanning pages 8–241 of a 248-page transcript.
 */
export const VOSS_DEPOSITION: Deposition = {
  id: "dep_vls_voss_v1",
  matterId: MATTERS.valsara,
  witnessId: PEOPLE.hemaVasudevan,
  witnessName: "Hema Vasudevan",
  witnessTitle: "Senior Toxicologist, Meridian Fine Chemicals Ltd.",
  date: "2026-06-17",
  takenBy: "Radhika Kale (Counsel for the Claimant)",
  defendingBy: "Arjun Mehra (Mehra & Rao Advocates)",
  location: "Mehra & Rao Advocates, 21 Kasturba Gandhi Marg, New Delhi 110001 — Conference Room 4B",
  volume: 1,
  pages: 248,
  status: "reviewed",
  exhibits: [
    { id: "Vasudevan-1", description: "Sundaram Toxicology 90-day rat study, final report summary (14 Mar 2001)", bates: "MFC-0041877" },
    { id: "Vasudevan-2", description: "Vasudevan email to Hegde and Bose, 'Sundaram final — 90-day rat study' (14 Mar 2001)", bates: "MFC-0041880" },
    { id: "Vasudevan-3", description: "Vasudevan laboratory notebook, dose-response recalculation (16 Mar 2001)", bates: "MFC-0041884" },
    { id: "Vasudevan-4", description: "Proposal — two-year bioassay and monkey kinetics (9 Apr 2001)", bates: "MFC-0041945" },
    { id: "Vasudevan-5", description: "Vasudevan email, 'RE: Marketing plan — biodegradable claim' (4 May 2001)", bates: "MFC-0041964" },
    { id: "Vasudevan-6", description: "Sundaram reply re raw serum data (4 Oct 2001)", bates: "MFC-0041986" },
    { id: "Vasudevan-7", description: "Two-year bioassay 12-month interim report (11 Sep 2002)", bates: "MFC-0052226" },
    { id: "Vasudevan-8", description: "Two-year bioassay final report summary (28 Feb 2005)", bates: "MFC-0052248" },
    { id: "Vasudevan-9", description: "SL-2001-0512 dose groups and 3-month serum (19 Feb 2002)", bates: "MFC-0042000" },
    { id: "Vasudevan-10", description: "Benchmark-dose analysis — hepatic endpoints, draft 2 (2 Nov 2017)", bates: "MFC-0043211" },
    { id: "Vasudevan-11", description: "Hegde EHS assessment memo (19 Mar 2001)", bates: "MFC-0041912" },
  ],
  transcript: [
    qa(8, 4, "Please state your full name for the record.", "Hema Lakshmi Vasudevan."),
    qa(8, 9, "Ms. Vasudevan, what is your current position at Meridian Fine Chemicals?", "I am a senior toxicologist in the Product Safety group. I have held that title since 1998. Before that I was a staff toxicologist at Meridian from 1994."),
    qa(9, 2, "And your educational background?", "B.Sc. in biology, 1988. Ph.D. in toxicology, 1993. I am a board-certified toxicologist, certified 1997 and recertified since."),
    qa(11, 14, "In March 2001, to whom did you report?", "Administratively I reported to Girish Hegde, the Director of EHS. For product safety questions I worked directly with Nandini Bose in Product Stewardship, and Anil Prasad's group was the internal client for the repellent agent work."),
    qa(14, 6, "Let's talk about Sundaram Laboratories. What was Sundaram's role?", "Sundaram was the contract research organization Meridian used for regulatory toxicology. Dr. Leela Sundaram was the study director on the 90-day study and later on the two-year bioassay."),
    qa(16, 21, "Who selected Sundaram?", "I recommended them. They were GLP-compliant, they had a good pathology group, and they had done work for us in the early nineties."),
    qa(19, 3, "I am handing you what has been marked Vasudevan Exhibit 1. Do you recognize it?", "Yes. This is the summary of the Sundaram 90-day oral toxicity study of MF-3 concentrate. Study number SL-2000-0417.", { exhibit: "Vasudevan-1" }),
    qa(19, 15, "The document is titled 'final report summary.' Is that what it was?", "That is what Sundaram called it. From my perspective, in March 2001 it was a preliminary result. We did not yet have the individual animal data, and I had not completed my own review.", { flags: ["contradiction", "key"], note: "Cf. MFC-0041877 header 'FINAL REPORT SUMMARY' and Vasudevan's own 14 Mar 2001 email calling it 'the Sundaram final' (MFC-0041880). Core contradiction for cross." }),
    qa(20, 8, "Does the word 'preliminary' appear anywhere on Exhibit 1?", "I do not believe it does, no."),
    qa(20, 17, "Does the word 'final' appear?", "In the title, yes.", { flags: ["admission"] }),
    qa(22, 2, "Exhibit 2 is an email from you dated March 14, 2001. Is that your email?", "Yes.", { exhibit: "Vasudevan-2" }),
    qa(22, 11, "You wrote, quote, 'The Sundaram final came in this afternoon.' Did I read that correctly?", "You did."),
    qa(22, 19, "So on March 14, 2001, you described the report as 'the Sundaram final'?", "I used Sundaram's label. Scientists use 'final' to mean the sponsor deliverable has been issued. It does not mean the interpretation is settled.", { objection: obj(MEHRA, "asked-and-answered"), flags: ["evasive", "contradiction"] }),
    qa(24, 5, "In the same email you wrote, 'the liver effects are real, they are dose-related, and they did not fully reverse in the recovery animals.' Was that your scientific opinion on March 14, 2001?", "It was my read of the summary tables at that time, yes.", { flags: ["admission", "key"] }),
    qa(25, 12, "Was there anything preliminary about that opinion?", "The direction of the effect was clear. The magnitude and its relevance to humans were not.", { objection: obj(MEHRA, "form") }),
    qa(28, 1, "You also wrote that Dr. Sundaram's verbal estimate of the half-life in the rat was, quote, 'on the order of 100 days.' Do you recall that conversation?", "I recall that Leela gave me a rough number on the phone. I would not have treated it as a determined value."),
    qa(28, 14, "But you thought it important enough to put in an email to your colleagues?", "I put it in because it was the number that worried me. I said so in the email.", { flags: ["admission"] }),
    qa(31, 9, "Prior to March 2001, had Meridian ever had an estimate of the elimination half-life of MF-3 in any species?", "Not a measured one. The 1993 study had a 14-day recovery period and reported that serum levels were, I think, 'declining.' Nobody calculated a half-life from it.", { flags: ["key"] }),
    qa(34, 20, "Exhibit 3 is a page from your laboratory notebook dated March 16, 2001. What were you doing?", "I was recalculating the dose-response using Sundaram's group means and working out a margin of exposure against the 1999 industrial hygiene data for the Valsara blending area.", { exhibit: "Vasudevan-3" }),
    qa(35, 11, "What margin did you calculate for plant workers?", "Roughly 100 to 300-fold below the NOAEL, depending on the absorption assumption."),
    qa(35, 22, "And for finishing-line workers handling the baths?", "I did not have exposure data for finishing-line workers. I noted that dermal contact was the main route and that margins were likely lower. I flagged it as a data gap."),
    qa(38, 7, "Did you tell Mr. Hegde that the finishing-line worker margin was a data gap?", "I told him, and it is in his memo. Exhibit 11, paragraph 3, says margins for finishing-line use are lower and should be evaluated further. That sentence came from me.", { exhibit: "Vasudevan-11", flags: ["key"] }),
    qa(39, 15, "Paragraph 2 of Mr. Hegde's memo says, quote, 'there are no adverse findings at exposures relevant to occupational use of the product.' Did that sentence come from you?", "No. That was Girish's framing. I would not have written 'no adverse findings' about a study that found dose-related liver effects.", { flags: ["key", "admission"], note: "Vasudevan distances herself from the 'no adverse findings' language in MFC-0041912. Compare Hegde 61:4 (Hegde says Vasudevan reviewed and approved the memo)." }),
    qa(40, 6, "Did you object to that sentence at the time?", "I raised it with Girish verbally. I did not put anything in writing.", { objection: obj(MEHRA, "foundation") }),
    qa(43, 2, "Let's go to the Friday meeting. March 16, 2001. Who attended?", "Girish Hegde, Nandini Bose, Anil Prasad, and me. Manish Sood joined for the last part."),
    qa(43, 18, "What was decided?", "Two things. That we would propose a two-year bioassay, and that the report would not go outside the group until Legal had looked at the reporting question."),
    qa(44, 13, "Who said the report should not go outside the group?", "Anil. He had said the same thing in an email the day before.", { flags: ["key"] }),
    qa(47, 9, "Exhibit 4 is your proposal for the two-year bioassay. You proposed four dose groups, a 12-month interim sacrifice, a monkey kinetics study, and a reproductive screen, at a cost of about ₹16.2 crore. Correct?", "Correct.", { exhibit: "Vasudevan-4" }),
    qa(48, 1, "What was approved?", "Three dose groups, no interim sacrifice, no monkey study, no repro screen. Serum only at 12 months. About ₹9,20,00,000."),
    qa(48, 14, "Was the reduced design scientifically adequate?", "It was adequate to detect a carcinogenic effect. It was not adequate to characterize the dose-response at the low end, which was the question that mattered for human risk. I said that at the time.", { flags: ["admission", "key"] }),
    qa(49, 8, "Who made the decision to reduce the design?", "Anil Prasad. It was a budget decision."),
    qa(49, 16, "Did anyone tell you the design was reduced for scientific reasons?", "Anil's email said Sundaram had told Pankaj Malhotra that a three-group design still gives you a NOAEL. That is true as far as it goes. It was not the reason.", { objection: obj(MEHRA, "speculation", "Calls for speculation as to Mr. Prasad's reasons."), flags: ["key"] }),
    qa(56, 3, "Exhibit 5. This is your May 4, 2001 email about the marketing plan. You wrote 'Slide 8 is false.' What was Slide 8?", "Slide 8 described MF-3 as a, quote, 'different, biodegradable repellent agent' from the Orbis product. It was the same active substance, MC-8 sodium salt.", { exhibit: "Vasudevan-5", flags: ["key"] }),
    qa(57, 1, "Did the deck go out with Slide 8?", "I was told it was revised. I never saw the final version."),
    qa(57, 12, "Did anyone respond to your email?", "Nandini agreed with me. Anil's response was that Legal would look at the claims. Rohit Kapur was copied on the next round."),
    qa(62, 20, "I want to go to the raw serum data. Exhibit 6 is Dr. Sundaram's reply to your October 2001 request. Why did you want the individual animal data?", "Because the group means hid the variability. I wanted to see whether the recovery animals were all retaining the material or whether one or two outliers were driving the mean.", { exhibit: "Vasudevan-6" }),
    qa(63, 9, "And what did the individual data show?", "All of them. Every recovery animal in the high-dose group retained more than 70 percent of its terminal serum concentration after 28 days.", { flags: ["admission", "key"] }),
    qa(64, 2, "Did you communicate that finding to anyone?", "I told Girish and Nandini. I believe I told Anil in a hallway conversation. I did not write a memo.", { objection: obj(MEHRA, "compound") }),
    qa(71, 15, "Did you ever calculate a human half-life for MC-8?", "Not in 2001. In 2003 I did a rough allometric scaling that put it in the range of years rather than days. That was consistent with what Orbis had published by then."),
    qa(72, 6, "Did you share that calculation with anyone?", "It went into the MC-8 alternatives review in February 2003. Nandini's memo."),
    qa(78, 10, "Exhibit 9 is the spreadsheet of 3-month serum results from the two-year study. Whose spreadsheet is this?", "Mine. Sundaram sent the data in a PDF table and I re-keyed it.", { exhibit: "Vasudevan-9" }),
    qa(79, 3, "What did the 3-month serum results tell you?", "That the animals were not at steady state. Serum was still rising in every dose group. That meant the body burden at two years was going to be much higher than the 90-day study had suggested.", { flags: ["key"] }),
    qa(84, 12, "Prior to the 12-month interim in September 2002, did you have any concern that MF-3 was carcinogenic?", "Concern is a strong word. Persistent liver enlargement is a known precursor to liver tumors in rodents. I would have said the possibility could not be excluded.", { flags: ["evasive"] }),
    qa(85, 4, "Did you say that to anyone in writing before September 2002?", "The bioassay proposal says a chronic study is needed to evaluate carcinogenic potential. That is the standard language."),
    qa(91, 18, "Exhibit 7, the 12-month interim. Please turn to the histopathology table. What did the interim show?", "Hepatocellular adenomas in the mid- and high-dose males at 12 months. Five in the high-dose group against zero in controls.", { exhibit: "Vasudevan-7", flags: ["admission", "key"] }),
    qa(92, 9, "Was that a surprise?", "The timing was. Twelve months is early for adenomas in a Sprague-Dawley rat."),
    qa(93, 1, "What did you do when you received it?", "I read it the evening it arrived. I emailed Girish and Anil the next morning and asked for a meeting with Legal."),
    qa(93, 14, "Why Legal?", "Because in my view the interim was a substantial-risk finding under Clause 9.4, and I wanted that decision made by the people responsible for it.", { objection: obj(MEHRA, "privilege", "Counsel instructs the witness not to disclose the content of communications with in-house counsel. The witness may answer as to her own state of mind."), flags: ["privilege", "key"] }),
    qa(102, 7, "Did Meridian give a Clause 9.4 notice after the 12-month interim?", "Yes. I understand a notice was given in October 2002."),
    qa(102, 15, "Did Meridian give a Clause 9.4 notice after the 90-day study in 2001?", "No."),
    qa(103, 2, "In your opinion as a toxicologist, did the 90-day study, together with the half-life information, constitute information that reasonably supported a conclusion of substantial risk?", "I am not a lawyer. Scientifically, the 90-day study told us the material was hepatotoxic and very persistent. Whether that meets the contractual standard was Manish's and Rohit's call.", { objection: obj(MEHRA, "form", "Calls for a legal conclusion."), flags: ["evasive"] }),
    qa(118, 9, "Exhibit 8, the final report summary from February 2005. Is it fair to say the study found MF-3 to be a rat liver carcinogen?", "The study found a statistically significant, dose-related increase in hepatocellular adenomas and carcinomas in males and adenomas in females. Yes, by the usual criteria it is positive for liver carcinogenicity in the rat.", { exhibit: "Vasudevan-8", flags: ["admission", "key"] }),
    qa(119, 6, "And thyroid?", "Follicular cell adenomas were increased in high-dose males. The pathologist considered them secondary to the hepatic enzyme induction. I thought that was a reasonable interpretation."),
    qa(126, 14, "Did Meridian ever conduct a study of MF-3 exposure in finishing-line workers?", "No."),
    qa(126, 20, "Did anyone ever propose one?", "I proposed a serum biomonitoring study of Valsara plant workers in 2003. It was approved. Finishing-line workers were outside our control; we did not have access to a population."),
    qa(131, 3, "What did the 2003 biomonitoring show?", "Median serum MC-8 in blending-area workers of about 1,900 nanograms per milliliter. General population at the time was in the range of 30 to 40."),
    qa(138, 11, "Let's go to 2016. Exhibit 10 is a benchmark-dose analysis you prepared in 2017. Why did you prepare it?", "Legal asked for an updated point of departure for the hepatic endpoints using current benchmark-dose methodology, in connection with the 2016 notification review.", { exhibit: "Vasudevan-10", objection: obj(MEHRA, "privilege", "To the extent the answer reveals the substance of a request from counsel, I instruct the witness not to answer. She may identify the document."), flags: ["privilege"] }),
    qa(139, 4, "What benchmark dose did you calculate?", "A BMDL10 of 0.03 milligrams per kilogram per day for hepatocellular hypertrophy. That is roughly a factor of three below the 2001 NOAEL."),
    qa(147, 16, "Ms. Vasudevan, did you ever, at any time between 2001 and 2016, tell anyone at Meridian that you disagreed with the decision not to give the Park notice of the 90-day study?", "I told Manish Sood in 2001 that I thought the notice should go. I told Rohit Kapur the same thing in 2016.", { flags: ["admission", "key"], note: "Strong admission. Consider whether the 2001 conversation with Sood is privileged (Sood is Regulatory Affairs Counsel); Sundaram did not instruct." }),
    qa(148, 7, "Was that in writing?", "No. Both were conversations."),
    qa(155, 2, "Let me ask about the MSDS. In April 2001 Ms. Bose proposed revising Sections 11 and 12. What was your role?", "I drafted the toxicology language for Section 11. I proposed 'may accumulate in the body' and 'not expected to biodegrade' for the repellent agent."),
    qa(155, 18, "Was your language adopted?", "No. Anil kept 'eliminated slowly' and struck 'may accumulate.' Section 12 stayed at 'has not been determined.'"),
    qa(156, 9, "Who made that decision?", "Anil Prasad. It is in his email of April 4."),
    qa(156, 20, "Did Mr. Hegde have any role in the MSDS language?", "Not that I recall. It was Product Stewardship and Anil.", { flags: ["contradiction"], note: "Hegde testified (Hegde 142:6) that he 'signed off on the MSDS language with Hema.' Testimony-vs-testimony conflict." }),
    qa(171, 5, "Have you ever spoken with Dr. Sundaram about her evidence in this arbitration?", "No."),
    qa(184, 12, "Did you review documents to prepare for today?", "Yes, with counsel."),
    qa(184, 19, "Which documents?", "The exhibits you have shown me, and my own emails from 2001 and 2002.", { objection: obj(MEHRA, "privilege", "The witness may identify documents she reviewed; she may not describe counsel's selection or discussion.") }),
    qa(203, 8, "Ms. Vasudevan, as you sit here today, do you believe the 90-day study was a preliminary result?", "I believe the interpretation was preliminary. The data were what they were.", { objection: obj(MEHRA, "asked-and-answered"), flags: ["evasive", "contradiction"] }),
    qa(204, 2, "And the data showed dose-related liver toxicity and a very long half-life?", "Yes.", { flags: ["admission", "key"] }),
    // Examination by defending counsel
    qa(226, 3, "Ms. Vasudevan, this is Arjun Mehra. A few questions. When you used the word 'final' in your March 14, 2001 email, what did you mean?", "That Sundaram had issued its deliverable. The sponsor review — my review — was still ahead.", { objection: obj(KALE, "form", "Leading.") }),
    qa(226, 16, "Does a sponsor review typically change the conclusions of a CRO report?", "It can. In this case it did not change the direction of the findings. It refined the numbers.", { objection: obj(KALE, "relevance") }),
    qa(228, 9, "Between March 2001 and September 2002, did Meridian take any steps in response to the 90-day study?", "Yes. We commissioned the two-year bioassay, we started serum biomonitoring planning, and Product Stewardship revised customer guidance on rinse water.", { objection: obj(KALE, "form", "Compound and leading.") }),
    qa(233, 14, "Was the reduced bioassay design capable of identifying carcinogenic potential?", "Yes. And it did."),
    qa(241, 1, "Thank you. Nothing further.", "(Whereupon, the deposition was adjourned at 5:42 p.m.)"),
  ],
  aiDigest: undefined,
};
