import type { Deposition } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "@/lib/seed/ids";
import { KALE, MEHRA, obj, qa } from "./seed-helpers";

/**
 * Deposition of Anil Prasad, Vice President, Textile Chemicals,
 * Meridian Fine Chemicals Ltd. Taken by Radhika Kale; defended by Arjun
 * Mehra with Priya Raman. Rough transcript, certified copy pending.
 */
export const PRYCE_DEPOSITION: Deposition = {
  id: "dep_vls_pryce_v1",
  matterId: MATTERS.valsara,
  witnessId: PEOPLE.anilPrasad,
  witnessName: "Anil Prasad",
  witnessTitle: "Vice President, Textile Chemicals, Meridian Fine Chemicals Ltd.",
  date: "2026-07-22",
  takenBy: "Radhika Kale (Counsel for the Claimant)",
  defendingBy: "Arjun Mehra / Priya Raman (Mehra & Rao Advocates)",
  location: "Meridian Fine Chemicals Ltd., Plot 18, Industrial Estate Road, Valsara, Gujarat — Boardroom",
  volume: 1,
  pages: 231,
  status: "transcribed",
  exhibits: [
    { id: "Prasad-1", description: "Prasad email, 'RE: Sundaram final' — 'keep to the four of us' (15 Mar 2001)", bates: "MFC-0041882" },
    { id: "Prasad-2", description: "Prasad email to Kapur, 'RE: timing — commercial consequences' (19 Mar 2001)", bates: "MFC-0041920" },
    { id: "Prasad-3", description: "Prasad email, 'RE: MSDS revision — keep the language as is' (4 Apr 2001)", bates: "MFC-0041942" },
    { id: "Prasad-4", description: "Prasad email, 'RE: bioassay proposal — budget' (11 Apr 2001)", bates: "MFC-0041948" },
    { id: "Prasad-5", description: "Aqua-Guard 2001–2002 marketing plan deck (1 May 2001)", bates: "MFC-0041955" },
    { id: "Prasad-6", description: "Prasad email, 'RE: Marketing plan — biodegradable claim' (4 May 2001)", bates: "MFC-0041967" },
    { id: "Prasad-7", description: "Prasad email, 'Do not put this in email' (9 Jul 2002)", bates: "MFC-0052217" },
    { id: "Prasad-8", description: "Prasad response to DQA-T, DTS-24385F qualification (7 Oct 2002)", bates: "MFC-0052238" },
    { id: "Prasad-9", description: "Board pre-read — repellent agent strategy (15 Jun 2001)", bates: "MFC-0041977" },
    { id: "Prasad-10", description: "Aqua-Guard MF-5 transition timeline (19 Jun 2006)", bates: "MFC-0052251" },
    { id: "Prasad-11", description: "Vasudevan email, 'RE: Marketing plan' — 'Slide 8 is false' (4 May 2001)", bates: "MFC-0041964" },
    { id: "Prasad-12", description: "Board minutes excerpt (20 Jun 2001)", bates: "MFC-0041978" },
  ],
  transcript: [
    qa(5, 8, "Please state your name.", "Anil Tarun Prasad."),
    qa(5, 14, "Mr. Prasad, what was your position in 2001?", "Vice President, Textile Chemicals. I had the Aqua-Guard line, the hardware line, and the government sales group."),
    qa(6, 5, "To whom did you report?", "The CEO, Dinesh Pherwani."),
    qa(6, 12, "Who reported to you?", "Nandini Bose in Product Stewardship, the sales directors, marketing under Kavita Lal, and the DTS program office."),
    qa(9, 3, "Did Ms. Vasudevan report to you?", "No. Hema was in Product Safety, under Girish Hegde. Her group did work for my business unit."),
    qa(12, 17, "How large was the Aqua-Guard business in 2000?", "About 4.2 million litres and roughly ₹610 crore in revenue. It was the most profitable line in the company."),
    qa(13, 6, "What fraction went to defence fabric mills?", "The defence rate contract was about 35 percent by volume. Paramilitary uniform mills through central tenders, another 15."),
    qa(18, 1, "When did you first learn of the Sundaram 90-day results?", "Hema's email. March 14, 2001. I read it that night."),
    qa(18, 10, "Exhibit 1 is your reply the next day. You wrote, 'please keep the report and the summary to the four of us. Do not forward it to the plant, to marketing, or to the defence qualification cell.' Why?", "Because a toxicology report is not something you circulate before the people who understand it have decided what it means. I did not want a garbled version reaching customers.", { exhibit: "Prasad-1", flags: ["key"] }),
    qa(19, 2, "Did you ever restrict the distribution of the Sundaram report?", "I did not restrict it. I asked that it stay within the working group until we had met on Friday.", { flags: ["contradiction", "evasive"], note: "'keep to the four of us … do not forward' (MFC-0041882) is a restriction on distribution. Also compare Vasudevan 44:13 (Anil said report should not go outside the group)." }),
    qa(19, 15, "Is asking that a document not be forwarded a restriction on its distribution?", "You can call it what you like. It was a request for a few days.", { objection: obj(MEHRA, "argumentative"), flags: ["evasive"] }),
    qa(20, 9, "Did the defence qualification cell ever receive the Sundaram report?", "Not the report. DQA-T received a summary of the findings in October 2002 in connection with the qualification renewal."),
    qa(20, 20, "That is nineteen months after you received it?", "That sounds right."),
    qa(26, 4, "In Exhibit 1 you also wrote, 'We sold 4.2 million litres of Aqua-Guard last year on the strength of the existing data package.' What was the existing data package?", "The 1993 28-day study, the aquatic toxicity work, and the DTS qualification data."),
    qa(26, 18, "Did the existing data package include any information on persistence or bioaccumulation of the repellent agent?", "The 28-day study had a recovery arm. I would have to look at what it said."),
    qa(31, 7, "Exhibit 2 is your email to Rohit Kapur dated March 19, 2001, subject 'timing of any submission.' Did you write it?", "Yes.", { exhibit: "Prasad-2" }),
    qa(31, 14, "You wrote, 'If a substantial-risk notice on our finishing agent lands at the Park and the GPCB in April, every one of those customers will hear about it.' What customers?", "The defence re-qualification, Konkan Weaves, Saurashtra Fabrics, the two Ludhiana mills. The renewals that were coming up."),
    qa(32, 5, "And you wrote, 'If there is a defensible path that involves doing the bioassay first and reporting when we actually know something, that is the path I want.' Correct?", "Correct.", { flags: ["admission", "key"] }),
    qa(32, 14, "Was that path taken?", "Legal made the reporting decision. I was not part of it.", { flags: ["evasive"] }),
    qa(33, 1, "You were copied on Mr. Kapur's advice of March 19, were you not?", "I was copied.", { objection: obj(MEHRA, "privilege", "The witness may confirm receipt. He may not disclose the content of Mr. Kapur's advice."), flags: ["privilege"] }),
    qa(33, 12, "Did the commercial considerations you described in Exhibit 2 play any role in the decision not to give a Clause 9.4 notice in 2001?", "I cannot speak to what Legal considered. I told them the commercial picture. That was my job.", { objection: obj(MEHRA, "speculation"), flags: ["evasive", "key"] }),
    qa(39, 8, "Exhibit 4, April 11, 2001. 'I will sign the bioassay. I will not sign ₹16.2 crore.' Did you write that?", "Yes.", { exhibit: "Prasad-4" }),
    qa(39, 17, "Was budget a factor in the design of the two-year bioassay?", "Budget was not a factor in the design. The design was Sundaram's recommendation. Cost was a factor in what we did in that fiscal year.", { flags: ["contradiction", "key"], note: "MFC-0041948: 'Three groups, not four, and drop the 12-month interim sacrifice … that takes it to about ₹9.2 crore.' Budget drove design. Vasudevan 49:8 confirms." }),
    qa(40, 6, "Your email says, 'Three groups, not four, and drop the 12-month interim sacrifice. Sundaram told Pankaj on the phone that takes it to about ₹9.2 crore.' Is dropping a dose group a design change?", "It is a design choice within a scientifically valid range. Sundaram agreed three groups gives you a NOAEL.", { objection: obj(MEHRA, "form"), flags: ["evasive"] }),
    qa(40, 18, "Who chose three groups instead of four?", "I approved three. Sundaram said it was acceptable."),
    qa(41, 4, "Did Ms. Vasudevan tell you the reduced design could not characterize the low-dose response?", "She may have. Hema had a lot of views about the design.", { flags: ["evasive"] }),
    qa(47, 2, "Exhibit 3, April 4, 2001, the MSDS. You wrote that you were not going to approve an MSDS that says the product 'accumulates in the body' on the strength of 'one rat study that our own toxicologist says is preliminary.' Which toxicologist?", "Hema Vasudevan.", { exhibit: "Prasad-3" }),
    qa(47, 15, "When did Ms. Vasudevan tell you the study was preliminary?", "At the Friday meeting. She said she had not finished her review of the individual animal data."),
    qa(48, 3, "Did she use the word 'preliminary'?", "I do not remember her exact words. That was the substance."),
    qa(48, 12, "The same email says 'Legal has decided [it] does not need to go to the Park.' As of April 4, 2001, had Legal decided that?", "Manish had told me the March analysis concluded no notice was required at that time. Yes.", { objection: obj(MEHRA, "privilege", "Instruct the witness not to disclose the substance of the legal analysis. He may answer whether a decision had been communicated to him."), flags: ["privilege", "key"] }),
    qa(49, 1, "Who decided to keep Section 12 as 'has not been determined'?", "I did."),
    qa(49, 8, "Did Mr. Hegde participate in that decision?", "Girish was copied. It was my call.", { flags: ["key"] }),
    qa(55, 10, "Exhibit 5 is the 2001–2002 marketing plan. Slide 8 describes MF-3 as a 'different, biodegradable repellent agent.' Who wrote Slide 8?", "Kavita Lal's group, with input from sales.", { exhibit: "Prasad-5" }),
    qa(55, 20, "Exhibit 11 is Ms. Vasudevan's email saying 'Slide 8 is false.' Did you read it?", "Yes.", { exhibit: "Prasad-11" }),
    qa(56, 5, "Was Slide 8 false?", "It was inaccurate as to chemistry. 'Biodegradable' was a term the industry used loosely. We revised it.", { flags: ["admission", "key"] }),
    qa(56, 16, "Exhibit 6 is your reply. You wrote, 'Legal will look at the claims before anything goes to print.' Did the deck go to print?", "A revised version went to the sales force in June. Slides 5 and 8 were changed.", { exhibit: "Prasad-6" }),
    qa(57, 4, "Do you have the revised version?", "I assume it was produced. I have not looked."),
    qa(57, 12, "Was the word 'biodegradable' removed?", "I believe it was changed to 'readily biodegradable hydrocarbon surfactant system.' I would have to see it.", { flags: ["evasive"] }),
    qa(64, 7, "Exhibit 9 is your board pre-read from June 2001. Page 2 says, quote, 'the toxicology profile of MF-3 is well characterized and supports continued sale.' Was that accurate?", "In June 2001, yes. We had the 90-day study, we had commissioned the two-year study, and the plant exposures were well below the NOAEL.", { exhibit: "Prasad-9" }),
    qa(65, 2, "Does the pre-read mention that the material has a half-life in the rat of about 100 days?", "It does not.", { flags: ["admission"] }),
    qa(65, 10, "Does it mention that the recovery animals retained the material?", "No.", { flags: ["admission"] }),
    qa(65, 18, "Exhibit 12, the board minutes. The minutes say 'Mr. Prasad reported that the recent rat study raised no issues requiring regulatory action.' Did you say that?", "The minutes are a summary. I told the board that Legal had reviewed the study and that no notice was required. That is what I understood.", { exhibit: "Prasad-12", flags: ["key"] }),
    qa(72, 14, "Let's go to July 2002. Exhibit 7. 'Do not put this in email. Not the recommendations, not the numbers, not the farm.' Why did you write that?", "Because Girish had sent a groundwater interpretation to a wide distribution before anyone had reviewed it. The numbers were preliminary and the recommendations were Girish's personal views.", { exhibit: "Prasad-7", flags: ["key"] }),
    qa(73, 6, "The email was to you and Mr. Sood. Is that a wide distribution?", "Nandini was on it too. I took her off.", { flags: ["evasive"] }),
    qa(73, 14, "Were the numbers preliminary? The Beacon report was a final laboratory report.", "The interpretation was preliminary.", { flags: ["contradiction"], note: "Position inconsistency: Prasad characterizes 'Do not put this in email' as concern about preliminary numbers; the email itself says nothing goes to the Board 'until Legal has looked at it' (MFC-0052217). Hegde 50:16 corroborates." }),
    qa(74, 2, "You also wrote, 'Nothing goes to the Board or to the Park until Legal has looked at it. That is not a no, it is a not yet.' Correct?", "Correct."),
    qa(74, 10, "How long did 'not yet' last?", "The Park was notified in October."),
    qa(74, 17, "And the Board?", "The formal submission was in November, in response to their request."),
    qa(80, 5, "Was there any business reason to delay notifying Valsara Textile Park Ltd.?", "No business reason. Legal wanted another round of data so we were not reporting a single result.", { objection: obj(MEHRA, "privilege", "The witness may not disclose the reasons given by counsel."), flags: ["privilege", "key"] }),
    qa(88, 12, "Exhibit 8 is your October 2002 response to Col. Wadhwa at DQA-T. Item 2 says Meridian 'provided a summary of the 90-day study to CPCB in June 2001.' Is that accurate?", "Manish told me a summary went to CPCB in response to the voluntary data request. I relied on that.", { exhibit: "Prasad-8" }),
    qa(89, 3, "Did you review the submission to CPCB before you wrote to the defence qualification authority?", "No."),
    qa(89, 10, "Item 3 says, 'Meridian has not given a substantial-risk notice to date.' Was that accurate on October 7, 2002?", "Yes. The notice went in later that month.", { flags: ["admission"] }),
    qa(90, 1, "So when you wrote to the defence qualification authority, you knew a notice was about to be given and did not say so?", "I said we 'may make a submission in connection with data from the two-year study.' That was accurate.", { objection: obj(MEHRA, "argumentative"), flags: ["evasive", "key"] }),
    qa(90, 14, "The 12-month interim showing liver tumors had been in Meridian's hands since September 11. Did you mention the tumors to the defence qualification authority?", "Not in that letter.", { flags: ["admission", "key"] }),
    qa(98, 8, "Exhibit 8 also says the product literature and MSDS were 'revised in August 2001 to reflect the 90-day study.' What was revised?", "Section 11 was revised to say 'eliminated slowly.' The rinse water guidance was added."),
    qa(98, 19, "In April 2001 you struck 'may accumulate' from the same section. Was 'eliminated slowly' a full reflection of the 90-day study?", "It reflected what we knew.", { flags: ["evasive"] }),
    qa(106, 3, "Exhibit 10 is the MF-5 transition timeline from June 2006. Why did Meridian move to a MF-5 repellent agent?", "Regulatory direction from CPCB, customer demand, and the 2005 bioassay result. All three."),
    qa(106, 15, "Was the 2005 bioassay result a reason?", "It was one reason. Yes.", { flags: ["admission"] }),
    qa(114, 9, "Between March 2001 and June 2006, did Meridian ever tell its Aqua-Guard customers that the repellent agent was persistent and bioaccumulative?", "The February 2010 customer letter says that. Before that, the MSDS said 'eliminated slowly.'"),
    qa(115, 1, "So the answer to my question is no?", "Not in those words, no.", { flags: ["admission", "key"] }),
    qa(127, 6, "Did you receive a bonus in 2001?", "Yes.", { objection: obj(MEHRA, "relevance") }),
    qa(127, 12, "Was any part of it tied to Aqua-Guard revenue?", "Business unit performance was one component. Yes."),
    qa(140, 18, "Have you spoken with Mr. Hegde about his testimony?", "No. Counsel told me not to."),
    qa(152, 4, "Mr. Prasad, do you agree that in March 2001 Meridian had information that its repellent agent was toxic to the liver and very persistent, and chose not to tell the Park, the defence qualification authority, or its customers?", "I do not agree with the way you put it. We had a study, we commissioned a bigger study, and Legal made the reporting decision.", { objection: obj(MEHRA, "form", "Compound, argumentative, and mischaracterizes the testimony."), flags: ["key"] }),
    qa(153, 2, "Did you tell the Park?", "No."),
    qa(153, 7, "Did you tell the defence qualification authority?", "Not until 2002."),
    qa(153, 12, "Did you tell your customers?", "Not in 2001.", { flags: ["admission", "key"] }),
    // Examination by defending counsel
    qa(210, 5, "Mr. Prasad, Arjun Mehra. Did Meridian conduct the two-year bioassay?", "Yes. It started in 2001 and finished in 2005. It cost about ₹11 crore in the end.", { objection: obj(KALE, "form", "Leading.") }),
    qa(210, 16, "Did Meridian give a Clause 9.4 notice when the interim results showed tumors?", "Yes, in October 2002. Within about six weeks of receiving the interim."),
    qa(214, 3, "Did any customer ever ask Meridian, before 2002, whether the repellent agent was persistent?", "Sarangpur asked about environmental fate in April 2001. We answered. Nobody else asked.", { objection: obj(KALE, "relevance") }),
    qa(219, 8, "Was the MF-5 transition completed?", "Yes. Aqua-Guard 3 and 6 were discontinued in 2008 and replaced by Aqua-Guard MF-5."),
    qa(227, 1, "Nothing further.", "(Whereupon, at 4:51 p.m., the deposition was concluded.)"),
  ],
};
