import type { Deposition } from "@/lib/types/domain";
import { MATTERS, PEOPLE } from "@/lib/seed/ids";
import { KALE, MEHRA, obj, qa } from "./seed-helpers";

/**
 * Deposition of Girish Hegde, Director of Environmental Health & Safety,
 * Meridian Fine Chemicals Ltd. Vol. I (2001–2003 EHS reporting, Valsara
 * groundwater). Taken by Radhika Kale; defended by Arjun Mehra.
 */
export const HALE_DEPOSITION: Deposition = {
  id: "dep_vls_hale_v1",
  matterId: MATTERS.valsara,
  witnessId: PEOPLE.girishHegde,
  witnessName: "Girish Hegde",
  witnessTitle: "Director, Environmental Health & Safety, Meridian Fine Chemicals Ltd.",
  date: "2026-05-13",
  takenBy: "Radhika Kale (Counsel for the Claimant)",
  defendingBy: "Arjun Mehra (Mehra & Rao Advocates)",
  location: "Kale & Associates, 12 Marine Lines, Mumbai 400020 — Conference Room 3",
  volume: 1,
  pages: 262,
  status: "reviewed",
  exhibits: [
    { id: "Hegde-1", description: "EHS assessment — Sundaram 90-day study (19 Mar 2001)", bates: "MFC-0041912" },
    { id: "Hegde-2", description: "EHS assessment — DRAFT v2 (18 Mar 2001)", bates: "MFC-0041965" },
    { id: "Hegde-3", description: "EHS quarterly report Q3 2001 — Valsara site (15 Nov 2001)", bates: "MFC-0041988" },
    { id: "Hegde-4", description: "Hegde email, 'Valsara site — monitoring well MW-7 results' (8 Jul 2002)", bates: "MFC-0052210" },
    { id: "Hegde-5", description: "Beacon Enviro Services Q2 2002 groundwater results (3 Jul 2002)", bates: "MFC-0052212" },
    { id: "Hegde-6", description: "Prasad reply, 'Do not put this in email' (9 Jul 2002)", bates: "MFC-0052217" },
    { id: "Hegde-7", description: "Letter to Valsara Textile Park Water Works (24 Oct 2002)", bates: "MFC-0052221" },
    { id: "Hegde-8", description: "Response to Sarangpur Processors' Co-operative (24 Apr 2001)", bates: "MFC-0041952" },
    { id: "Hegde-9", description: "Hegde email, 'GPCB — call from Jyoti Rathore' (15 Jul 2002)", bates: "MFC-0052220" },
    { id: "Hegde-10", description: "Operations review — Valsara EHS notes (11 May 2001)", bates: "MFC-0041970" },
    { id: "Hegde-11", description: "Hegde email, 'RE: MW-7 results — actions from 7/9 meeting' (10 Jul 2002)", bates: "MFC-0052219" },
    { id: "Hegde-12", description: "Vasudevan email, 'Sundaram final — 90-day rat study' (14 Mar 2001)", bates: "MFC-0041880" },
  ],
  transcript: [
    qa(6, 12, "Please state and spell your name.", "Girish Anand Hegde. H-E-G-D-E."),
    qa(7, 3, "Mr. Hegde, how long have you been Director of EHS at Meridian?", "Since November 1996. Before that I was EHS manager at the Valsara plant from 1991."),
    qa(7, 18, "What is your training?", "B.Tech. in chemical engineering, 1984. Certified industrial hygienist since 1990. I am not a toxicologist."),
    qa(10, 7, "Who reported to you in 2001?", "The site EHS managers at Valsara and Dahej, the corporate industrial hygienist, and — administratively — Hema Vasudevan and the Product Safety group."),
    qa(10, 20, "And to whom did you report?", "Pankaj Malhotra, Senior Vice President of Operations."),
    qa(15, 4, "Exhibit 12 is Ms. Vasudevan's email of March 14, 2001. You were a recipient. When did you first read it?", "The evening of the 14th, I believe. Or the next morning.", { exhibit: "Hegde-12" }),
    qa(15, 16, "What was your reaction?", "That we had a serious scientific result and needed to handle it carefully."),
    qa(16, 8, "What did 'carefully' mean?", "Understand it before it went to people who would not understand it."),
    qa(21, 2, "Exhibit 2 is a draft of your EHS assessment memo dated March 18. Exhibit 1 is the final dated March 19. Why did you write the memo?", "Pankaj Malhotra asked for an EHS view of what the study meant for the plant and for the product. That was my job.", { exhibit: "Hegde-1" }),
    qa(22, 10, "Paragraph 2 of the final memo says there are, quote, 'no adverse findings at exposures relevant to occupational use of the product.' Who wrote that sentence?", "I did."),
    qa(22, 19, "Did Ms. Vasudevan review the memo before it went out?", "Yes. Hema reviewed the final and did not ask for changes to that paragraph.", { flags: ["contradiction", "key"], note: "Vasudevan testified (Vasudevan 39:15, 40:6) that the sentence was Hegde's framing and that she objected verbally. Testimony-vs-testimony conflict." }),
    qa(23, 8, "Is the sentence accurate?", "As written, yes. Measured plant exposures were 100 to 300 times below the no-effect level. That is what the sentence says."),
    qa(23, 20, "It does not say the study found dose-related liver toxicity, does it?", "Paragraph 1 says the study identifies the liver as the target organ. It is in the memo.", { objection: obj(MEHRA, "argumentative") }),
    qa(25, 1, "Compare Exhibit 2, the draft. The draft paragraph 2 reads: 'Effects observed are consistent with a persistent, bioaccumulative compound and margins for end-users cannot be established on current data.' That sentence is not in the final. Why?", "Because it was not an EHS conclusion. It was a product-safety conclusion, and Hema's group was going to address it in the bioassay proposal.", { exhibit: "Hegde-2", flags: ["key"] }),
    qa(25, 21, "Who asked you to remove it?", "Nobody asked me. I revised my own draft.", { flags: ["evasive"] }),
    qa(26, 9, "Did you discuss the draft with Mr. Prasad between March 18 and March 19?", "I am sure I did. He was the addressee."),
    qa(26, 18, "Did Mr. Prasad express any view about the draft language?", "Anil said the memo should stick to what EHS knew, which was plant exposure. I agreed.", { flags: ["admission", "key"] }),
    qa(33, 5, "Let's go to Valsara. Exhibit 10 is your notes from an operations review in May 2001. You wrote 'Lagoon 2 — south third never lined?' with a question mark. What did you mean?", "The plant's records showed a liner installed in 1989. The site engineer told me the south third of the lagoon had been extended in 1991 and he could not find a liner record for the extension.", { exhibit: "Hegde-10" }),
    qa(34, 2, "What did you do about it?", "I asked Beacon to add a monitoring well downgradient of Lagoon 2. That became MW-7. It was installed in August 2001."),
    qa(34, 15, "What was MW-7 sampled for?", "Initially the standard consent-condition suite. I added MC-8 and adsorbable organic halogens starting with the September 2001 round."),
    qa(38, 9, "Exhibit 3 is your Q3 2001 quarterly report. Section 4 reports MW-7 at 12.0 micrograms per liter MC-8. Is that the first detection of MC-8 in Valsara groundwater?", "In a monitoring well, yes. That was the first round we had analyzed for it.", { exhibit: "Hegde-3", flags: ["admission", "key"] }),
    qa(39, 1, "Who received the Q3 2001 report?", "Pankaj Malhotra, Anil Prasad, Nandini Bose, the plant manager, and the file."),
    qa(39, 12, "Did you tell anyone outside Meridian about the 12 microgram result?", "No. There was no standard and no reporting requirement."),
    qa(46, 7, "When did you first learn of the MW-7 result of 41 micrograms per liter?", "That would have been late August 2002, when Beacon delivered the Q2 report.", { flags: ["contradiction", "key"], note: "Hegde's own email transmitting the 41 µg/L result (MFC-0052210) is dated 8 Jul 2002, and Beacon's report (MFC-0052212) is dated 3 Jul 2002. Date inconsistency — impeach with Exhibits 4 and 5." }),
    qa(46, 18, "Are you sure about late August?", "That is my recollection. It was after the summer shutdown."),
    qa(47, 6, "Exhibit 4 is an email from you to Mr. Prasad and Mr. Sood with the subject 'Valsara site — monitoring well MW-7 results.' What is the date on that email?", "July 8, 2002.", { exhibit: "Hegde-4", flags: ["admission"] }),
    qa(47, 14, "And the first line reads 'Beacon's Q2 results for the Valsara wells are attached.' Does that refresh your recollection as to when you received the results?", "It does. It must have been early July. I was wrong about August.", { flags: ["admission", "key"] }),
    qa(48, 3, "Exhibit 5, the Beacon report, is dated July 3, 2002. So you received it and forwarded it within five days?", "It appears so, yes."),
    qa(49, 10, "In Exhibit 4 you recommended notifying GPCB, quote, 'voluntarily, now.' Was GPCB notified in July 2002?", "No."),
    qa(49, 17, "When was GPCB notified?", "Jyoti Rathore called us on July 15 about something unrelated — a stormwater inspection — and I mentioned we had added MC-8 to our monitoring. The formal letter did not go until later."),
    qa(50, 8, "Exhibit 9 is your email about the Rathore call. It says, quote, 'I did not raise MW-7.' Did I read that correctly?", "Yes.", { exhibit: "Hegde-9", flags: ["admission", "key"] }),
    qa(50, 16, "So on July 15, 2002 you spoke with GPCB and did not mention the 41 microgram result?", "Correct. I had been told nothing goes to the Board until Legal had looked at it.", { flags: ["admission", "key"] }),
    qa(51, 4, "Who told you that?", "Anil Prasad. It is in Exhibit 6.", { exhibit: "Hegde-6" }),
    qa(52, 1, "Exhibit 6 is Mr. Prasad's reply of July 9, 2002. He wrote, 'Do not put this in email. Not the recommendations, not the numbers, not the farm.' What did you understand 'the farm' to mean?", "The Kesar farm. The property between the plant and the Park wellfield. There was a private well on it.", { flags: ["key"] }),
    qa(52, 14, "Was the Kesar well ever sampled?", "In 2003, after the Park sampling. It was 3.1 micrograms per liter.", { flags: ["key"] }),
    qa(56, 9, "What happened at the 2 p.m. meeting on July 9, 2002?", "Anil, Manish, Pankaj, Rohit Kapur and I met. Manish walked through the legal position. The decision was to close Lagoon 2, finish the drain re-route, install the two additional wells, and hold on notification until we had another round of data."),
    qa(57, 3, "Exhibit 11 is your email of July 10 listing actions from the meeting. It does not mention notification. Why not?", "Because the decision on notification was Legal's, and I was told not to put it in email.", { exhibit: "Hegde-11", objection: obj(MEHRA, "privilege", "The witness may describe the business decisions made. He may not describe the legal advice given at the meeting.") , flags: ["privilege", "key"] }),
    qa(61, 4, "When did Meridian first tell Valsara Textile Park Ltd. about MC-8 in groundwater?", "Exhibit 7. My letter of October 24, 2002.", { exhibit: "Hegde-7" }),
    qa(61, 12, "That is 108 days after you recommended notifying the Board 'now.' Correct?", "If that is the arithmetic, yes.", { objection: obj(MEHRA, "argumentative") }),
    qa(62, 2, "Your October letter offers to sample the Park's wells 9 through 12. Does it state the MW-7 concentration?", "It says elevated concentrations were detected in shallow groundwater at the property line. I do not believe it gives the number.", { flags: ["admission"] }),
    qa(62, 15, "Why not?", "Manish drafted the letter. I signed it.", { objection: obj(MEHRA, "privilege") }),
    qa(70, 8, "Let's go back to April 2001 and Exhibit 8, your letter to Mr. Dutta of the Sarangpur Processors' Co-operative. Paragraph 2 says the repellent agent's behavior in soil and water 'has not been fully determined.' As of April 24, 2001, what did you know about its behavior?", "I knew from the 90-day study that it was persistent in the rat. I did not have environmental fate data.", { exhibit: "Hegde-8" }),
    qa(71, 1, "You knew it did not biodegrade?", "Hema believed it did not. There was no study.", { flags: ["evasive"] }),
    qa(71, 9, "Ms. Vasudevan wrote in May 2001, 'The repellent agent does not biodegrade.' Did you disagree with her?", "No.", { flags: ["admission"] }),
    qa(78, 14, "Did you ever recommend that Meridian tell textile processors that the repellent agent was persistent and bioaccumulative?", "I recommended the rinse water-collection guidance, which is in the letter. I did not recommend those words."),
    qa(85, 6, "Did the Valsara plant ever discharge finishing concentrate or wash water to Lagoon 2?", "Tote wash water went to the Building 7 floor drain, which went to Lagoon 2, until the sump was installed in October 2001. Yes."),
    qa(85, 20, "For how long?", "Since Building 7 was built. 1987."),
    qa(91, 3, "Mr. Hegde, did anyone ever instruct you to stop sampling MW-7 for MC-8?", "No. We sampled quarterly through 2011."),
    qa(91, 12, "Did the results ever go below 41?", "They peaked at 66 in 2004 and came down after the lagoon closure. In 2011 MW-7 was about 9."),
    qa(104, 15, "Exhibit 3, Section 3, reports a adsorbable organic halogens of 41 micrograms per liter at Outfall 002 in Q3 2001. Is that the same 41 as MW-7?", "No. Coincidence. Different matrix, different quarter. Outfall 002 is wastewater; MW-7 is groundwater.", { flags: ["key"], note: "the Claimant's expert conflated these two figures in the Patel report. Useful clarification." }),
    qa(112, 8, "Did you keep a personal file on the MW-7 issue?", "I kept a working file at the office. It was collected in 2012 under the hold."),
    qa(121, 2, "Did you attend the June 20, 2001 board meeting?", "No. Anil presented."),
    qa(121, 10, "Were you asked to prepare anything for it?", "A one-page summary of the Valsara monitoring plan. It did not mention the Sundaram study; that was Anil's section."),
    qa(134, 17, "Have you had any discussions with Ms. Vasudevan about the substance of her testimony?", "No. We were both told not to."),
    qa(142, 6, "Who was responsible for the MSDS language on the repellent agent in 2001?", "Product Stewardship drafted it; I signed off on the MSDS language with Hema, and Anil approved the final.", { flags: ["contradiction"], note: "Vasudevan testified (156:20) that Hegde had no role in the MSDS language." }),
    qa(158, 3, "Mr. Hegde, do you agree that as of July 2002 Meridian knew MC-8 from its Valsara plant was migrating off-site toward the Park's drinking-water supply?", "We knew it was in MW-8 at the property line and that the wellfield was 2.3 km away in the direction of flow. Whether it would reach the wellfield was uncertain. Beacon said uncertain.", { objection: obj(MEHRA, "form", "Mischaracterizes the document."), flags: ["admission", "key"] }),
    qa(159, 1, "You wrote, in Exhibit 4, 'we have an off-site migration of a compound we know is persistent and bioaccumulative, toward the Park's drinking-water supply.' Those are your words?", "Those are my words.", { flags: ["admission", "key"] }),
    qa(176, 9, "Did you ever consider resigning over the notification issue?", "No.", { objection: obj(MEHRA, "relevance") }),
    qa(190, 14, "In 2017 you distributed a Q3 EHS report that references July and August 2017 interim groundwater results. Where are those interims?", "I do not know. They should be in the Beacon portal. I have been told they could not be located."),
    qa(191, 5, "Did you delete them?", "No.", { objection: obj(MEHRA, "argumentative") }),
    qa(208, 2, "Is there anything in your testimony today you would like to correct?", "The date I gave for the 41 microgram result. It was July 2002, not August.", { flags: ["admission"] }),
    // Examination by defending counsel
    qa(240, 6, "Mr. Hegde, Arjun Mehra. Between July 2002 and October 2002, what did Meridian do at the Valsara site?", "We closed Lagoon 2, we finished the Building 7 drain re-route, and we installed MW-9 and MW-10 between the property line and the wellfield.", { objection: obj(KALE, "form", "Leading.") }),
    qa(241, 1, "Was there a legal requirement to report the MW-7 result to GPCB in July 2002?", "Not that I was aware of. There was no MC-8 standard.", { objection: obj(KALE, "foundation", "The witness has testified he is not a lawyer.") }),
    qa(244, 12, "Did Meridian ever refuse a request from GPCB for groundwater data?", "No. We provided everything they asked for, starting with the November 2002 request."),
    qa(252, 8, "Did the Park's wells 9 through 12 ever show MC-8 above CPCB's current guidance value during the period you were sampling?", "The highest was 3.6 nanograms per litre in Well 11 in 2006. The current guidance value is 100 nanograms per litre combined. So no.", { objection: obj(KALE, "relevance", "The guidance value did not exist at the time.") }),
    qa(258, 3, "Thank you. Nothing further.", "(Whereupon, the deposition was adjourned at 6:05 p.m., to be continued as Volume II.)"),
  ],
};
