import type { ColumnKind, ReviewColumn, ReviewIssue, ReviewPlaybook } from "../review-types";

/**
 * Review playbooks for Indian practice areas. Each playbook is a starting point a practising litigator would recognise:
 * the statutes it is built around (short titles with years; the 2023 criminal codes with their predecessors), the
 * document types the classifier picks from, the issues a document is screened against, the columns pulled from every
 * file (each with a precise instruction) and the questions run across the whole set for the report.
 *
 * Playbook text is guidance for the reviewer model and the reviewer; nothing here is treated as evidence. Every value the
 * model returns still has to carry a quote that is checked against the file text in code.
 */

const col = (id: string, label: string, kind: ColumnKind, prompt: string, choices?: string[]): ReviewColumn =>
  choices ? { id, label, kind, prompt, choices } : { id, label, kind, prompt };

const iss = (id: string, label: string, description: string): ReviewIssue => ({ id, label, description });

const GENERAL: ReviewPlaybook = {
  id: "general",
  area: "general",
  name: "General litigation review",
  description: "A first pass over any bundle of pleadings, correspondence and records: who, when, how much, what was admitted and whether limitation or notice is in play. Use it when no practice-area playbook fits.",
  statutes: [
    "Code of Civil Procedure, 1908",
    "Bharatiya Sakshya Adhiniyam, 2023 (formerly Indian Evidence Act, 1872)",
    "Limitation Act, 1963",
    "Indian Contract Act, 1872",
    "Specific Relief Act, 1963",
    "Bharatiya Nagarik Suraksha Sanhita, 2023 (formerly Code of Criminal Procedure, 1973)",
  ],
  docTypes: [
    "Plaint", "Written statement", "Affidavit", "Court order / judgment", "Legal notice", "Reply to legal notice", "Agreement / contract",
    "Letter / correspondence", "Email", "Invoice / bill", "Receipt", "Bank statement", "Vakalatnama", "Power of attorney", "Minutes of meeting",
    "Internal note / memo", "Report", "Certificate under s.63 BSA (s.65B Evidence Act)",
  ],
  issues: [
    iss("liability", "Liability", "The document states or bears on who is responsible for the breach, wrong or loss in dispute (conduct, obligations, breach, fault)."),
    iss("limitation", "Limitation", "The document fixes or moves a limitation date: when the cause of action arose, a written acknowledgement of liability (s.18 Limitation Act), a part-payment (s.19), or a fresh promise."),
    iss("quantum", "Damages and quantum", "The document states amounts claimed, paid, due, or the basis for calculating loss, interest or costs."),
    iss("admissions", "Admissions", "A party states something against its own interest (admits a fact, liability, receipt, delay or default)."),
    iss("notice_service", "Notice and service", "The document concerns issuing, serving, receiving or refusing a notice, summons or demand, or the dates of service."),
    iss("electronic_evidence", "Electronic evidence", "The document is or relies on an electronic record (email, WhatsApp, CCTV, printout) whose admissibility needs a certificate under s.63 BSA 2023 (s.65B Evidence Act)."),
  ],
  columns: [
    col("doc_date", "Document date", "date", "The date the document bears (date of execution, letter date or email sent date), exactly as written."),
    col("author", "Author / sender", "party", "The person or organisation that wrote, signed or sent the document."),
    col("recipients", "Recipients", "list", "Every person or organisation the document is addressed or copied to."),
    col("parties_named", "Parties named", "list", "Each party to the dispute named in the document, with their role if stated (e.g. \"Acme Traders Pvt. Ltd. — buyer\")."),
    col("amounts", "Amounts", "list", "Every sum of money stated, with what it is for (e.g. \"Rs. 5,00,000 — fee due on invoice\")."),
    col("obligations", "Obligations", "text", "The main obligations or undertakings the document places on any party, briefly."),
    col("deadline", "Deadline / due date", "date", "Any date by which something must be done (payment, reply, compliance), exactly as written."),
    col("admissions", "Admissions", "text", "Any statement by a party against its own interest, in that party's words."),
    col("relief_claimed", "Relief claimed", "text", "The relief, payment or action demanded or prayed for in the document."),
    col("cause_of_action_date", "Cause of action date", "date", "The date on which the document says the cause of action arose, or the breach/default occurred."),
    col("signed", "Signed", "yes_no", "Whether the document is signed or executed by the party it comes from (Yes / No as visible in the text)."),
    col("certificate_63", "s.63 BSA / s.65B certificate", "yes_no", "Whether the document is or attaches a certificate under s.63 Bharatiya Sakshya Adhiniyam (or s.65B Indian Evidence Act) for an electronic record."),
  ],
  questions: [
    "Set out the chronology of the dispute from the documents, with dates.",
    "What does each party claim and what relief is sought?",
    "Which documents contain admissions by either party, and what was admitted?",
    "When did the cause of action arise, and is there any written acknowledgement or part-payment that extends limitation?",
    "What notices were issued, when were they served, and how did the other side respond?",
    "What amounts are claimed or shown as due, and how are they computed?",
    "Which electronic records are relied on, and is a certificate under s.63 BSA (s.65B Evidence Act) on record for them?",
  ],
};

const COMMERCIAL: ReviewPlaybook = {
  id: "commercial-arbitration",
  area: "commercial-arbitration",
  name: "Commercial dispute and arbitration",
  description: "Contract disputes heading to arbitration or the Commercial Court: the arbitration clause, seat, notices, breach, termination and the money claimed. Use it for supply, services, construction, distribution and JV disputes.",
  statutes: [
    "Arbitration and Conciliation Act, 1996",
    "Commercial Courts Act, 2015",
    "Indian Contract Act, 1872",
    "Specific Relief Act, 1963",
    "Limitation Act, 1963",
    "Indian Stamp Act, 1899",
    "Code of Civil Procedure, 1908",
  ],
  docTypes: [
    "Agreement / contract", "Purchase order", "Work order", "Invoice", "Delivery challan", "Bank guarantee", "Notice invoking arbitration (s.21)",
    "Reply to notice", "Termination notice", "Statement of claim", "Statement of defence", "Counter-claim", "Petition under s.9", "Petition under s.11",
    "Petition under s.34", "Interim order (s.9 / s.17)", "Arbitral award", "Pre-institution mediation report (s.12A)", "Minutes of meeting",
    "Email / correspondence", "Board resolution",
  ],
  issues: [
    iss("arbitration_agreement", "Arbitration agreement and scope", "The document contains or refers to an arbitration clause, its scope, the seat or venue, the appointment procedure or the rules, or a challenge to them."),
    iss("breach", "Breach", "The document evidences performance, non-performance, delay or defective performance of contractual obligations by either party."),
    iss("termination", "Termination", "The document concerns termination of the contract: grounds, notice and cure periods, the termination itself or its validity."),
    iss("damages", "Damages and liquidated damages", "The document states loss, liquidated damages, penalties, interest or the basis for compensation (ss.73-74 Indian Contract Act)."),
    iss("limitation", "Limitation", "The document bears on limitation: date of breach or invoice, notice under s.21 A&C Act (commencement of arbitration), acknowledgements or part-payments."),
    iss("bank_guarantee", "Bank guarantee", "The document concerns a bank guarantee: its terms, invocation, encashment or an injunction against it."),
    iss("pre_institution", "Pre-institution mediation", "The document shows whether pre-institution mediation under s.12A Commercial Courts Act was attempted or urgent interim relief was sought."),
  ],
  columns: [
    col("contract_date", "Contract date", "date", "The date of execution of the contract or purchase order, exactly as written."),
    col("contract_parties", "Contract parties", "list", "The parties to the contract with their roles (e.g. \"XYZ Infra Ltd. — contractor\")."),
    col("arbitration_clause", "Arbitration clause", "yes_no", "Whether the document contains an arbitration clause or agreement to arbitrate."),
    col("seat", "Seat", "text", "The seat (juridical place) of arbitration as stated in the clause; note if only a \"venue\" is named."),
    col("venue", "Venue", "text", "The venue or place of hearings named in the clause, if different from the seat."),
    col("institution_rules", "Institution / rules", "choice", "The arbitral institution or rules named in the clause.", ["Ad hoc", "MCIA", "ICA", "DIAC", "ICC", "SIAC", "LCIA", "Other", "Not stated"]),
    col("appointment", "Appointment procedure", "text", "How the tribunal is to be constituted: number of arbitrators and who appoints them (flag any unilateral appointment by one party)."),
    col("governing_law", "Governing law", "text", "The governing law of the contract as stated."),
    col("jurisdiction_clause", "Jurisdiction clause", "text", "Any exclusive jurisdiction clause naming courts, as written."),
    col("notice_s21_date", "s.21 notice date", "date", "The date of the notice invoking arbitration under s.21 A&C Act, or the date it was received."),
    col("claim_amount", "Amount claimed", "amount", "The principal amount claimed or demanded, with currency, as written."),
    col("liquidated_damages", "Liquidated damages", "text", "The liquidated damages or penalty clause: rate, cap and trigger."),
    col("limitation_of_liability", "Limitation of liability", "text", "Any cap or exclusion of liability (e.g. consequential loss excluded, cap at contract value)."),
    col("payment_terms", "Payment terms", "text", "Payment terms: milestones, credit period, interest on delayed payment."),
    col("termination_date", "Termination date", "date", "The date on which the contract was terminated or termination took effect."),
    col("termination_ground", "Termination ground", "text", "The ground stated for termination and the clause relied on, and any cure notice given."),
    col("stamp_duty", "Stamp duty", "text", "Stamp duty paid on the instrument as shown (amount, e-stamp certificate number), or any statement that it is unstamped."),
    col("mediation_s12a", "s.12A mediation", "yes_no", "Whether the document records pre-institution mediation under s.12A Commercial Courts Act (or its non-starter report)."),
  ],
  questions: [
    "What is the arbitration clause, what seat and rules does it name, and how is the tribunal to be appointed?",
    "Set out the chronology of performance, breach and termination with dates.",
    "What notices were exchanged (cure notices, termination, s.21 notice) and when?",
    "What amounts are claimed by each side, under which heads, and on what basis?",
    "Is there a liquidated damages or limitation of liability clause, and how does it apply to the claims?",
    "When did the claims arise, and is any claim arguably barred by limitation?",
    "What do the documents show about invocation of any bank guarantee?",
    "Was pre-institution mediation under s.12A Commercial Courts Act attempted?",
  ],
};

const INSOLVENCY: ReviewPlaybook = {
  id: "insolvency-banking",
  area: "insolvency-banking",
  name: "Insolvency, banking and recovery",
  description: "Debt, default and security papers for IBC applications, SARFAESI actions, DRT recovery and cheque bounce cases. Use it to establish the debt, the date of default, limitation and procedural compliance.",
  statutes: [
    "Insolvency and Bankruptcy Code, 2016",
    "Insolvency and Bankruptcy Board of India (Insolvency Resolution Process for Corporate Persons) Regulations, 2016",
    "Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act, 2002",
    "Recovery of Debts and Bankruptcy Act, 1993",
    "Negotiable Instruments Act, 1881 (s.138)",
    "Limitation Act, 1963 (ss.18-19)",
    "Bankers' Books Evidence Act, 1891",
  ],
  docTypes: [
    "Sanction letter", "Loan / facility agreement", "Deed of hypothecation", "Memorandum of deposit of title deeds", "Guarantee deed",
    "Statement of account", "Certificate under Bankers' Books Evidence Act", "Balance confirmation / acknowledgement of debt", "NPA classification letter",
    "Demand notice u/s 13(2) SARFAESI", "Reply / objection u/s 13(3A)", "Possession notice u/s 13(4)", "Demand notice u/s 8 IBC (Form 3 / Form 4)",
    "Application u/s 7 IBC (Form 1)", "Application u/s 9 IBC (Form 5)", "Record of default (information utility)", "Proof of claim (Form B / C / CA)",
    "Cheque", "Cheque return memo", "Legal notice u/s 138 NI Act", "One-time settlement letter", "Resolution plan", "CoC minutes",
  ],
  issues: [
    iss("debt_default", "Debt and default", "The document establishes the existence of a financial or operational debt, the amount due, or the date and fact of default."),
    iss("limitation_ack", "Limitation and acknowledgement", "The document bears on limitation: date of default or NPA, a signed acknowledgement of debt (s.18 Limitation Act, including balance-sheet entries), part-payment (s.19) or restructuring."),
    iss("pre_existing_dispute", "Pre-existing dispute", "For operational debts: the document shows a dispute about quality, quantity or amount raised before the s.8 IBC demand notice."),
    iss("security", "Security creation and perfection", "The document creates, describes or registers security (hypothecation, mortgage, pledge, guarantee), including CERSAI or ROC charge registration."),
    iss("sarfaesi_compliance", "SARFAESI compliance", "The document bears on SARFAESI procedure: s.13(2) notice and 60-day period, reply to objections under s.13(3A), possession under s.13(4), sale notices."),
    iss("ni_138", "Cheque dishonour (s.138 NI Act)", "The document bears on a s.138 NI Act case: the cheque, presentation, return memo, statutory notice within 30 days, the 15-day payment window, or the legally enforceable debt."),
    iss("guarantor", "Guarantor liability", "The document concerns a guarantee or a guarantor's liability, invocation or discharge."),
    iss("settlement", "Settlement and restructuring", "The document concerns a one-time settlement, restructuring, moratorium or resolution plan."),
  ],
  columns: [
    col("borrower", "Borrower / corporate debtor", "party", "The borrower, drawer or corporate debtor named in the document."),
    col("creditor", "Lender / creditor", "party", "The lender, payee, financial or operational creditor named in the document."),
    col("guarantors", "Guarantors", "list", "Every guarantor named, personal or corporate."),
    col("facility_amount", "Facility / debt amount", "amount", "The sanctioned facility or principal debt, as written."),
    col("sanction_date", "Sanction / agreement date", "date", "The date of sanction or of the loan or supply agreement."),
    col("date_of_default", "Date of default", "date", "The date of default stated in the document (or the date payment fell due and was not made)."),
    col("npa_date", "NPA date", "date", "The date the account was classified as a non-performing asset, if stated."),
    col("outstanding_amount", "Amount outstanding", "amount", "The amount claimed as outstanding, with the date it is computed to."),
    col("interest_terms", "Interest terms", "text", "The rate of interest and any penal or default interest."),
    col("security", "Security", "list", "Each security interest: the asset and the form (hypothecation, equitable mortgage, pledge)."),
    col("charge_registration", "Charge registered (CERSAI / ROC)", "yes_no", "Whether the document records registration of the charge with CERSAI or the Registrar of Companies."),
    col("acknowledgement", "Acknowledgement of debt", "text", "Any written acknowledgement of the debt by the debtor, with its date (balance confirmation, letter, balance-sheet note)."),
    col("demand_notice_date", "Demand notice date", "date", "The date of a demand notice (s.13(2) SARFAESI, s.8 IBC, or s.138 NI Act notice)."),
    col("notice_service_date", "Notice served on", "date", "The date the demand or statutory notice was received or served, as stated."),
    col("cheque_details", "Cheque details", "text", "Cheque number, date, amount and drawee bank."),
    col("dishonour_reason", "Dishonour reason and date", "text", "The reason for dishonour on the return memo (e.g. \"funds insufficient\") and the memo date."),
    col("dispute_raised", "Dispute raised", "text", "Any dispute about the debt raised by the debtor, with the date it was raised."),
    col("settlement_terms", "OTS / settlement terms", "text", "Terms of any one-time settlement or restructuring offered or accepted."),
  ],
  questions: [
    "What is the debt, who owes it, and what amount is outstanding as of which date?",
    "What is the date of default, and what document proves it?",
    "Is the claim within limitation? List every acknowledgement of debt or part-payment with its date.",
    "Before the demand notice, did the debtor raise any dispute about the debt? Quote it.",
    "What security was created and was it registered with CERSAI or the ROC?",
    "Was the SARFAESI procedure followed (s.13(2) notice, 60 days, reply to objections, s.13(4) possession)?",
    "For dishonoured cheques: dates of the cheque, presentation, return memo, notice, its service and the complaint.",
    "What settlement or restructuring proposals were made, and what happened to them?",
  ],
};

const REAL_ESTATE: ReviewPlaybook = {
  id: "real-estate",
  area: "real-estate",
  name: "Real estate, land and RERA",
  description: "Title, registration, possession and builder disputes: traces the chain of title, stamping and registration, encumbrances, approvals and delay in possession. Use it for title suits, specific performance and RERA complaints.",
  statutes: [
    "Transfer of Property Act, 1882",
    "Registration Act, 1908",
    "Indian Stamp Act, 1899 (and the State stamp Acts)",
    "Real Estate (Regulation and Development) Act, 2016",
    "Specific Relief Act, 1963",
    "Limitation Act, 1963",
    "Consumer Protection Act, 2019",
    "State land revenue codes (mutation and record of rights)",
  ],
  docTypes: [
    "Sale deed", "Agreement for sale", "Allotment letter", "Builder-buyer agreement", "Gift deed", "Will", "Partition deed", "Release deed",
    "Lease deed", "Leave and licence agreement", "General power of attorney", "Encumbrance certificate", "Khata / mutation extract",
    "Record of rights (7/12 / jamabandi / RoR)", "Property tax receipt", "Approved building plan", "Commencement certificate",
    "Occupancy / completion certificate", "RERA registration certificate", "Possession letter", "Demand letter from builder", "Payment receipt",
    "Title search report", "Legal notice",
  ],
  issues: [
    iss("title_chain", "Title and chain of title", "The document is a link in the chain of title or shows how the executant acquired the property; or it reveals a gap, a competing claim or a defect in title."),
    iss("registration_stamp", "Registration and stamping", "The document's registration (s.17 Registration Act; effect of non-registration under s.49) or the sufficiency of stamp duty is in question or recorded."),
    iss("encumbrances", "Encumbrances", "The document shows a mortgage, charge, lien, lease, attachment, litigation or other encumbrance on the property."),
    iss("possession_delay", "Possession and delay", "The document concerns the promised or actual date of possession, delay, refund or interest for delay (s.18 RERA)."),
    iss("approvals", "Statutory approvals", "The document concerns sanctioned plans, commencement or occupancy/completion certificates, conversion or other approvals, or deviations from them."),
    iss("specific_performance", "Specific performance", "The document bears on readiness and willingness, payment of consideration, or time being of the essence in an agreement for sale."),
    iss("description_mismatch", "Property description", "The document's description of the property (survey number, area, boundaries) differs from other documents."),
    iss("gpa_transfer", "GPA / SA-will transfers", "The document is or relies on a general power of attorney, agreement to sell or will used as a mode of transfer instead of a registered conveyance."),
  ],
  columns: [
    col("executant", "Executant / vendor", "party", "The person executing or transferring under the document (vendor, donor, lessor, promoter)."),
    col("claimant", "Purchaser / transferee", "party", "The person taking under the document (purchaser, donee, lessee, allottee)."),
    col("document_date", "Execution date", "date", "The date the document was executed, as written."),
    col("registration_details", "Registration details", "text", "Registration particulars: document number, book, Sub-Registrar office and date of registration."),
    col("stamp_duty", "Stamp duty paid", "amount", "Stamp duty paid on the document, as written."),
    col("consideration", "Consideration", "amount", "The sale price, premium or consideration stated."),
    col("amount_paid", "Amount paid", "amount", "The amount paid so far (advance, instalments) as stated or receipted."),
    col("property_description", "Property description", "text", "The property: survey / khasra / plot / flat number, area, village or locality, and taluka/district."),
    col("boundaries", "Boundaries", "text", "The boundaries (North, South, East, West) as written."),
    col("title_source", "Prior title", "text", "How the executant acquired title (earlier deed, inheritance, partition), with the document reference."),
    col("encumbrances", "Encumbrances", "list", "Every encumbrance, mortgage, charge, lease or litigation shown on the property."),
    col("possession_date", "Possession date", "date", "The date possession was promised or handed over (say which)."),
    col("possession_status", "Possession", "text", "Who is stated to be in possession, and in what capacity."),
    col("rera_registration", "RERA registration no.", "text", "The project's RERA registration number, as written."),
    col("approvals", "Approvals", "list", "Sanctions and certificates referred to (building plan, CC, OC/CC, NA conversion), with numbers and dates."),
    col("mutation", "Mutation done", "yes_no", "Whether the document records mutation or khata transfer in the purchaser's name."),
    col("poa_involved", "Power of attorney used", "yes_no", "Whether the document was executed through a power of attorney holder."),
  ],
  questions: [
    "Trace the chain of title to the property from the documents, with each deed's date and registration details.",
    "Which documents in the chain are unregistered or insufficiently stamped?",
    "What encumbrances, mortgages, attachments or litigation affect the property?",
    "Do the property descriptions (survey numbers, area, boundaries) match across documents? List mismatches.",
    "What was the promised possession date, when (if ever) was possession given, and what delay is shown?",
    "What has been paid against the consideration, with dates and receipts?",
    "Are occupancy/completion certificates and sanctioned plans on record for the project?",
    "Is any transfer made only by GPA, agreement to sell or will rather than a registered conveyance?",
  ],
};

const EMPLOYMENT: ReviewPlaybook = {
  id: "employment",
  area: "employment",
  name: "Employment and labour",
  description: "Termination, wage, gratuity and POSH disputes: service record, the termination and its procedure, dues, and internal committee proceedings. Covers the pre-Code statutes and the four Labour Codes; confirm which regime governs the cause-of-action date.",
  statutes: [
    "Industrial Disputes Act, 1947",
    "Industrial Relations Code, 2020",
    "Code on Wages, 2019",
    "Code on Social Security, 2020",
    "Occupational Safety, Health and Working Conditions Code, 2020",
    "Payment of Gratuity Act, 1972",
    "Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013",
    "Industrial Employment (Standing Orders) Act, 1946",
    "Employees' Provident Funds and Miscellaneous Provisions Act, 1952",
    "Indian Contract Act, 1872 (s.27)",
  ],
  docTypes: [
    "Appointment letter", "Employment agreement", "Confirmation letter", "Increment / promotion letter", "Salary slip", "Form 16",
    "Attendance / leave record", "HR policy / standing orders", "Show cause notice", "Charge sheet (departmental)", "Enquiry notice",
    "Enquiry proceedings", "Enquiry report", "Termination / dismissal letter", "Resignation letter", "Relieving / experience letter",
    "Full and final settlement", "Gratuity claim / notice", "PF / ESI record", "POSH complaint", "Internal Committee report",
    "Conciliation failure report", "Union demand notice", "Email / correspondence",
  ],
  issues: [
    iss("workman_status", "Workman status", "The document shows the employee's actual duties, supervisory or managerial powers, or wages, bearing on whether they are a \"workman\" (s.2(s) ID Act / IR Code)."),
    iss("termination_legality", "Legality of termination", "The document bears on the termination: its form, stated reasons, notice or pay in lieu, retrenchment compensation and conditions (s.25F ID Act), or stigma."),
    iss("enquiry_fairness", "Domestic enquiry and natural justice", "The document concerns the charge sheet, enquiry, opportunity to defend, supply of documents, findings or penalty."),
    iss("dues", "Wages, gratuity and dues", "The document states salary, unpaid wages, bonus, leave encashment, gratuity (continuous service, last drawn wages) or full-and-final dues."),
    iss("posh", "Sexual harassment (POSH)", "The document concerns a complaint of sexual harassment, the Internal Committee's constitution, inquiry, timelines or recommendations."),
    iss("restrictive_covenants", "Restrictive covenants", "The document contains non-compete, non-solicit, confidentiality or bond / training-cost clauses."),
    iss("victimisation", "Victimisation and discrimination", "The document suggests the action was retaliatory, discriminatory, or connected with union activity or a complaint."),
  ],
  columns: [
    col("employee", "Employee", "party", "The employee or workman the document concerns."),
    col("employer", "Employer", "party", "The employing establishment or company."),
    col("designation", "Designation and duties", "text", "The designation and the duties actually described (note any power to hire, sanction leave or supervise)."),
    col("date_of_joining", "Date of joining", "date", "The date of joining service, as written."),
    col("date_of_termination", "Date of separation", "date", "The date of termination, resignation, dismissal or retrenchment."),
    col("mode_of_separation", "Mode of separation", "choice", "How employment ended, as the document records it.", ["Resignation", "Termination simpliciter", "Dismissal after enquiry", "Retrenchment", "Superannuation", "Abandonment / deemed resignation", "Not stated"]),
    col("reasons_stated", "Reasons stated", "text", "The reasons given for the action (misconduct alleged, performance, restructuring)."),
    col("last_drawn_wages", "Last drawn wages", "amount", "Last drawn monthly wages or CTC, with the components if given (basic, DA)."),
    col("notice_or_pay", "Notice / pay in lieu", "text", "The notice period given, or pay in lieu of notice paid."),
    col("retrenchment_compensation", "Retrenchment compensation", "amount", "Retrenchment or severance compensation paid or offered."),
    col("enquiry_held", "Enquiry held", "yes_no", "Whether a domestic enquiry was held before the penalty."),
    col("gratuity", "Gratuity", "amount", "Gratuity claimed, computed or paid."),
    col("pending_dues", "Dues claimed", "list", "Each unpaid amount claimed (wages, bonus, leave encashment, reimbursement) with period."),
    col("posh_complaint", "POSH complaint", "text", "Date of the complaint, the Internal Committee, inquiry dates and outcome."),
    col("non_compete", "Restrictive covenant", "text", "Any non-compete, non-solicit or bond clause, with its duration and scope."),
  ],
  questions: [
    "Set out the employee's service history: joining, confirmations, promotions, wages and separation, with dates.",
    "What duties did the employee actually perform, and do the documents suggest supervisory or managerial capacity?",
    "How did employment end, what reasons were given, and was notice or pay in lieu given?",
    "Was a domestic enquiry held? Was the employee given the charge sheet, documents and an opportunity to defend?",
    "What wages, gratuity and other dues are claimed or unpaid?",
    "If there was a POSH complaint, was the Internal Committee properly constituted and were statutory timelines followed?",
    "What restrictive covenants does the employee's contract contain?",
  ],
};

const CRIMINAL: ReviewPlaybook = {
  id: "criminal",
  area: "criminal",
  name: "Criminal trial and bail",
  description: "Police papers and trial record for defence or prosecution: FIR, statements, seizures, medical and forensic evidence, and procedural compliance. Built on the 2023 codes with their IPC/CrPC/Evidence Act predecessors for older offences.",
  statutes: [
    "Bharatiya Nyaya Sanhita, 2023 (formerly Indian Penal Code, 1860)",
    "Bharatiya Nagarik Suraksha Sanhita, 2023 (formerly Code of Criminal Procedure, 1973)",
    "Bharatiya Sakshya Adhiniyam, 2023 (formerly Indian Evidence Act, 1872)",
    "Narcotic Drugs and Psychotropic Substances Act, 1985",
    "Protection of Children from Sexual Offences Act, 2012",
    "Prevention of Corruption Act, 1988",
    "Prevention of Money-laundering Act, 2002",
  ],
  docTypes: [
    "FIR", "Private complaint", "Statement u/s 180 BNSS (s.161 CrPC)", "Statement u/s 183 BNSS (s.164 CrPC)", "Arrest memo",
    "Notice u/s 35 BNSS (s.41A CrPC)", "Seizure memo / panchnama", "Recovery memo", "Site plan", "Inquest report", "Post-mortem report",
    "Medico-legal certificate (MLC)", "FSL / forensic report", "Call detail records", "Certificate under s.63 BSA (s.65B Evidence Act)",
    "Chargesheet / final report (s.193 BNSS / s.173 CrPC)", "Supplementary chargesheet", "Remand order", "Bail application", "Bail order",
    "Charge framed", "Witness deposition", "Judgment",
  ],
  issues: [
    iss("fir_delay", "Delay in FIR", "The document shows the time of the incident and of the report, or explains (or fails to explain) a delay in lodging the FIR."),
    iss("ingredients", "Ingredients of the offence", "The document bears on an ingredient of an offence charged (act, intention, knowledge, dishonesty, consent, age)."),
    iss("identification", "Identity of the accused", "The document concerns naming or identification of the accused (named in FIR, TIP, dock identification, CCTV)."),
    iss("seizure_custody", "Seizure and chain of custody", "The document concerns search, seizure, sealing, recovery, independent witnesses, malkhana entries or dispatch to the FSL."),
    iss("procedure_arrest", "Arrest and procedural compliance", "The document bears on arrest (grounds communicated, intimation, production within 24 hours), notice under s.35 BNSS (s.41A CrPC), or remand."),
    iss("witness_contradictions", "Contradictions and improvements", "The document contains a witness's account that may contradict or improve on that witness's or another witness's earlier statement."),
    iss("medical_forensic", "Medical and forensic evidence", "The document records injuries, cause and time of death, or forensic findings, which may support or contradict the prosecution version."),
    iss("default_bail", "Custody period and default bail", "The document shows the date of arrest, remand periods or chargesheet filing date relevant to default bail (s.187 BNSS / s.167(2) CrPC)."),
  ],
  columns: [
    col("fir_number", "FIR no. and police station", "text", "FIR number, year, police station and district."),
    col("fir_date", "FIR date and time", "date", "The date (and time if given) the FIR was registered."),
    col("incident_date", "Incident date and time", "date", "The date (and time if given) of the alleged occurrence."),
    col("sections_invoked", "Sections invoked", "list", "Every penal provision invoked, as written (e.g. \"s.318(4) BNS\", \"s.420 IPC\")."),
    col("complainant", "Complainant / informant", "party", "The complainant or informant."),
    col("accused", "Accused", "list", "Every accused person named, with any alias or role attributed."),
    col("witnesses", "Witnesses", "list", "Witnesses named in the document and whether they claim to be eyewitnesses."),
    col("place_of_occurrence", "Place of occurrence", "text", "The place of the incident as described."),
    col("delay_explained", "Delay explanation", "text", "Any explanation given for delay in reporting."),
    col("weapon_or_property", "Weapon / property", "text", "The weapon, contraband or property involved."),
    col("recovery_details", "Recovery and seizure", "text", "What was recovered or seized, from where, when, in whose presence, and how it was sealed."),
    col("arrest_date", "Arrest date", "date", "The date (and time if given) of arrest."),
    col("medical_findings", "Medical findings", "text", "Injuries, cause of death and estimated time of death as recorded."),
    col("forensic_findings", "Forensic findings", "text", "The FSL or forensic conclusion and the exhibits examined."),
    col("chargesheet_date", "Chargesheet date", "date", "The date the chargesheet / final report was filed."),
    col("independent_witnesses", "Independent witnesses", "yes_no", "Whether independent (non-police) witnesses attested the search, seizure or recovery."),
    col("electronic_evidence", "Electronic evidence", "text", "Electronic records relied on (CCTV, CDR, chats) and whether a s.63 BSA / s.65B certificate accompanies them."),
  ],
  questions: [
    "Set out the prosecution's version from the FIR and chargesheet, with dates, times and places.",
    "When did the incident occur, when was the FIR lodged, and is any delay explained?",
    "List each witness's statements and point out contradictions or improvements between them.",
    "How was each recovery or seizure made, and were independent witnesses present?",
    "Do the medical and forensic findings support or contradict the prosecution version?",
    "Was the arrest procedure followed (grounds of arrest, intimation, production within 24 hours)?",
    "What is the date of arrest and of the chargesheet, and does any default-bail period arise?",
    "What electronic evidence is relied on, and is a certificate under s.63 BSA (s.65B Evidence Act) on record?",
  ],
};

const FAMILY: ReviewPlaybook = {
  id: "family",
  area: "family",
  name: "Family and matrimonial",
  description: "Divorce, maintenance, domestic violence and custody records: marriage, separation, allegations, incomes and assets, children and earlier proceedings. Use it to prepare pleadings and the affidavit of assets and liabilities.",
  statutes: [
    "Hindu Marriage Act, 1955",
    "Special Marriage Act, 1954",
    "Protection of Women from Domestic Violence Act, 2005",
    "Bharatiya Nagarik Suraksha Sanhita, 2023, s.144 (formerly Code of Criminal Procedure, 1973, s.125)",
    "Hindu Adoptions and Maintenance Act, 1956",
    "Guardians and Wards Act, 1890",
    "Hindu Minority and Guardianship Act, 1956",
    "Dowry Prohibition Act, 1961",
    "Family Courts Act, 1984",
    "Dissolution of Muslim Marriages Act, 1939",
  ],
  docTypes: [
    "Marriage certificate", "Wedding invitation / photographs", "Divorce petition", "Petition for restitution of conjugal rights (s.9 HMA)",
    "Maintenance petition (s.144 BNSS / s.125 CrPC)", "Application under s.12 DV Act", "Domestic incident report", "Affidavit of assets and liabilities",
    "Salary slip", "Income tax return", "Bank statement", "Property documents", "Stridhan list", "Police complaint / FIR", "Medical record",
    "Mediation report", "Settlement / MoU", "Custody / visitation order", "School records", "Chat / message record", "Email / letter",
  ],
  issues: [
    iss("grounds", "Grounds for divorce", "The document bears on a ground for divorce or judicial separation: cruelty, desertion for two years, adultery, conversion, mental disorder, or irretrievable breakdown."),
    iss("maintenance_means", "Income, means and maintenance", "The document shows either spouse's income, earning capacity, assets, liabilities, lifestyle or expenses, or maintenance claimed, paid or ordered."),
    iss("domestic_violence", "Domestic violence", "The document describes physical, sexual, verbal, emotional or economic abuse, with dates, or relief under the DV Act."),
    iss("child_welfare", "Children and custody", "The document concerns the children: their age, schooling, health, who cares for them, custody or visitation, and their welfare."),
    iss("stridhan_dowry", "Stridhan and dowry", "The document concerns stridhan, jewellery, gifts at marriage, or dowry demands."),
    iss("residence", "Shared household and residence", "The document concerns the shared household, residence rights, or dispossession (s.17 DV Act)."),
    iss("settlement", "Settlement and mutual consent", "The document records mediation, settlement terms, or consent to divorce by mutual consent (s.13B HMA)."),
  ],
  columns: [
    col("petitioner", "Petitioner / applicant", "party", "The petitioner, applicant or complainant."),
    col("respondent", "Respondent", "party", "The respondent or opposite party."),
    col("date_of_marriage", "Date of marriage", "date", "The date of marriage, as written."),
    col("marriage_details", "Place and form of marriage", "text", "Where and under which law or rites the marriage was solemnised, and whether it was registered."),
    col("date_of_separation", "Date of separation", "date", "The date the parties began living separately."),
    col("children", "Children", "list", "Each child with age or date of birth and with whom the child lives."),
    col("income_husband", "Husband's income", "amount", "The husband's income as stated (monthly or annual; say which) and its source."),
    col("income_wife", "Wife's income", "amount", "The wife's income as stated (monthly or annual; say which) and its source."),
    col("maintenance_claimed", "Maintenance claimed", "amount", "Maintenance claimed per month (and interim maintenance, if separately claimed)."),
    col("maintenance_ordered", "Maintenance ordered", "amount", "Maintenance awarded or paid, with the order date if stated."),
    col("allegations", "Allegations", "list", "Each specific allegation of cruelty, violence or misconduct, with its date where given."),
    col("stridhan_items", "Stridhan items", "list", "Each item of stridhan or dowry listed, with its value if stated."),
    col("residence", "Residence", "text", "The shared household and who is in occupation."),
    col("custody_arrangement", "Custody arrangement", "text", "Current custody or visitation arrangement, or the arrangement sought."),
    col("prior_proceedings", "Other proceedings", "list", "Other proceedings between the parties (case type, number, court, status)."),
    col("settlement_terms", "Settlement terms", "text", "Terms of any settlement or mediated agreement (amount, custody, withdrawal of cases)."),
  ],
  questions: [
    "Set out the matrimonial history: marriage, cohabitation, separation and children, with dates.",
    "What specific allegations does each party make, with dates and the documents that support them?",
    "What do the documents show about each spouse's income, assets, liabilities and expenses?",
    "What maintenance has been claimed, ordered or paid, and is anything in arrears?",
    "What stridhan or dowry items are claimed and where are they said to be?",
    "What do the documents show about the children's welfare, schooling and current care?",
    "What other proceedings are pending between the parties?",
    "Has any settlement or mutual-consent arrangement been proposed or recorded?",
  ],
};

const TAX: ReviewPlaybook = {
  id: "tax-gst",
  area: "tax-gst",
  name: "Tax and GST",
  description: "Show cause notices, assessments and returns for GST and income-tax disputes: the demand, the provisions invoked, limitation, input tax credit and natural justice. Use it to prepare replies, appeals and writ petitions.",
  statutes: [
    "Central Goods and Services Tax Act, 2017",
    "Integrated Goods and Services Tax Act, 2017",
    "Central Goods and Services Tax Rules, 2017",
    "Income-tax Act, 1961",
    "Income-tax Act, 2025 (for tax years from 1 April 2026)",
    "Customs Act, 1962",
  ],
  docTypes: [
    "Show cause notice", "Form GST DRC-01", "Form GST DRC-01A", "Form GST ASMT-10", "Reply to show cause notice", "Order-in-original",
    "Form GST DRC-07", "Summons u/s 70 CGST", "Statement recorded u/s 70 CGST", "Inspection / search panchnama (s.67 CGST)", "Tax invoice",
    "E-way bill", "GSTR-1 / GSTR-3B return", "GSTR-2A / GSTR-2B statement", "Notice u/s 148A / 148 Income-tax Act", "Notice u/s 142(1)",
    "Assessment order", "Penalty notice", "Appeal (Form GST APL-01 / Form 35)", "Books of account / ledger", "Bank statement", "Contract / purchase order",
  ],
  issues: [
    iss("limitation", "Limitation for notice and order", "The document bears on the time limit for the notice or order (ss.73, 74, 74A CGST; ss.149 and 153 Income-tax Act) or invokes an extended period."),
    iss("itc", "Input tax credit", "The document concerns input tax credit: conditions under s.16(2), the time limit in s.16(4), blocked credits under s.17(5), mismatch with GSTR-2A/2B, or supplier default."),
    iss("classification_valuation", "Classification, rate and valuation", "The document concerns the classification, HSN/SAC, rate of tax, place of supply or valuation of a supply."),
    iss("suppression", "Fraud, suppression and penalty", "The document alleges or rebuts fraud, wilful misstatement or suppression of facts, or proposes penalty."),
    iss("natural_justice", "Natural justice", "The document bears on the opportunity of hearing (s.75(4) CGST), supply of relied-upon documents, time to reply, or a non-speaking order."),
    iss("reassessment", "Reassessment procedure", "The document concerns reopening under ss.147-151 Income-tax Act: the s.148A inquiry, information relied on, approvals and time limits."),
    iss("pre_deposit_recovery", "Pre-deposit, stay and recovery", "The document concerns appeal pre-deposit, stay of demand, attachment of bank accounts or recovery."),
  ],
  columns: [
    col("taxpayer", "Taxpayer", "party", "The taxpayer or noticee."),
    col("gstin_or_pan", "GSTIN / PAN", "text", "GSTIN or PAN as written."),
    col("authority", "Issuing authority", "text", "The officer, designation and office issuing the document."),
    col("notice_number", "Reference / DIN", "text", "Notice or order number and the DIN, if any."),
    col("notice_date", "Date of notice / order", "date", "The date of issue, as written."),
    col("tax_period", "Tax period", "text", "The tax period or assessment year concerned."),
    col("provision_invoked", "Demand provision", "choice", "The provision under which the demand is raised.", ["Section 73 CGST", "Section 74 CGST", "Section 74A CGST", "Section 147/148 Income-tax Act", "Section 143(3) Income-tax Act", "Other", "Not stated"]),
    col("sections_invoked", "All sections invoked", "list", "Every statutory provision and rule invoked."),
    col("tax_demanded", "Tax demanded", "amount", "Tax demanded (by head: CGST/SGST/IGST/cess, or income tax), as written."),
    col("interest_demanded", "Interest", "amount", "Interest demanded and the provision (e.g. s.50 CGST)."),
    col("penalty", "Penalty", "amount", "Penalty proposed or imposed and the provision."),
    col("itc_disputed", "ITC disputed", "amount", "The input tax credit disallowed or proposed to be reversed."),
    col("grounds", "Grounds", "text", "The grounds or allegations on which the demand rests, briefly."),
    col("hearing_offered", "Personal hearing offered", "yes_no", "Whether a personal hearing was offered or held."),
    col("reply_due_date", "Reply / hearing date", "date", "The date by which the reply is due or the hearing is fixed."),
    col("din_quoted", "DIN quoted", "yes_no", "Whether the communication quotes a Document Identification Number (DIN)."),
  ],
  questions: [
    "Summarise each notice or order: authority, date, period, provisions invoked and amounts (tax, interest, penalty).",
    "Is each notice and order within limitation? Which period is invoked and on what allegation?",
    "What input tax credit is disputed and on what ground?",
    "Which allegations of fraud, suppression or wilful misstatement are made, and what evidence is cited?",
    "Was the taxpayer given a personal hearing and the documents relied upon?",
    "What has the taxpayer said in reply, and which points does the order deal with or ignore?",
    "For income-tax reassessment: what information was relied on, and were the s.148A procedure and approvals followed?",
  ],
};

const IP: ReviewPlaybook = {
  id: "ip",
  area: "ip",
  name: "Intellectual property",
  description: "Trade mark, copyright, patent and design disputes: ownership and chain of title, registrations, use and goodwill, infringement evidence, delay and damages. Use it for infringement and passing-off suits and oppositions.",
  statutes: [
    "Trade Marks Act, 1999",
    "Copyright Act, 1957",
    "Patents Act, 1970",
    "Designs Act, 2000",
    "Geographical Indications of Goods (Registration and Protection) Act, 1999",
    "Information Technology Act, 2000",
    "Commercial Courts Act, 2015",
  ],
  docTypes: [
    "Trade mark registration certificate", "Trade mark application / examination report", "Opposition / counter-statement",
    "Copyright registration certificate", "Patent specification", "Patent certificate", "Statement of working (Form 27)",
    "Design registration certificate", "Assignment deed", "Licence agreement", "Cease and desist notice", "Reply to cease and desist",
    "Invoices / sales figures", "Advertisement / marketing material", "Product photographs", "Screenshot / website capture",
    "Investigator's report", "Local commissioner's report", "Customs recordal", "Plaint for infringement / passing off",
  ],
  issues: [
    iss("ownership", "Ownership and chain of title", "The document shows who owns or created the right, its registration, assignment or licence, or a gap in the chain of title."),
    iss("validity", "Validity and registrability", "The document bears on distinctiveness, prior art, novelty, originality, descriptiveness, or grounds of invalidity or rectification."),
    iss("infringement", "Infringement and similarity", "The document shows the defendant's use, product or work and its similarity to the plaintiff's (marks, trade dress, claims read on product, copying)."),
    iss("prior_use_goodwill", "Prior use and goodwill", "The document shows the date of first use, sales, advertising spend or reputation, relevant to priority and passing off."),
    iss("confusion", "Actual confusion and deception", "The document records actual confusion among customers or the trade, or deceptive conduct."),
    iss("damages", "Damages and account of profits", "The document shows sales, profits or losses relevant to damages or an account of profits."),
    iss("delay_acquiescence", "Delay and acquiescence", "The document shows when the right holder learned of the infringement, any delay, or conduct amounting to acquiescence or consent."),
  ],
  columns: [
    col("rights_holder", "Right holder", "party", "The owner or claimant of the right."),
    col("alleged_infringer", "Alleged infringer", "party", "The party alleged to infringe."),
    col("ip_right", "Right", "choice", "The type of right the document concerns.", ["Trade mark", "Copyright", "Patent", "Design", "Geographical indication", "Confidential information", "Not stated"]),
    col("registration_number", "Registration / application no.", "text", "Registration or application number, as written."),
    col("class_or_category", "Class / category", "text", "Trade mark class, copyright work category, or patent / design class."),
    col("registration_date", "Registration / filing date", "date", "Date of registration or filing (priority date for patents, if stated)."),
    col("first_use_date", "Date of first use", "date", "The date of first use claimed (\"user since\" for marks), or creation/publication date for works."),
    col("marks_or_works", "Marks / works compared", "text", "The plaintiff's and the defendant's marks, works or products, as described."),
    col("goods_services", "Goods / services", "text", "The goods or services in question."),
    col("knowledge_date", "Knowledge of infringement", "date", "When the right holder says it first learned of the infringing use."),
    col("territory", "Territory / channels", "text", "Where and through which trade channels the goods are sold."),
    col("sales_figures", "Sales / turnover", "amount", "Sales or turnover figures stated, with period."),
    col("advertising_spend", "Advertising spend", "amount", "Advertising or promotional expenditure stated, with period."),
    col("licence_assignment", "Licence / assignment terms", "text", "Parties, scope, territory, term and royalty of any licence or assignment."),
    col("confusion_evidence", "Evidence of confusion", "text", "Instances of actual confusion described."),
    col("renewal_status", "Renewal / status", "text", "Renewal date or current status of the registration (registered, opposed, lapsed)."),
  ],
  questions: [
    "Who owns each right in issue, and what documents prove the chain of title?",
    "What registrations are relied on, with numbers, classes, dates and current status?",
    "Since when has the right holder used the mark or work, and what sales and advertising figures support goodwill?",
    "What evidence shows the defendant's use, and how similar is it?",
    "Is there evidence of actual confusion?",
    "When did the right holder learn of the infringement, and is there any delay or acquiescence?",
    "What licences or assignments affect the parties' rights?",
  ],
};

const CONSUMER: ReviewPlaybook = {
  id: "consumer",
  area: "consumer",
  name: "Consumer protection",
  description: "Consumer complaints about goods, services, insurance, housing and medical treatment: consumer status, deficiency, limitation, jurisdiction and compensation. Use it to prepare or defend complaints before District, State and National Commissions.",
  statutes: [
    "Consumer Protection Act, 2019",
    "Consumer Protection (E-Commerce) Rules, 2020",
    "Consumer Protection (Jurisdiction of the District Commission, the State Commission and the National Commission) Rules, 2021",
    "Consumer Protection (Consumer Commissions Procedure) Regulations, 2020",
    "Insurance Regulatory and Development Authority of India (Protection of Policyholders' Interests and Allied Matters of Insurers) Regulations, 2024",
    "Real Estate (Regulation and Development) Act, 2016",
  ],
  docTypes: [
    "Consumer complaint", "Written version / reply", "Invoice / bill", "Order confirmation (e-commerce)", "Warranty card", "Job card / service record",
    "Insurance policy", "Claim form", "Repudiation letter", "Surveyor's report", "Builder-buyer agreement", "Payment receipt",
    "Discharge summary / medical record", "Expert opinion", "Legal notice", "Reply to legal notice", "Email / correspondence", "Photographs",
    "Affidavit of evidence",
  ],
  issues: [
    iss("consumer_status", "Consumer status", "The document shows whether the complainant bought the goods or service for consideration and whether for a commercial purpose (s.2(7) CPA 2019)."),
    iss("deficiency_defect", "Deficiency or defect", "The document describes a defect in goods or a deficiency in service, and its cause."),
    iss("unfair_trade_practice", "Unfair trade practice", "The document shows misleading advertisement, false representation, hidden charges or unfair contract terms."),
    iss("limitation", "Limitation", "The document bears on when the cause of action arose or continued, relevant to the two-year limitation under s.69."),
    iss("jurisdiction", "Pecuniary and territorial jurisdiction", "The document shows the consideration paid (pecuniary jurisdiction) or where the complainant resides or works, or where the cause of action arose."),
    iss("compensation", "Compensation", "The document shows loss, expenses, mental agony or other heads for compensation, refund or replacement."),
    iss("insurance_repudiation", "Insurance repudiation", "The document gives or rebuts a ground for repudiating an insurance claim (non-disclosure, policy exclusion, delay in intimation)."),
    iss("medical_negligence", "Medical negligence", "The document bears on the standard of care, consent, treatment given or expert opinion in a medical negligence claim."),
  ],
  columns: [
    col("complainant", "Complainant", "party", "The consumer or complainant."),
    col("opposite_parties", "Opposite parties", "list", "Every opposite party (seller, manufacturer, service provider, insurer, platform)."),
    col("product_or_service", "Product / service", "text", "The goods or service in question, with model, policy or unit number."),
    col("purchase_date", "Purchase / availed date", "date", "The date the goods were bought or the service availed."),
    col("consideration_paid", "Amount paid", "amount", "The consideration paid for the goods or service."),
    col("defect_or_deficiency", "Defect / deficiency", "text", "The defect or deficiency alleged, as described."),
    col("complaint_raised_date", "First complaint to trader", "date", "When the complainant first raised the problem with the opposite party."),
    col("response", "Opposite party's response", "text", "How the opposite party responded (repair, refusal, repudiation, no reply)."),
    col("cause_of_action_date", "Cause of action date", "date", "The date the cause of action arose (e.g. repudiation, final refusal, failure to deliver)."),
    col("commercial_purpose", "Commercial purpose", "yes_no", "Whether the document shows the goods or service were obtained for a commercial purpose."),
    col("warranty_terms", "Warranty / policy terms", "text", "Relevant warranty, guarantee or policy terms and exclusions."),
    col("repudiation_ground", "Repudiation ground", "text", "The ground given for rejecting a claim."),
    col("relief_claimed", "Relief claimed", "text", "Relief claimed (refund, replacement, repair, compensation, costs)."),
    col("compensation_claimed", "Compensation claimed", "amount", "Total compensation claimed."),
    col("expert_evidence", "Expert evidence", "text", "Any expert or surveyor opinion and its conclusion."),
  ],
  questions: [
    "Is the complainant a consumer? Was the purchase for any commercial purpose?",
    "What defect or deficiency is alleged, and what evidence supports it?",
    "Set out the chronology from purchase to complaint, with each communication.",
    "When did the cause of action arise, and is the complaint within two years (s.69)?",
    "What was paid, and which Commission has pecuniary and territorial jurisdiction?",
    "For insurance claims: what ground of repudiation is given and what do the policy terms say?",
    "What compensation is claimed under each head, and what evidence supports it?",
  ],
};

const MOTOR: ReviewPlaybook = {
  id: "motor-accident",
  area: "motor-accident",
  name: "Motor accident claims",
  description: "MACT claim papers: negligence, the vehicle and policy, the victim's age, income and dependants, injuries and disability, and every input for computing compensation under Sarla Verma and Pranay Sethi.",
  statutes: [
    "Motor Vehicles Act, 1988 (ss.140, 147, 149, 163A, 164, 166, 168)",
    "Motor Vehicles (Amendment) Act, 2019",
    "Central Motor Vehicles Rules, 1989",
    "Bharatiya Nyaya Sanhita, 2023, ss.106 and 281 (formerly Indian Penal Code, 1860, ss.304A and 279)",
  ],
  docTypes: [
    "FIR", "Detailed accident report", "Site plan", "Mechanical inspection report", "Chargesheet", "Post-mortem report", "Medico-legal certificate (MLC)",
    "Discharge summary", "Medical bills", "Disability certificate", "Driving licence", "Registration certificate (RC)", "Insurance policy / cover note",
    "Permit / fitness certificate", "Salary certificate / slip", "Income tax return", "Age proof (school certificate / Aadhaar)", "Legal heir certificate",
    "Claim petition (s.166)", "Written statement of insurer", "Award",
  ],
  issues: [
    iss("negligence", "Negligence", "The document bears on how the accident happened, rash or negligent driving, or contributory negligence of the victim."),
    iss("policy_defences", "Policy and licence defences", "The document bears on the insurer's defences: validity of the driving licence, permit, fitness, policy period, use contrary to policy (s.149 MV Act)."),
    iss("income_dependency", "Income and dependency", "The document proves the victim's age, occupation, income, future prospects or the number of dependants (Sarla Verma; Pranay Sethi)."),
    iss("injury_disability", "Injuries and disability", "The document records injuries, treatment, permanent disability (physical and functional) or medical expenses."),
    iss("conventional_heads", "Non-pecuniary heads", "The document bears on loss of consortium, loss of estate, funeral expenses, pain and suffering or loss of amenities."),
    iss("limitation_jurisdiction", "Limitation and jurisdiction", "The document bears on the claim's limitation (s.166(3), six months, for accidents after the 2019 amendment came into force) or the Tribunal's territorial jurisdiction."),
  ],
  columns: [
    col("claimants", "Claimants", "list", "Each claimant with relationship to the victim and age."),
    col("victim", "Deceased / injured", "party", "The deceased or injured person."),
    col("victim_age", "Victim's age", "text", "The victim's age or date of birth, and the document it is drawn from."),
    col("occupation", "Occupation", "text", "The victim's occupation and employer."),
    col("monthly_income", "Monthly income", "amount", "The victim's monthly (or annual; say which) income as stated or proved."),
    col("accident_date", "Accident date and time", "date", "The date (and time) of the accident."),
    col("accident_place", "Place of accident", "text", "The place of the accident."),
    col("offending_vehicle", "Offending vehicle", "text", "Registration number and type of the offending vehicle."),
    col("driver", "Driver", "party", "The driver of the offending vehicle."),
    col("owner", "Owner", "party", "The registered owner of the offending vehicle."),
    col("insurer", "Insurer", "party", "The insurer of the offending vehicle."),
    col("policy_details", "Policy no. and period", "text", "Policy number, type and period of cover."),
    col("licence_valid", "Driving licence valid", "yes_no", "Whether the driver held a valid and effective licence for that class of vehicle on the accident date."),
    col("injuries", "Injuries", "list", "Each injury recorded."),
    col("disability_percent", "Disability %", "text", "Permanent disability percentage certified, and the limb or whole-body basis."),
    col("medical_expenses", "Medical expenses", "amount", "Total medical expenses shown by bills."),
    col("dependants", "Dependants", "list", "Each dependant with age and relationship."),
    col("fir_details", "FIR details", "text", "FIR number, police station and sections."),
  ],
  questions: [
    "How did the accident happen, according to the FIR, site plan and chargesheet? Is there any contributory negligence?",
    "What was the victim's age, and which document proves it?",
    "What was the victim's occupation and income, and what documents prove it?",
    "Who are the dependants, with ages and relationship?",
    "List the inputs for computing compensation: income, future prospects, deduction for personal expenses, multiplier (Sarla Verma; Pranay Sethi).",
    "What injuries and permanent disability are recorded, and what medical expenses are proved?",
    "Did the driver hold a valid licence, and were the permit, fitness and policy in force on the accident date?",
    "Which non-pecuniary heads (consortium, loss of estate, funeral expenses) are claimed?",
  ],
};

const SERVICE: ReviewPlaybook = {
  id: "service-constitutional",
  area: "service-constitutional",
  name: "Service and writ matters",
  description: "Service disputes and writ petitions against the State: appointments, promotions, seniority, disciplinary proceedings, pay and pension. Use it to test the impugned action against the rules, Articles 14, 16 and 311 and natural justice.",
  statutes: [
    "Constitution of India (Articles 14, 16, 32, 226, 227, 309 and 311)",
    "Central Civil Services (Classification, Control and Appeal) Rules, 1965",
    "Central Civil Services (Conduct) Rules, 1964",
    "Central Civil Services (Pension) Rules, 2021",
    "Administrative Tribunals Act, 1985",
    "Rights of Persons with Disabilities Act, 2016",
    "Right to Information Act, 2005",
  ],
  docTypes: [
    "Recruitment notification", "Appointment order", "Seniority list", "DPC minutes", "Promotion order", "Transfer order", "Suspension order",
    "Memorandum of charges", "Statement of imputations", "Enquiry officer's report", "Show cause notice", "Representation", "Penalty order",
    "Appellate order", "Revision / review order", "APAR", "Pay fixation / pension order", "Office memorandum / government resolution",
    "Service rules", "Disability certificate", "RTI reply", "Writ petition / original application", "Counter affidavit",
  ],
  issues: [
    iss("natural_justice", "Natural justice and Art. 311(2)", "The document bears on notice, supply of documents, opportunity to be heard, cross-examination, or dispensing with enquiry under Art. 311(2)."),
    iss("competence", "Competent authority", "The document shows who passed the order and whether that authority was competent (appointing authority, delegation)."),
    iss("proportionality", "Proportionality of penalty", "The document bears on the gravity of the charge, the penalty imposed and comparable cases."),
    iss("delay", "Delay in proceedings", "The document shows delay in initiating or concluding disciplinary proceedings, or delay and laches in the employee's challenge."),
    iss("seniority_promotion", "Seniority and promotion", "The document concerns seniority, eligibility, DPC assessment, sealed cover procedure or promotion."),
    iss("recruitment_reservation", "Recruitment and reservation", "The document concerns eligibility criteria, selection, reservation rosters or recruitment rules."),
    iss("pay_pension", "Pay and pension", "The document concerns pay fixation, arrears, recovery from pay, pension or retiral dues."),
  ],
  columns: [
    col("petitioner", "Employee / petitioner", "party", "The employee or petitioner."),
    col("respondent_authority", "Respondent authorities", "list", "The department, authority and officers concerned."),
    col("post_and_cadre", "Post and cadre", "text", "The post, cadre, grade and pay level."),
    col("date_of_appointment", "Date of appointment", "date", "The date of appointment to service or to the post."),
    col("impugned_order", "Order reference", "text", "The number, authority and subject of the order in the document."),
    col("order_date", "Order date", "date", "The date of the order or communication."),
    col("passed_by", "Passed by", "text", "The authority who signed or passed the order, with designation."),
    col("charges", "Charges", "list", "Each article of charge, briefly."),
    col("penalty_imposed", "Penalty", "text", "The penalty imposed or proposed (minor or major, and its terms)."),
    col("enquiry_held", "Enquiry held", "yes_no", "Whether a regular enquiry was held."),
    col("documents_supplied", "Documents supplied", "yes_no", "Whether the relied-upon documents and the enquiry report were supplied to the employee."),
    col("representation_date", "Representation date", "date", "The date of the employee's representation, reply or appeal."),
    col("rules_invoked", "Rules invoked", "list", "Every rule, OM or provision relied on in the document."),
    col("relief_sought", "Relief sought", "text", "The relief the employee seeks."),
    col("alternate_remedy", "Alternative remedy", "text", "Any appeal, revision or Tribunal remedy mentioned, and whether it was availed."),
  ],
  questions: [
    "What is the impugned action, who passed it and when, and under which rule?",
    "Was the authority that passed the order competent to do so?",
    "Was the employee given the charges, relied-upon documents and enquiry report, and an opportunity to be heard?",
    "What are the charges, what did the enquiry find, and is the penalty proportionate?",
    "Was there delay in initiating or completing the proceedings, or in the employee's challenge?",
    "What do the documents show about seniority, DPC assessments or promotion?",
    "What pay, pension or retiral dues are withheld or recovered, and on what basis?",
  ],
};

const COMPETITION: ReviewPlaybook = {
  id: "competition-regulatory",
  area: "competition-regulatory",
  name: "Competition and securities regulation",
  description: "CCI and SEBI investigations: competitor communications, pricing, dominance and market definition, UPSI and trading, disclosure lapses and penalties. Use it to review a document production or prepare a reply to a DG or SEBI notice.",
  statutes: [
    "Competition Act, 2002 (as amended in 2023)",
    "Competition Commission of India (Lesser Penalty) Regulations, 2024",
    "Securities and Exchange Board of India Act, 1992",
    "SEBI (Prohibition of Insider Trading) Regulations, 2015",
    "SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015",
    "SEBI (Substantial Acquisition of Shares and Takeovers) Regulations, 2011",
    "SEBI (Prohibition of Fraudulent and Unfair Trade Practices relating to Securities Market) Regulations, 2003",
    "Companies Act, 2013",
  ],
  docTypes: [
    "Information / complaint to CCI", "DG investigation report", "CCI order", "Notice from DG / CCI", "Combination notice", "Distribution / dealership agreement",
    "Pricing circular / price list", "Trade association minutes", "Email / correspondence", "Chat / message record", "Board minutes",
    "SEBI show cause notice", "SEBI order", "Trading data / demat statement", "Insider trading disclosure", "Stock exchange filing", "Annual report",
    "Structured digital database extract", "Whistle-blower complaint",
  ],
  issues: [
    iss("horizontal_agreement", "Cartel / horizontal agreement", "The document shows contact, information exchange, or agreement between competitors on price, output, markets or bids (s.3(3) Competition Act)."),
    iss("vertical_restraint", "Vertical restraints", "The document shows resale price maintenance, exclusive supply or distribution, tie-in or refusal to deal (s.3(4))."),
    iss("dominance", "Dominance and abuse", "The document bears on the relevant market, market share, dominance or abusive conduct (s.4)."),
    iss("upsi", "UPSI and insider trading", "The document shows unpublished price sensitive information, who had it and when, or trades while in possession of it."),
    iss("disclosure", "Disclosure obligations", "The document bears on timely disclosure of material events or of trades (LODR Reg. 30; PIT Regs.)."),
    iss("penalty_leniency", "Penalty and leniency", "The document bears on turnover for penalty, mitigating factors, lesser-penalty applications or settlement and commitment."),
    iss("procedural_fairness", "Procedural fairness", "The document concerns access to the investigation report or evidence, cross-examination, or hearing."),
  ],
  columns: [
    col("entities", "Entities", "list", "Every company or person named and their role (competitor, distributor, insider, noticee)."),
    col("regulator", "Regulator / forum", "choice", "The regulator or forum the document concerns.", ["CCI", "DG (CCI)", "SEBI", "SAT", "NCLAT", "Other", "Not stated"]),
    col("proceeding_reference", "Case reference", "text", "Case, notice or investigation number."),
    col("doc_date", "Date", "date", "The date of the document or communication."),
    col("provisions_invoked", "Provisions invoked", "list", "Every statutory provision or regulation invoked."),
    col("relevant_market", "Relevant market", "text", "The relevant product and geographic market as described."),
    col("conduct_alleged", "Conduct", "text", "The conduct described or alleged."),
    col("competitor_contact", "Competitor contact", "text", "Any communication or meeting between competitors: who, when, and what was discussed."),
    col("pricing_information", "Pricing information", "text", "Prices, price changes, discounts or margins discussed or set."),
    col("upsi", "UPSI", "text", "The unpublished price sensitive information described and the period it was unpublished."),
    col("persons_with_upsi", "Persons with UPSI", "list", "Persons shown to have had the UPSI."),
    col("trades", "Trades", "text", "Trades in securities: who, which scrip, dates and quantities."),
    col("penalty", "Penalty", "amount", "Penalty proposed or imposed."),
    col("leniency_settlement", "Leniency / settlement", "text", "Any lesser-penalty application, settlement or commitment."),
  ],
  questions: [
    "Which communications between competitors are in the documents, who took part and what was discussed?",
    "What do the documents show about prices, discounts or bids being aligned?",
    "How is the relevant market described, and what market shares are shown?",
    "What restrictions are imposed on distributors or customers?",
    "What UPSI existed, when was it generated and disclosed, and who had access to it?",
    "What trades were made during the UPSI period, and by whom?",
    "Were the required disclosures made on time?",
    "What mitigating factors or leniency steps appear in the documents?",
  ],
};

export const PLAYBOOKS: readonly ReviewPlaybook[] = [GENERAL, COMMERCIAL, INSOLVENCY, REAL_ESTATE, EMPLOYMENT, CRIMINAL, FAMILY, TAX, IP, CONSUMER, MOTOR, SERVICE, COMPETITION];

export function getPlaybook(id: unknown): ReviewPlaybook | null {
  if (typeof id !== "string") return null;
  return PLAYBOOKS.find((p) => p.id === id) ?? null;
}
