import type { CodingDecision } from "@/lib/types/domain";
import { DEMO_ID as D, type DocSpec } from "./doc-spec";

/**
 * Hyderabad matters (synthetic): W.P. No. 18234 of 2026 before the High Court for the State of Telangana against a
 * demolition notice of a FICTIONAL municipality, and the related Crl.P. No. 7710 of 2026 for regular bail under s.483
 * BNSS. The alleged offence is dated 12.08.2026 — after 1 July 2024, so the BNS and BNSS apply without any question of
 * the transition. Telugu originals are the text of record; English translations are labelled as translations.
 */

const R = "p_demo_in_sai_kiran_reddy";
const T = "2026-09-15T10:00:00Z";
const code = (c: Partial<CodingDecision>): Partial<CodingDecision> => ({ responsive: true, reviewerId: R, reviewedAt: T, ...c });

export const WRIT_DOCS: DocSpec[] = [
  { id: D("w_notice_te"), source: "municipality", date: "2026-07-21", type: "Letter", subject: "Demolition notice of the Chandrayanagiri Municipality (Telugu)", from: "Commissioner, Chandrayanagiri Municipality", to: ["Kondapalli Sarojini Devi"], body: "నోటీసు\n\nచంద్రయానగిరి పురపాలక సంఘం (కల్పితం)\n\nశ్రీమతి కొండపల్లి సరోజినీ దేవి గారికి, ప్లాట్ నం. 27, సర్వే నం. 214/ఎ.\n\nమీ భవనం పెద్దచెరువు పూర్తి నీటి మట్టం (FTL) బఫర్ జోన్‌లో నిర్మించబడినట్లు గుర్తించబడింది. ఈ నోటీసు అందిన ఏడు రోజుల లోపు ఆ నిర్మాణాన్ని మీరే తొలగించాలి, లేనిచో పురపాలక సంఘం తొలగిస్తుంది మరియు ఖర్చును మీ నుండి వసూలు చేస్తుంది.\n\nకమిషనర్", india: { docClass: "notice", filedBy: "respondent", language: "te", docNumber: "Material papers, p. 14" }, coding: code({ hot: true, issues: ["NJ-01", "FTL-01"] }), tags: ["key-doc", "telugu", "impugned"], aiScore: 96 },
  { id: D("w_notice_en"), source: "petitioner", date: "2026-07-28", type: "Letter", subject: "English translation of the demolition notice dated 21.07.2026", from: "Commissioner, Chandrayanagiri Municipality", to: ["Kondapalli Sarojini Devi"], body: "TRANSLATION (filed by the petitioner; the Telugu original is the text of record).\n\nNOTICE\n\nChandrayanagiri Municipality (fictional)\n\nTo Smt. Kondapalli Sarojini Devi, Plot No. 27, Survey No. 214/A.\n\nIt has been found that your building has been constructed within the Full Tank Level (FTL) buffer zone of Peddacheruvu. You shall remove the structure yourself within seven days of receipt of this notice, failing which the Municipality will remove it and recover the cost from you.\n\nCommissioner", india: { docClass: "translation", filedBy: "petitioner", language: "en", translationOf: D("w_notice_te"), translationOrigin: "provider", docNumber: "Material papers, p. 15" }, coding: code({ hot: true, issues: ["NJ-01", "FTL-01"] }), tags: ["translation"] },
  { id: D("w_permit"), source: "petitioner", date: "2019-07-03", type: "Other", subject: "Building permission BP/2019/0412 for Plot No. 27, Sy. No. 214/A", body: "BUILDING PERMISSION No. BP/2019/0412 dated 03.07.2019 issued by the Chandrayanagiri Municipality (fictional) for a ground plus one floor residential building on Plot No. 27 in Sy. No. 214/A. Setbacks and plan approved. Irrigation department NOC dated 18.06.2019 enclosed: the plot lies outside the FTL and buffer of Peddacheruvu as per the survey then on record.", pages: 3, india: { docClass: "document", filedBy: "petitioner", docNumber: "Material papers, pp. 5–7" }, coding: code({ hot: true, issues: ["BP-01", "FTL-01"] }), tags: ["key-doc"], aiScore: 93 },
  { id: D("w_sale_deed"), source: "petitioner", date: "2017-11-20", type: "Contract", subject: "Registered sale deed — Plot No. 27, Sy. No. 214/A (extract)", body: "SALE DEED registered as Document No. 11842 of 2017 at the Sub-Registrar's office (demo). Vendor: a fictional layout developer. Purchaser: Smt. Kondapalli Sarojini Devi. Schedule: Plot No. 27, admeasuring 200 square yards, in Sy. No. 214/A, Chandrayanagiri (fictional), Ranga Reddy District.", pages: 8, india: { docClass: "document", filedBy: "petitioner", docNumber: "Material papers, pp. 1–4" }, coding: code({ issues: ["BP-01"] }) },
  { id: D("w_tax"), source: "petitioner", date: "2026-04-10", type: "Other", subject: "Property tax receipt 2026-27", body: "Property tax receipt for 2026-27 for House No. 3-27, assessed on the building constructed under BP/2019/0412.", pages: 1, india: { docClass: "document", filedBy: "petitioner", docNumber: "Material papers, p. 8" }, coding: code({ issues: ["BP-01"] }) },
  { id: D("w_representation"), source: "petitioner", date: "2026-07-24", type: "Letter", subject: "Petitioner's representation to the Commissioner seeking survey records and a hearing", from: "Kondapalli Sarojini Devi", to: ["Commissioner, Chandrayanagiri Municipality"], body: "Sir, I received the notice dated 21.07.2026. My house was built under BP/2019/0412 with the Irrigation department's NOC. The notice does not enclose any survey showing the FTL line or give me an opportunity to be heard. I request copies of the survey records and a personal hearing before any action. No reply has been received.", pages: 2, india: { docClass: "correspondence", filedBy: "petitioner", docNumber: "Material papers, pp. 16–17" }, coding: code({ hot: true, issues: ["NJ-01"] }), tags: ["key-doc"], aiScore: 88 },
  { id: D("w_petition"), source: "courtHyd", date: "2026-07-29", type: "Other", subject: "W.P. No. 18234 of 2026 — affidavit of the petitioner and writ petition", body: "IN THE HIGH COURT FOR THE STATE OF TELANGANA AT HYDERABAD. W.P. No. 18234 of 2026. Affidavit of Smt. Kondapalli Sarojini Devi. The notice dated 21.07.2026 was issued without a survey, without notice of the FTL demarcation and without a hearing, contrary to the principles of natural justice and Article 300-A. Prayer: Writ of Mandamus declaring the action of Respondent No. 2 in issuing the notice as illegal and arbitrary, and consequently setting it aside. Interim prayer: suspension of the notice.", pages: 22, india: { docClass: "pleading", filedBy: "petitioner", title: "Writ petition (Art. 226)" }, coding: code({ issues: ["NJ-01", "FTL-01", "BP-01"] }), tags: ["pleading"] },
  { id: D("w_interim"), source: "courtHyd", date: "2026-07-31", type: "Other", subject: "Interim order in W.P. No. 18234 of 2026 — status quo", body: "Notice before admission. Learned Standing Counsel for Respondent No. 2 takes notice. Until the next date of hearing, the parties shall maintain status quo as on today in respect of the petitioner's building on Plot No. 27. Respondent No. 2 is at liberty to conduct a joint survey with notice to the petitioner. Post after four weeks.", pages: 2, india: { docClass: "order", filedBy: "court", title: "Interim order" }, coding: code({ hot: true, issues: ["NJ-01"] }), tags: ["key-doc", "order"], aiScore: 95 },
  { id: D("w_survey_te"), source: "municipality", date: "2026-08-12", type: "Report", subject: "Survey report of the municipal survey team, 12.08.2026 (Telugu)", from: "B. Narsimha", body: "సర్వే నివేదిక\n\n12.08.2026 ఉదయం 11 గంటలకు సర్వే బృందం ప్లాట్ నం. 27 వద్దకు చేరుకుంది. భవనం FTL సరిహద్దు నుండి సుమారు 38 మీటర్ల దూరంలో ఉంది. ఇంటి యజమాని కుమారుడు ముందస్తు నోటీసు లేదని కొలతలకు అభ్యంతరం చెప్పారు; వాగ్వాదం జరిగింది. సర్వే పూర్తి కాలేదు.\n\nబి. నర్సింహ, టౌన్ ప్లానింగ్ సూపర్వైజర్", india: { docClass: "document", filedBy: "respondent", language: "te" }, coding: code({ hot: true, issues: ["FTL-01", "ALG-01"] }), tags: ["key-doc", "telugu"], aiScore: 94 },
  { id: D("w_survey_en"), source: "petitioner", date: "2026-08-20", type: "Report", subject: "English translation of the survey report dated 12.08.2026", from: "B. Narsimha", body: "TRANSLATION (filed by the petitioner; the Telugu original is the text of record).\n\nSURVEY REPORT\n\nAt 11 a.m. on 12.08.2026 the survey team reached Plot No. 27. The building is about 38 metres from the FTL boundary. The house owner's son objected to the measurements saying that no prior notice had been given; there was an argument. The survey was not completed.\n\nB. Narsimha, Town Planning Supervisor", india: { docClass: "translation", filedBy: "petitioner", language: "en", translationOf: D("w_survey_te"), translationOrigin: "provider" }, coding: code({ hot: true, issues: ["FTL-01", "ALG-01"] }), tags: ["translation"] },
  { id: D("w_counter"), source: "courtHyd", date: "2026-09-02", type: "Other", subject: "Counter-affidavit of Respondent No. 2 (Municipality)", body: "The petitioner's building encroaches the FTL buffer of Peddacheruvu as per the revised FTL map notified in 2024. The building permission of 2019 was based on an earlier map. The survey on 12.08.2026 was obstructed by the petitioner's son, who assaulted the supervisor; a crime has been registered. The writ petition is premature as the petitioner may file objections.", pages: 11, india: { docClass: "pleading", filedBy: "respondent", title: "Counter-affidavit of Respondent No. 2" }, coding: code({ issues: ["FTL-01", "ALG-01"] }), tags: ["pleading"] },
];

export const BAIL_DOCS: DocSpec[] = [
  { id: D("b_fir"), source: "prosecution", date: "2026-08-12", type: "Report", subject: "FIR in Crime No. 612 of 2026 — Chandrayanagiri Police Station (fictional)", body: "FIRST INFORMATION REPORT. Crime No. 612 of 2026. Date and time of occurrence: 12.08.2026, about 11:30 hours. Place: Plot No. 27, Sy. No. 214/A. Sections: 132, 121(1) and 351(2) of the Bharatiya Nyaya Sanhita, 2023. Complainant: B. Narsimha, Town Planning Supervisor. Allegation: while the survey team was measuring the FTL boundary, Kondapalli Ravi Teja obstructed the team, abused the complainant, pushed him and hit him on the left forearm with a wooden stick, and threatened the team with dire consequences if they returned.", pages: 3, india: { docClass: "document", filedBy: "state", docNumber: "Annexure-1" }, coding: code({ hot: true, issues: ["ALG-01", "BAIL-01"] }), tags: ["key-doc"], aiScore: 95 },
  { id: D("b_wound"), source: "prosecution", date: "2026-08-12", type: "Report", subject: "Wound certificate of the complainant", body: "WOUND CERTIFICATE. Patient: B. Narsimha, 46 years. Examined at 14:10 on 12.08.2026. Injury: contusion 3 cm × 2 cm on the left forearm. Nature: simple. Weapon: blunt object.", pages: 1, india: { docClass: "document", filedBy: "state", docNumber: "Annexure-2" }, coding: code({ issues: ["ALG-01"] }) },
  { id: D("b_remand"), source: "prosecution", date: "2026-08-13", type: "Report", subject: "Remand report — arrest of Kondapalli Ravi Teja on 13.08.2026", body: "REMAND REPORT. The accused Kondapalli Ravi Teja, aged 27 years, software tester, was arrested on 13.08.2026 at 07:30 hours at his residence and produced before the Magistrate. The wooden stick has been seized under a seizure memo. Investigation is in progress; statements of three members of the survey team are recorded. Remanded to judicial custody.", pages: 2, india: { docClass: "document", filedBy: "state", docNumber: "Annexure-3" }, coding: code({ issues: ["BAIL-01"] }) },
  { id: D("b_sessions_order"), source: "prosecution", date: "2026-09-04", type: "Other", subject: "Order of the Sessions Court rejecting bail (Crl.M.P. No. 1893 of 2026)", body: "ORDER. The petitioner/accused seeks regular bail. The allegations are that he obstructed public servants and caused hurt to the complainant. Investigation is not complete; the complainant and the survey team are local residents. At this stage the petition is dismissed, with liberty to renew after the charge sheet is filed.", pages: 3, india: { docClass: "order", filedBy: "court", docNumber: "Annexure-4", title: "Order of the Sessions Court" }, coding: code({ hot: true, issues: ["BAIL-01"] }), tags: ["key-doc", "order"], aiScore: 90 },
  { id: D("b_petition"), source: "prosecution", date: "2026-09-10", type: "Other", subject: "Crl.P. No. 7710 of 2026 — petition under Section 483 BNSS for regular bail", body: "IN THE HIGH COURT FOR THE STATE OF TELANGANA AT HYDERABAD. Crl.P. No. 7710 of 2026. Petition under Section 483 of the Bharatiya Nagarik Suraksha Sanhita, 2023 to enlarge the petitioner on bail in Crime No. 612 of 2026. Grounds: the offences under sections 132, 121(1) and 351(2) BNS arise from a survey conducted despite the status quo order of this Court dated 31.07.2026; the survey report records only an objection and an argument, not an assault; the injury is simple; the petitioner has no antecedents and has been in custody since 13.08.2026; the seizure is complete.", pages: 12, india: { docClass: "pleading", filedBy: "accused", title: "Criminal petition (s.483 BNSS)" }, coding: code({ issues: ["BAIL-01", "ALG-01"] }), tags: ["pleading"] },
  { id: D("b_sureties"), source: "prosecution", date: "2026-09-10", type: "Other", subject: "Surety particulars and residence proof", body: "Two sureties offered: the petitioner's uncle (landowner, Ranga Reddy District) and a colleague (employee of a fictional software company, Hyderabad). Residence proof of the petitioner: house at Plot No. 27 (subject of W.P. No. 18234 of 2026).", pages: 4, india: { docClass: "document", filedBy: "accused", docNumber: "Annexure-6" }, coding: code({ issues: ["BAIL-01"] }) },
  { id: D("b_survey_te"), source: "prosecution", date: "2026-08-12", type: "Report", subject: "Survey report dated 12.08.2026 (Telugu) — filed with the bail petition as Annexure-7", from: "B. Narsimha", body: "సర్వే నివేదిక\n\n12.08.2026 ఉదయం 11 గంటలకు సర్వే బృందం ప్లాట్ నం. 27 వద్దకు చేరుకుంది. భవనం FTL సరిహద్దు నుండి సుమారు 38 మీటర్ల దూరంలో ఉంది. ఇంటి యజమాని కుమారుడు ముందస్తు నోటీసు లేదని కొలతలకు అభ్యంతరం చెప్పారు; వాగ్వాదం జరిగింది. సర్వే పూర్తి కాలేదు.\n\nబి. నర్సింహ, టౌన్ ప్లానింగ్ సూపర్వైజర్", india: { docClass: "document", filedBy: "accused", language: "te", docNumber: "Annexure-7" }, coding: code({ hot: true, issues: ["ALG-01"] }), tags: ["key-doc", "telugu"], aiScore: 93 },
  { id: D("b_survey_en"), source: "prosecution", date: "2026-09-10", type: "Report", subject: "English translation of the survey report (Annexure-7A)", from: "B. Narsimha", body: "TRANSLATION (filed by the petitioner; the Telugu original is the text of record).\n\nSURVEY REPORT\n\nAt 11 a.m. on 12.08.2026 the survey team reached Plot No. 27. The building is about 38 metres from the FTL boundary. The house owner's son objected to the measurements saying that no prior notice had been given; there was an argument. The survey was not completed.\n\nB. Narsimha, Town Planning Supervisor", india: { docClass: "translation", filedBy: "accused", language: "en", translationOf: D("b_survey_te"), translationOrigin: "provider", docNumber: "Annexure-7A" }, coding: code({ hot: true, issues: ["ALG-01"] }), tags: ["translation"] },
  { id: D("b_employer"), source: "prosecution", date: "2026-09-08", type: "Letter", subject: "Employer's letter confirming employment of the petitioner", body: "This is to confirm that Mr. Kondapalli Ravi Teja has been employed with us as a Senior Test Engineer since June 2021 and his conduct has been good. [Employer: fictional software company, HITEC City, Hyderabad]", pages: 1, india: { docClass: "document", filedBy: "accused", docNumber: "Annexure-5" }, coding: code({ issues: ["BAIL-01"] }) },
];
