import type { CodingDecision } from "@/lib/types/domain";
import type { IndiaDocMeta } from "@/modules/ediscovery/india";
import { DEMO_ID as D, type DocSpec } from "./doc-spec";

/**
 * Com.O.S. No. 1187 of 2023 — the defendant's documents Ex.D1 to Ex.D18 (D1, D2 and D4 confronted to PW-1 in
 * cross-examination; the rest marked through DW-1 on 20.01.2025), and the court record (pleadings, applications,
 * orders and order sheets). Synthetic; the parties are fictional.
 */

const R = "p_demo_in_kavya_hegde";
const T = "2026-09-11T10:00:00Z";
const code = (c: Partial<CodingDecision>): Partial<CodingDecision> => ({ responsive: true, reviewerId: R, reviewedAt: T, ...c });
const Dx = (n: number, through: "PW-1" | "DW-1", on: string, extra: Partial<IndiaDocMeta> = {}): IndiaDocMeta => ({ docClass: "exhibit", exhibit: `Ex.D${n}`, markedThrough: through, markedOn: on, filedBy: "defendant", docNumber: `List D, item ${n}`, ...extra });
const PW = "2024-07-15";
const PW2 = "2024-08-05";
const DW = "2025-01-20";

export const DEFENDANT_EXHIBITS: DocSpec[] = [
  { id: D("d01"), source: "defendant", date: "2022-12-02", time: "19:02", type: "Email", subject: "Pilot go-live — revised plan", from: "Raghavendra S. Bhat", to: ["Harish Kumar Patil"], cc: ["Arjun Shetty"], body: "Harish,\n\nGiven where we are on store master data and the e-invoicing integration, the pilot go-live will slip by about six weeks from 15.12.2022. We will share a revised plan by Monday. The master data for 27 stores is still not with us.\n\nRaghavendra", india: Dx(1, "PW-1", PW), coding: code({ issues: ["DLY-01"], hot: true }), tags: ["key-doc", "confronted"], thread: "t_master_data", aiScore: 92 },
  { id: D("d02"), source: "defendant", date: "2022-12-20", type: "Spreadsheet", subject: "Defect log as on 20.12.2022 — 14 open Sev-3 defects", body: "DEFECT LOG — Project Sankalp (extract). Open: 14 Sev-3, 0 Sev-1, 0 Sev-2. Examples: SAN-211 loyalty points rounding; SAN-219 slow SKU search (>4 s) at Mysuru; SAN-224 duplicate print of credit note; SAN-230 Kannada receipt footer truncation.", pages: 3, india: Dx(2, "PW-1", PW), coding: code({ issues: ["ACC-01", "DEF-01"] }) },
  { id: D("d03"), source: "defendant", date: "2023-02-14", type: "Letter", subject: "Invocation of liquidated damages under clause 11.2 for delayed pilot", from: "Lalitha Gowda", to: ["Raghavendra S. Bhat"], body: "The pilot scheduled for 15.12.2022 went live only on 06.02.2023, a delay of 53 days (7 complete weeks). We hereby invoke clause 11.2 of the MSA and will adjust liquidated damages of ₹2,94,000 (0.5% × 7 weeks × ₹84,00,000) against the M4 invoice. We reserve our rights in respect of further delays.", pages: 1, india: Dx(3, "DW-1", DW), coding: code({ issues: ["DLY-01"], hot: true }), aiScore: 84 },
  { id: D("d04"), source: "defendant", date: "2023-02-27", time: "16:20", type: "Email", subject: "Performance fixes — deferral to rollout", from: "Arjun Shetty", to: ["Harish Kumar Patil"], body: "Harish, the SKU search performance fix (SAN-219) and the credit-note duplication fix (SAN-224) will be delivered with the rollout build on 20.03.2023 rather than as a hotfix now. Neither blocks billing.", india: Dx(4, "PW-1", PW2), coding: code({ issues: ["DEF-01"] }), tags: ["confronted"] },
  { id: D("d05"), source: "defendant", date: "2023-04-10", type: "Report", subject: "Kaveri QA Labs — independent audit of the Sankalp platform", from: "Rohit Joshi", body: "INDEPENDENT AUDIT REPORT (Kaveri QA Labs LLP). Scope: stability of billing across 46 stores, 20.03.2023 to 05.04.2023. Findings: (1) 11 billing interruptions recorded in the customer's downtime report; (2) 8 of the 11 coincide with store network outages recorded by the ISPs; (3) 3 interruptions (Mysuru, 24.03.2023; Davanagere, 28.03.2023; Udupi, 02.04.2023) were caused by a memory leak in the store sync agent, fixed in release 2.4.1 on 04.04.2023. Overall: platform stable after 04.04.2023.", pages: 12, india: Dx(5, "DW-1", DW), coding: code({ issues: ["DEF-01"], hot: true }), tags: ["key-doc", "expert"], aiScore: 90 },
  { id: D("d06"), source: "defendant", date: "2022-12-22", time: "09:15", type: "Email", subject: "About yesterday's UAT mail", from: "Harish Kumar Patil", to: ["Lalitha Gowda"], body: "Lalitha, yesterday's UAT mail to Nimbus is only to unblock the pilot. Please don't treat it as acceptance of M3 — I have made it subject to the 14 defects. Internal only.", india: Dx(6, "DW-1", DW), coding: code({ issues: ["ACC-01"], hot: true }), tags: ["key-doc", "internal"], aiScore: 91 },
  { id: D("d07"), source: "defendant", date: "2023-03-30", type: "Spreadsheet", subject: "Store downtime report, 20.03.2023 to 30.03.2023", body: "Downtime report compiled by Store Operations. 11 billing interruptions across 7 stores. Hubballi, 22.03.2023: 10:00 to 13:30 (210 minutes) — Ugadi sale day. Mysuru, 24.03.2023: 45 minutes. Davanagere, 28.03.2023: 30 minutes. [Remaining rows omitted in extract]", pages: 2, india: Dx(7, "DW-1", DW), coding: code({ issues: ["DEF-01"], hot: true }), aiScore: 86 },
  { id: D("d08"), source: "defendant", date: "2023-01-16", type: "Memo", subject: "Minutes of steering committee — Project Sankalp, 16.01.2023", body: "Present: Lalitha Gowda, Harish Kumar Patil (Tungabhadra); Raghavendra S. Bhat, Arjun Shetty (Nimbus). 1. Pilot: new date 06.02.2023 agreed. 2. Store master data: complete set received on 12.01.2023. 3. Nimbus notes the pilot slip followed late master data; Tungabhadra does not accept this and reserves LD. 4. Rollout target 31.03.2023 retained.", pages: 2, india: Dx(8, "DW-1", DW), coding: code({ issues: ["DLY-01"], hot: true }), tags: ["key-doc"], aiScore: 88 },
  { id: D("d09"), source: "defendant", date: "2024-11-10", type: "Other", subject: "Board resolution of the defendant authorising Harish Kumar Patil to depose", body: "Resolved that Mr. Harish Kumar Patil, Head of IT, be authorised to depose on behalf of the Company in Com.O.S. No. 1187 of 2023 and to sign the affidavit in lieu of examination-in-chief.", pages: 1, india: Dx(9, "DW-1", DW), coding: code({}) },
  { id: D("d10"), source: "defendant", date: "2023-04-20", type: "Spreadsheet", subject: "Ugadi sales comparison 2022 v 2023 — claimed loss of sales", body: "Ugadi weekend sales, 46 stores. 2022: ₹5.84 crore. 2023: ₹5.12 crore. Shortfall ₹72 lakh attributed by Store Operations to billing outages. Note: 2022 figures include 3 stores closed in January 2023.", pages: 2, india: Dx(10, "DW-1", DW), coding: code({ issues: ["CC-01"], hot: true }), aiScore: 80 },
  { id: D("d11"), source: "defendant", date: "2023-03-23", type: "Letter", subject: "Letter of the Hubballi store manager on the Ugadi billing outage (Kannada)", from: "Mahesh Kulkarni", to: ["Lalitha Gowda"], body: "ಮಾನ್ಯರೇ,\n\nಯುಗಾದಿ ಹಬ್ಬದ ಮಾರಾಟದ ದಿನವಾದ 22.03.2023 ರಂದು ಬೆಳಿಗ್ಗೆ 10 ಗಂಟೆಯಿಂದ ಮಧ್ಯಾಹ್ನ 1.30 ರವರೆಗೆ ನಮ್ಮ ಹುಬ್ಬಳ್ಳಿ ಮಳಿಗೆಯ ಬಿಲ್ಲಿಂಗ್ ವ್ಯವಸ್ಥೆ ಕೆಲಸ ಮಾಡಲಿಲ್ಲ. ಗ್ರಾಹಕರು ಉದ್ದನೆಯ ಸಾಲಿನಲ್ಲಿ ಕಾಯಬೇಕಾಯಿತು ಮತ್ತು ಅನೇಕರು ಖರೀದಿ ಮಾಡದೆ ಹೊರಟುಹೋದರು. ಅಂದಾಜು ₹3.2 ಲಕ್ಷ ಮಾರಾಟ ನಷ್ಟವಾಗಿದೆ. ನಿಂಬಸ್ ತಂಡಕ್ಕೆ ಬೆಳಿಗ್ಗೆ 10.15ಕ್ಕೆ ಕರೆ ಮಾಡಲಾಯಿತು.\n\nದಯವಿಟ್ಟು ಈ ವಿಷಯವನ್ನು ಗಮನಿಸಬೇಕಾಗಿ ವಿನಂತಿ.\n\nಮಹೇಶ್ ಕುಲಕರ್ಣಿ\nಮಳಿಗೆ ವ್ಯವಸ್ಥಾಪಕರು, ಹುಬ್ಬಳ್ಳಿ", india: Dx(11, "DW-1", DW, { language: "kn" }), coding: code({ issues: ["DEF-01", "CC-01"], hot: true }), tags: ["key-doc", "kannada"], aiScore: 85 },
  { id: D("d12"), source: "defendant", date: "2023-04-11", time: "12:30", type: "Email", subject: "M5 acceptance withheld pending stabilisation", from: "Lalitha Gowda", to: ["Raghavendra S. Bhat"], cc: ["Pradeep Shenoy"], body: "Raghavendra, in view of the outages during Ugadi week, acceptance of M5 is withheld until the platform runs for 30 days without a Sev-1 incident. Please do not raise further invoices until then.", india: Dx(12, "DW-1", DW), coding: code({ issues: ["ACC-01"], hot: true }), tags: ["key-doc"], aiScore: 89 },
  { id: D("d13"), source: "defendant", date: "2023-12-15", type: "Spreadsheet", subject: "Counter-claim computation", body: "Counter-claim: (a) liquidated damages for delayed pilot ₹2,94,000; (b) liquidated damages for delayed rollout ₹0 (rollout on time); (c) loss of sales during Ugadi week ₹72,00,000; (d) cost of independent audit ₹6,50,000; (e) reputational loss ₹35,00,000. Total ₹1,16,44,000.", pages: 1, india: Dx(13, "DW-1", DW), coding: code({ issues: ["CC-01"] }) },
  { id: D("d14"), source: "defendant", date: "2024-11-11", type: "Other", subject: "Certificate under Section 63 of the Bharatiya Sakshya Adhiniyam for the defendant's electronic records", body: "CERTIFICATE UNDER SECTION 63(4) OF THE BHARATIYA SAKSHYA ADHINIYAM, 2023 (in the form in the Schedule), by Harish Kumar Patil, in respect of Ex.D1, Ex.D4, Ex.D6, Ex.D7, Ex.D12 and Ex.D15. [Part A by the party; Part B by the expert — not filed.]", pages: 2, india: Dx(14, "DW-1", DW), coding: code({}), tags: ["electronic evidence"] },
  { id: D("d15"), source: "defendant", date: "2023-01-20", type: "Chat", subject: "WhatsApp export — Harish Kumar Patil and Arjun Shetty, January 2023", from: "Harish Kumar Patil", body: "[18/01/23, 21:40] Harish Kumar Patil: Mysuru SKU search still slow. We'll sign off pilot readiness once Mysuru is stable.\n[18/01/23, 21:44] Arjun Shetty: Fix is in the 2.2 build, deploying Saturday night.\n[20/01/23, 09:12] Harish Kumar Patil: Mysuru is fine now. Go ahead with 06.02 for the pilot.", india: Dx(15, "DW-1", DW), coding: code({ issues: ["ACC-01", "DEF-01"] }), tags: ["whatsapp"] },
  { id: D("d16"), source: "defendant", date: "2023-03-24", type: "Letter", subject: "Notice of breach — billing outages during Ugadi week", from: "Lalitha Gowda", to: ["Raghavendra S. Bhat"], body: "We place on record the billing outages at our stores on 22.03.2023 and 24.03.2023 during the peak Ugadi sale. These constitute a material breach of the service levels in Annexure B of SOW-1. We reserve our right to claim damages, including for loss of sales.", pages: 1, india: Dx(16, "DW-1", DW), coding: code({ issues: ["DEF-01", "CC-01"] }) },
  { id: D("d17"), source: "defendant", date: "2023-05-02", type: "Other", subject: "Quotation from an alternative support vendor", body: "Quotation for annual support of a retail POS platform for 46 stores: ₹38,00,000 per annum plus GST. Vendor name redacted by the defendant.", pages: 1, india: Dx(17, "DW-1", DW), coding: code({ issues: ["CC-01"] }) },
  { id: D("d18"), source: "defendant", date: "2023-08-31", type: "Spreadsheet", subject: "Purchase ledger of the defendant — Nimbus Cloudworks account", body: "Ledger (extract). Payments to Nimbus Cloudworks: 30.05.2022 ₹49,56,000; 28.09.2022 ₹99,12,000; 12.04.2023 ₹60,00,000. Invoices 157 and 163 booked as 'disputed — under review'. LD adjustment of ₹2,94,000 not yet passed.", pages: 1, india: Dx(18, "DW-1", DW), coding: code({ issues: ["DUE-01", "ACK-01"] }) },
];

const C = (docClass: IndiaDocMeta["docClass"], extra: Partial<IndiaDocMeta> = {}): IndiaDocMeta => ({ docClass, filedBy: "court", ...extra });

/** Court record of the commercial suit (pleadings, applications, orders, order sheets). */
export const COMMERCIAL_RECORD: DocSpec[] = [
  { id: D("rec_plaint"), source: "courtCom", date: "2023-08-29", type: "Other", subject: "Plaint under Order VII Rule 1 CPC read with the Commercial Courts Act, 2015", body: "IN THE COURT OF THE COMMERCIAL COURT AT BENGALURU\nCom.O.S. No. 1187 of 2023\nBETWEEN: Nimbus Cloudworks Private Limited … PLAINTIFF\nAND: Tungabhadra Retail Solutions Private Limited … DEFENDANT\n\nThe Plaintiff prays for a decree for ₹3,09,33,690 with future interest at 18% per annum, being the balance of the price of Project Sankalp under the MSA dated 14.02.2022 and SOW-1, after giving credit for ₹60,00,000 received on 12.04.2023. The cause of action arose on the due dates of invoices 131, 157 and 163 and on 05.04.2023 when the Defendant acknowledged the dues in writing. Pre-institution mediation ended as a non-starter on 14.08.2023. Statement of truth filed.", pages: 18, india: C("pleading", { filedBy: "plaintiff", title: "Plaint", docNumber: "Plaint" }), coding: code({ issues: ["DUE-01", "ACK-01"] }), tags: ["pleading"] },
  { id: D("rec_ws"), source: "courtCom", date: "2023-12-18", type: "Other", subject: "Written statement and counter-claim of the defendant (Order VIII Rules 1 and 6A CPC)", body: "The Defendant denies that milestones M3, M4 and M5 were accepted. UAT sign-off dated 21.12.2022 was conditional on closure of 14 defects. The pilot was delayed by 53 days for reasons attributable to the Plaintiff. Billing outages during Ugadi week caused loss of sales. The e-mail of 05.04.2023 was a commercial courtesy. By way of counter-claim the Defendant claims ₹1,16,44,000 (liquidated damages, loss of sales, audit cost, reputational loss).", pages: 24, india: C("pleading", { filedBy: "defendant", title: "Written statement and counter-claim", docNumber: "WS + CC" }), coding: code({ issues: ["ACC-01", "DLY-01", "CC-01"] }), tags: ["pleading"] },
  { id: D("rec_ws_cc"), source: "courtCom", date: "2024-02-05", type: "Other", subject: "Written statement of the plaintiff to the counter-claim", body: "The counter-claim is barred by clause 12.3 of the MSA, which excludes loss of sales and consequential loss. Liquidated damages cannot run for delay caused by the Defendant's late store master data (clause 11.4; Ex.P8, Ex.P5). The Hubballi outage was caused by the Defendant's own network (Ex.P12, Ex.P16).", pages: 9, india: C("pleading", { filedBy: "plaintiff", title: "Written statement to counter-claim", docNumber: "WS to CC" }), coding: code({ issues: ["CC-01", "DLY-01", "DEF-01"] }), tags: ["pleading"] },
  { id: D("rec_issues"), source: "courtCom", date: "2024-04-22", type: "Other", subject: "Order framing issues", body: "ISSUES\n1. Whether the Plaintiff proves that it completed milestones M3, M4 and M5 under SOW-1 and that ₹2,86,92,000 is due from the Defendant?\n2. Whether the Plaintiff is entitled to interest at 18% per annum?\n3. Whether the Defendant proves that the pilot go-live was delayed for reasons attributable to the Plaintiff, entitling it to liquidated damages?\n4. Whether the Defendant proves that it suffered loss of sales on account of billing outages, and whether such loss is recoverable in view of clause 12.3 of the MSA?\n5. Whether the Defendant is entitled to the counter-claim of ₹1,16,44,000?\n6. What decree or order?", pages: 2, india: C("order", { title: "Order framing issues" }), coding: code({ issues: ["DUE-01", "DLY-01", "CC-01"] }), tags: ["order"] },
  { id: D("rec_pw1_aff"), source: "courtCom", date: "2024-06-10", type: "Other", subject: "Affidavit of PW-1 in lieu of examination-in-chief (Order XVIII Rule 4 CPC)", body: "Affidavit of Raghavendra S. Bhat, Vice President (Delivery) of the Plaintiff, in lieu of examination-in-chief. Paragraphs 1 to 14 as read into the deposition on 15.07.2024. Documents Ex.P1 to Ex.P25 produced.", pages: 11, india: C("affidavit", { filedBy: "plaintiff", title: "Chief-examination affidavit of PW-1" }), coding: code({}), tags: ["affidavit"] },
  { id: D("rec_dw1_aff"), source: "courtCom", date: "2024-11-11", type: "Other", subject: "Affidavit of DW-1 in lieu of examination-in-chief (Order XVIII Rule 4 CPC)", body: "Affidavit of Harish Kumar Patil, Head of IT of the Defendant, in lieu of examination-in-chief. Paragraphs 1 to 12 as read into the deposition on 20.01.2025. Documents Ex.D3, Ex.D5 to Ex.D18 produced.", pages: 9, india: C("affidavit", { filedBy: "defendant", title: "Chief-examination affidavit of DW-1" }), coding: code({}), tags: ["affidavit"] },
  { id: D("rec_ia1"), source: "courtCom", date: "2023-08-29", type: "Other", subject: "I.A. No. 1 under Order XXXVIII Rule 5 CPC — attachment before judgment", body: "Application by the Plaintiff for a direction to the Defendant to furnish security for ₹3,09,33,690 or show cause why its bank accounts should not be attached before judgment, on the ground that the Defendant is closing stores and disposing of assets.", pages: 6, india: C("application", { filedBy: "plaintiff", title: "I.A. No. 1 (Order XXXVIII Rule 5 CPC)" }), coding: code({ issues: ["DUE-01"] }), tags: ["application"] },
  { id: D("rec_ia1_order"), source: "courtCom", date: "2023-11-06", type: "Other", subject: "Order on I.A. No. 1 — dismissed, defendant's undertaking recorded", body: "ORDER ON I.A. No. 1. The Plaintiff has not shown that the Defendant is about to dispose of its property with intent to obstruct execution. The Defendant's undertaking not to alienate its Jayanagar premises without leave of the court is recorded. I.A. No. 1 is dismissed.", pages: 4, india: C("order", { title: "Order on I.A. No. 1" }), coding: code({}), tags: ["order"] },
  { id: D("rec_os_2024_07_15"), source: "courtCom", date: "2024-07-15", type: "Note", subject: "Order sheet — 15.07.2024", body: "15.07.2024. Plaintiff's advocate present. Defendant's advocate present. PW-1 examined; affidavit in lieu of chief taken as read. Ex.P1 to Ex.P25 marked. Cross-examination commenced; Ex.D1 and Ex.D2 confronted to PW-1 and marked. Further cross — call on 05.08.2024.", india: C("order_sheet", { title: "Order sheet 15.07.2024" }), coding: code({}) },
  { id: D("rec_os_2024_08_05"), source: "courtCom", date: "2024-08-05", type: "Note", subject: "Order sheet — 05.08.2024", body: "05.08.2024. PW-1 further cross-examined; Ex.D4 confronted and marked. Re-examination: nil. Plaintiff's evidence closed. For defendant's evidence — call on 11.11.2024.", india: C("order_sheet", { title: "Order sheet 05.08.2024" }), coding: code({}) },
  { id: D("rec_os_2025_01_20"), source: "courtCom", date: "2025-01-20", type: "Note", subject: "Order sheet — 20.01.2025", body: "20.01.2025. DW-1 examined; affidavit in lieu of chief taken as read. Ex.D3 and Ex.D5 to Ex.D18 marked. Ex.D10 and Ex.D13 marked subject to objection as to mode of proof. Cross-examination by the plaintiff's advocate commenced. Call on 17.02.2025.", india: C("order_sheet", { title: "Order sheet 20.01.2025" }), coding: code({}) },
  { id: D("rec_os_2025_02_17"), source: "courtCom", date: "2025-02-17", type: "Note", subject: "Order sheet — 17.02.2025", body: "17.02.2025. DW-1 further cross-examined. Re-examination: nil. Defendant's evidence closed. For arguments.", india: C("order_sheet", { title: "Order sheet 17.02.2025" }), coding: code({}) },
  { id: D("rec_os_2026_08_24"), source: "courtCom", date: "2026-08-24", type: "Note", subject: "Order sheet — 24.08.2026", body: "24.08.2026. Plaintiff's advocate addressed arguments in part. Defendant's advocate sought time to file written arguments. Written arguments of both sides to be filed before the next date. Call for further arguments.", india: C("order_sheet", { title: "Order sheet 24.08.2026" }), coding: code({}) },
];
