import type { CodingDecision } from "@/lib/types/domain";
import { DEMO_ID as D, type DocSpec } from "./doc-spec";

/**
 * Com.O.S. No. 1187 of 2023 — unmarked documents: advocate–client communications (withheld; privilege under BSA
 * s.132 / IEA s.126), a business e-mail on which the advocate was merely copied (not privileged), translations of
 * the Kannada exhibits (labelled as translations; the Kannada original is the text of record), and internal notes.
 */

const R = "p_demo_in_kavya_hegde";
const T = "2026-09-12T09:30:00Z";
const code = (c: Partial<CodingDecision>): Partial<CodingDecision> => ({ reviewerId: R, reviewedAt: T, ...c });

export const PRIVILEGED_AND_OTHER: DocSpec[] = [
  { id: D("priv01"), source: "plaintiff", date: "2023-05-12", time: "11:40", type: "Email", subject: "Advice: legal notice and Section 12A mediation before suit", from: "Kavya Hegde", to: ["Nisha Menon", "Raghavendra S. Bhat"], body: "Nisha, Raghavendra — privileged and confidential.\n\nOur advice on the notice, the pre-institution mediation requirement and the limitation position is in the attached note. In short: send the notice now, apply for mediation immediately after the reply period, and preserve the WhatsApp exports of 22.03.2023 with a Section 65B certificate.\n\nKavya Hegde, Advocate", india: { docClass: "correspondence", filedBy: "plaintiff" }, coding: code({ responsive: true, privileged: true, privilegeBasis: "attorney-client", issues: ["PRV-01", "LIM-01"], notes: "Advice from the firm to the client. Withhold." }), tags: ["privileged"], aiScore: 60 },
  { id: D("priv02"), source: "plaintiff", date: "2023-05-10", time: "17:05", type: "Email", subject: "Request for advice — does Pradeep's e-mail restart limitation?", from: "Nisha Menon", to: ["Kavya Hegde"], body: "Kavya, privileged. Please advise whether the CFO's e-mail of 05.04.2023 counts as an acknowledgement for limitation, and whether the part payment of 12.04.2023 helps us on invoice 157 as well. We also want to know whether we should stop support services.\n\nNisha", india: { docClass: "correspondence", filedBy: "plaintiff" }, coding: code({ responsive: true, privileged: true, privilegeBasis: "attorney-client", issues: ["PRV-01", "ACK-01", "LIM-01"], notes: "Client's request for legal advice. Withhold." }), tags: ["privileged"], aiScore: 58 },
  { id: D("priv03"), source: "plaintiff", date: "2023-08-18", type: "Memo", subject: "Draft plaint (v3) with advocate's comments", from: "Kavya Hegde", body: "DRAFT — PRIVILEGED. Draft plaint for Com.O.S. with comments: confirm the valuation for court fee [VERIFY]; tie paragraph 14 (acknowledgement) to Ex.P14 and Ex.P20; consider pleading clause 11.4 in answer to the anticipated LD defence.", pages: 16, india: { docClass: "pleading", filedBy: "plaintiff", title: "Draft plaint (not filed)" }, coding: code({ responsive: true, privileged: true, privilegeBasis: "work-product", issues: ["PRV-01"], notes: "Advocate's draft with comments; confidential communication with legal adviser." }), tags: ["privileged", "draft"], aiScore: 55 },
  { id: D("cc01"), source: "plaintiff", date: "2023-05-05", time: "15:22", type: "Email", subject: "Balance payment — invoices 131, 157 and 163", from: "Nisha Menon", to: ["Pradeep Shenoy"], cc: ["Kavya Hegde"], body: "Pradeep, thank you for the ₹60 lakh on 12 April. The balance of ₹2,86,92,000 remains outstanding. Please share the payment schedule you mentioned for Diwali so that we can plan our cash flows. Copying our advocate for information.\n\nNisha Menon, CFO", india: { docClass: "correspondence", filedBy: "plaintiff" }, coding: code({ responsive: true, privileged: false, issues: ["DUE-01", "ACK-01", "PRV-01"], notes: "Advocate merely copied on a business communication to the opposite party: not privileged. Produced." }), tags: ["privilege-cc", "key-doc"], aiScore: 82 },
  { id: D("tr_p16"), source: "plaintiff", date: "2023-08-25", type: "Chat", subject: "English translation of Ex.P16 (WhatsApp export, Kannada) — filed by the plaintiff", from: "Deepa Nagaraj", body: "TRANSLATION (filed by the plaintiff; certified by the translator). The Kannada original, Ex.P16, is the text of record.\n\n[22/03/23, 10:09] Deepa Nagaraj: The internet line at the Hubballi store is down. I have opened ISP ticket No. 88213.\n[22/03/23, 10:31] Deepa Nagaraj: Our server is fine; billing is running in all the other stores.\n[22/03/23, 11:05] Deepa Nagaraj: I have switched on offline billing mode.\n[22/03/23, 11:20] Deepa Nagaraj: The line is back; billing is running normally.", india: { docClass: "translation", filedBy: "plaintiff", language: "en", translationOf: D("p16"), translationOrigin: "provider" }, coding: code({ responsive: true, issues: ["DEF-01"] }), tags: ["translation"] },
  { id: D("tr_d11"), source: "defendant", date: "2024-11-11", type: "Letter", subject: "English translation of Ex.D11 (Hubballi store manager's letter, Kannada) — filed by the defendant", from: "Mahesh Kulkarni", to: ["Lalitha Gowda"], body: "TRANSLATION (filed by the defendant). The Kannada original, Ex.D11, is the text of record.\n\nSir,\n\nOn 22.03.2023, the Ugadi festival sale day, the billing system of our Hubballi store did not work from 10 a.m. to 1.30 p.m. Customers had to wait in long queues and many left without purchasing. The estimated loss of sales is ₹3.2 lakh. The Nimbus team was called at 10.15 a.m.\n\nKindly look into the matter.\n\nMahesh Kulkarni\nStore Manager, Hubballi", india: { docClass: "translation", filedBy: "defendant", language: "en", translationOf: D("d11"), translationOrigin: "provider" }, coding: code({ responsive: true, issues: ["DEF-01", "CC-01"] }), tags: ["translation"] },
  { id: D("n01"), source: "plaintiff", date: "2023-03-22", time: "13:10", type: "Email", subject: "Hubballi outage — root cause and timeline", from: "Arjun Shetty", to: ["Raghavendra S. Bhat"], body: "Raghavendra, Hubballi was down 10:05–11:20 because the store's leased line failed (ISP ticket 88213). Deepa switched them to offline billing at 11:05. Cloud and all other stores were fine. Incident report INC-0322 follows. Their store manager is telling the COO it was down till 1.30; our logs show sales posting from 11:21.", india: { docClass: "correspondence", filedBy: "plaintiff" }, coding: code({ responsive: true, hot: true, issues: ["DEF-01"] }), tags: ["key-doc"], aiScore: 88 },
  { id: D("n02"), source: "plaintiff", date: "2023-04-12", time: "16:48", type: "Email", subject: "₹60 lakh received from Tungabhadra", from: "Nisha Menon", to: ["Raghavendra S. Bhat", "Arjun Shetty"], body: "Received ₹60,00,000 today against invoice 131, as Pradeep promised in his mail of 5 April. Balance ₹2.87 crore. Please make sure M5 stabilisation items are closed quickly so they have no reason to hold the rest.", india: { docClass: "correspondence", filedBy: "plaintiff" }, coding: code({ responsive: true, issues: ["DUE-01", "ACK-01"] }), aiScore: 70 },
  { id: D("n03"), source: "plaintiff", date: "2023-01-12", time: "18:30", type: "Email", subject: "Store master data received — all 46 stores", from: "Arjun Shetty", to: ["Raghavendra S. Bhat"], body: "We finally have the complete master data for all 46 stores as of today (12.01.2023) — 89 days after the CR-07 date. That fully explains the pilot slip. Proposing 06.02.2023 for pilot go-live at tomorrow's steering committee.", india: { docClass: "correspondence", filedBy: "plaintiff" }, coding: code({ responsive: true, hot: true, issues: ["DLY-01"] }), tags: ["key-doc"], thread: "t_master_data", aiScore: 90 },
];
