import type { CodingDecision } from "@/lib/types/domain";
import type { IndiaDocMeta } from "@/modules/ediscovery/india";
import { DEMO_ID as D, type DocSpec } from "./doc-spec";

/**
 * Com.O.S. No. 1187 of 2023 (Commercial Court, Bengaluru) — the plaintiff's documents, Ex.P1 to Ex.P25, marked
 * through PW-1 (Raghavendra S. Bhat) on 15.07.2024. Nimbus Cloudworks Pvt. Ltd. and Tungabhadra Retail Solutions
 * Pvt. Ltd. are FICTIONAL companies; every document is synthetic.
 */

const R = "p_demo_in_kavya_hegde";
const T = "2026-09-10T11:00:00Z";
const code = (c: Partial<CodingDecision>): Partial<CodingDecision> => ({ responsive: true, reviewerId: R, reviewedAt: T, ...c });
const P = (n: number, extra: Partial<IndiaDocMeta> = {}): IndiaDocMeta => ({ docClass: "exhibit", exhibit: `Ex.P${n}`, markedThrough: "PW-1", markedOn: "2024-07-15", filedBy: "plaintiff", docNumber: `List P, item ${n}`, ...extra });

export const PLAINTIFF_EXHIBITS: DocSpec[] = [
  { id: D("p01"), source: "plaintiff", date: "2023-08-12", type: "Other", subject: "Board resolution authorising Raghavendra S. Bhat to institute the suit and depose", body: "CERTIFIED TRUE COPY OF THE RESOLUTION PASSED AT THE MEETING OF THE BOARD OF DIRECTORS OF NIMBUS CLOUDWORKS PRIVATE LIMITED HELD ON 12 AUGUST 2023 AT WHITEFIELD, BENGALURU\n\nRESOLVED THAT Mr. Raghavendra S. Bhat, Vice President (Delivery), be and is hereby authorised to institute a commercial suit against Tungabhadra Retail Solutions Private Limited for recovery of amounts due under the Master Services Agreement dated 14.02.2022, to sign and verify the plaint, affidavits and applications, to depose on behalf of the Company, and to engage advocates.\n\nFor Nimbus Cloudworks Private Limited\nCompany Secretary", pages: 1, india: P(1), coding: code({ issues: ["DUE-01"] }), tags: ["authority"] },
  { id: D("p02"), source: "plaintiff", date: "2022-02-14", type: "Contract", subject: "Master Services Agreement between Nimbus Cloudworks and Tungabhadra Retail Solutions", body: "MASTER SERVICES AGREEMENT dated 14 February 2022 between Nimbus Cloudworks Private Limited (\"Service Provider\") and Tungabhadra Retail Solutions Private Limited (\"Customer\").\n\n7.2 Invoices are payable within thirty (30) days of the invoice date.\n7.4 Amounts not paid when due carry interest at eighteen per cent (18%) per annum from the due date until payment.\n9.3 A milestone is accepted when the Customer signs off user acceptance testing or uses the Deliverable in production, whichever is earlier.\n11.2 If a milestone is delayed for reasons attributable solely to the Service Provider, the Customer may claim liquidated damages at 0.5% of the milestone value for each complete week of delay, capped at 10% of the milestone value.\n11.4 Delay caused by the Customer's failure to provide inputs, data or access extends the milestone date day for day.\n12.3 Neither party is liable for indirect or consequential loss, including loss of profit, revenue or sales.\n18.1 The courts at Bengaluru have exclusive jurisdiction.", pages: 14, india: P(2), coding: code({ issues: ["ACC-01", "DLY-01", "CC-01"], hot: true }), tags: ["key-doc", "contract"], aiScore: 94 },
  { id: D("p03"), source: "plaintiff", date: "2022-02-14", type: "Contract", subject: "Statement of Work No. 1 — Project Sankalp (cloud POS and inventory, 46 stores)", body: "STATEMENT OF WORK No. 1 under the MSA dated 14.02.2022. Fixed price ₹4,20,00,000 plus GST, payable on milestones:\nM1 Design — ₹42,00,000 — 30.04.2022\nM2 Build — ₹84,00,000 — 31.08.2022\nM3 User acceptance testing — ₹1,05,00,000 — 30.11.2022\nM4 Pilot go-live in 6 stores — ₹84,00,000 — 15.12.2022\nM5 Rollout to 46 stores — ₹1,05,00,000 — 31.03.2023\nCustomer dependency D-3: store master data (SKU, price and tax masters for all stores) to be provided by 15.10.2022.", pages: 9, india: P(3), coding: code({ issues: ["DUE-01", "DLY-01"], hot: true }), tags: ["key-doc", "contract"], aiScore: 91 },
  { id: D("p04"), source: "plaintiff", date: "2022-02-18", type: "Other", subject: "Purchase order TRS/PO/4471 — Project Sankalp", body: "PURCHASE ORDER No. TRS/PO/4471 dated 18.02.2022 issued by Tungabhadra Retail Solutions Pvt. Ltd. to Nimbus Cloudworks Pvt. Ltd. for Project Sankalp as per SOW-1. Order value ₹4,95,60,000 (inclusive of GST at 18%). Payment terms: as per MSA clause 7.2.", pages: 1, india: P(4), coding: code({ issues: ["DUE-01"] }) },
  { id: D("p05"), source: "plaintiff", date: "2022-09-26", type: "Contract", subject: "Change Request CR-07 — revised pilot date and store master data dependency", body: "CHANGE REQUEST CR-07 approved on 26.09.2022 by both parties. Scope: add GST e-invoicing integration. Impact: pilot go-live (M4) moved to 15.12.2022 subject to receipt of complete store master data by 15.10.2022 (dependency D-3). If the data is received later, M3 and M4 dates move day for day (MSA clause 11.4).\nApproved: Arjun Shetty (Nimbus) / Harish Kumar Patil (Tungabhadra).", pages: 2, india: P(5), coding: code({ issues: ["DLY-01"], hot: true }), tags: ["key-doc"], aiScore: 88 },
  { id: D("p06"), source: "plaintiff", date: "2022-08-31", type: "Other", subject: "Tax invoice INV/2022-23/118 — Milestone M2 (Build)", body: "TAX INVOICE INV/2022-23/118 dated 31.08.2022. Milestone M2 (Build): ₹84,00,000; IGST 18%: ₹15,12,000; total ₹99,12,000. Paid on 28.09.2022 (UTR ICIC0000912231).", pages: 1, india: P(6), coding: code({ issues: ["DUE-01"] }) },
  { id: D("p07"), source: "plaintiff", date: "2022-11-30", type: "Other", subject: "Tax invoice INV/2022-23/131 — Milestone M3 (UAT)", body: "TAX INVOICE INV/2022-23/131 dated 30.11.2022. Milestone M3 (User acceptance testing): ₹1,05,00,000; IGST 18%: ₹18,90,000; total ₹1,23,90,000. Due date: 30.12.2022.", pages: 1, india: P(7), coding: code({ issues: ["DUE-01"], hot: true }), tags: ["invoice"] },
  { id: D("p08"), source: "plaintiff", date: "2022-11-09", time: "18:12", type: "Email", subject: "Store master data still pending — dependency D-3", from: "Arjun Shetty", to: ["Harish Kumar Patil"], cc: ["Raghavendra S. Bhat"], body: "Harish,\n\nAs discussed in today's review, we have received price and tax masters for only 19 of the 46 stores. Under CR-07 the complete store master data was due on 15.10.2022. UAT for the remaining stores cannot close until this is received. Please treat this as notice under clause 11.4 of the MSA that the M3 and M4 dates move day for day.\n\nRegards,\nArjun", india: P(8), coding: code({ issues: ["DLY-01"], hot: true }), tags: ["key-doc"], thread: "t_master_data", aiScore: 90 },
  { id: D("p09"), source: "plaintiff", date: "2022-12-21", time: "20:41", type: "Email", subject: "UAT sign-off — Project Sankalp", from: "Harish Kumar Patil", to: ["Arjun Shetty"], cc: ["Raghavendra S. Bhat", "Lalitha Gowda"], body: "Arjun,\n\nWe have completed UAT. Please treat this mail as UAT sign-off for Project Sankalp subject to closure of the 14 open Sev-3 defects listed in the defect log before rollout. You may proceed with the pilot in the six stores.\n\nHarish Kumar Patil\nHead of IT, Tungabhadra Retail Solutions", india: P(9), coding: code({ issues: ["ACC-01"], hot: true }), tags: ["key-doc"], aiScore: 97 },
  { id: D("p10"), source: "plaintiff", date: "2023-02-06", type: "Report", subject: "Pilot go-live report — six stores (Jayanagar, Malleshwaram, Mysuru, Hubballi, Davanagere, Udupi)", body: "PILOT GO-LIVE REPORT dated 06.02.2023. The platform went live in the six pilot stores on 06.02.2023. Billing, inventory sync and GST e-invoicing are operating. Open items: 3 Sev-3 defects (report printing, loyalty rounding, slow SKU search at Mysuru). Sign-off by store operations obtained on 08.02.2023.", pages: 4, india: P(10), coding: code({ issues: ["ACC-01", "DLY-01"] }) },
  { id: D("p11"), source: "plaintiff", date: "2023-02-28", type: "Other", subject: "Tax invoice INV/2022-23/157 — Milestone M4 (Pilot)", body: "TAX INVOICE INV/2022-23/157 dated 28.02.2023. Milestone M4 (Pilot go-live in 6 stores): ₹84,00,000; IGST 18%: ₹15,12,000; total ₹99,12,000. Due date: 30.03.2023.", pages: 1, india: P(11), coding: code({ issues: ["DUE-01"], hot: true }), tags: ["invoice"] },
  { id: D("p12"), source: "plaintiff", date: "2023-03-22", type: "Report", subject: "Incident report INC-0322 — Hubballi store billing outage on Ugadi", body: "INCIDENT REPORT INC-0322. Store: Hubballi. Date: 22.03.2023. Outage window: 10:05 to 11:20 (75 minutes). Root cause: failure of the store's internet leased line (ISP ticket 88213); the cloud platform and other 45 stores were unaffected. Offline billing mode was enabled at 11:05 by our field engineer; line restored at 11:20. Responsibility for the store network lies with the Customer (SOW-1, Annexure C).", pages: 2, india: P(12), coding: code({ issues: ["DEF-01"], hot: true }), tags: ["key-doc"], aiScore: 89 },
  { id: D("p13"), source: "plaintiff", date: "2023-03-31", time: "17:55", type: "Email", subject: "Rollout complete — 46 stores live on Sankalp", from: "Lalitha Gowda", to: ["Raghavendra S. Bhat"], cc: ["Harish Kumar Patil", "Pradeep Shenoy"], body: "Raghavendra,\n\nConfirming that all 46 stores are now billing on Sankalp as of today. Thank you to your team for the weekend effort. We will share the list of stabilisation items separately.\n\nLalitha Gowda\nCOO", india: P(13), coding: code({ issues: ["ACC-01"], hot: true }), tags: ["key-doc"], aiScore: 93 },
  { id: D("p14"), source: "plaintiff", date: "2023-04-05", time: "10:14", type: "Email", subject: "RE: Overdue invoices 131 and 157", from: "Pradeep Shenoy", to: ["Nisha Menon"], cc: ["Harish Kumar Patil"], body: "Nisha,\n\nWe acknowledge that the M3 and M4 invoices are due. We will release ₹60 lakh this week and clear the balance by Diwali once the Ugadi issues are closed.\n\nRegards,\nPradeep Shenoy\nCFO, Tungabhadra Retail Solutions", india: P(14), coding: code({ issues: ["DUE-01", "ACK-01", "LIM-01"], hot: true }), tags: ["key-doc", "admission"], aiScore: 98 },
  { id: D("p15"), source: "plaintiff", date: "2023-03-31", type: "Other", subject: "Tax invoice INV/2022-23/163 — Milestone M5 (Rollout)", body: "TAX INVOICE INV/2022-23/163 dated 31.03.2023. Milestone M5 (Rollout to 46 stores): ₹1,05,00,000; IGST 18%: ₹18,90,000; total ₹1,23,90,000. Due date: 30.04.2023.", pages: 1, india: P(15), coding: code({ issues: ["DUE-01"] }), tags: ["invoice"] },
  { id: D("p16"), source: "plaintiff", date: "2023-03-22", type: "Chat", subject: "WhatsApp export — Sankalp field support group, 22.03.2023 (Kannada)", from: "Deepa Nagaraj", body: "[22/03/23, 10:09] Deepa Nagaraj: ಹುಬ್ಬಳ್ಳಿ ಸ್ಟೋರ್‌ನಲ್ಲಿ ಇಂಟರ್ನೆಟ್ ಲೈನ್ ಡೌನ್ ಆಗಿದೆ. ISP ಟಿಕೆಟ್ ನಂ. 88213 ತೆರೆದಿದ್ದೇನೆ.\n[22/03/23, 10:31] Deepa Nagaraj: ನಮ್ಮ ಸರ್ವರ್ ಸರಿಯಾಗಿ ಇದೆ, ಉಳಿದ ಎಲ್ಲಾ ಸ್ಟೋರ್‌ಗಳಲ್ಲಿ ಬಿಲ್ಲಿಂಗ್ ನಡೆಯುತ್ತಿದೆ.\n[22/03/23, 11:05] Deepa Nagaraj: ಆಫ್‌ಲೈನ್ ಬಿಲ್ಲಿಂಗ್ ಮೋಡ್ ಆನ್ ಮಾಡಿದ್ದೇನೆ.\n[22/03/23, 11:20] Deepa Nagaraj: ಲೈನ್ ವಾಪಸ್ ಬಂದಿದೆ, ಬಿಲ್ಲಿಂಗ್ ಸಾಮಾನ್ಯವಾಗಿ ನಡೆಯುತ್ತಿದೆ.", india: P(16, { language: "kn" }), coding: code({ issues: ["DEF-01"], hot: true }), tags: ["key-doc", "whatsapp", "kannada"], aiScore: 87 },
  { id: D("p17"), source: "plaintiff", date: "2023-05-18", type: "Letter", subject: "Legal notice calling upon the defendant to pay ₹2,86,92,000 with interest", from: "Kavya Hegde", to: ["Tungabhadra Retail Solutions Private Limited"], body: "LEGAL NOTICE dated 18.05.2023 on behalf of Nimbus Cloudworks Pvt. Ltd. Our client has completed all five milestones of SOW-1. Invoices INV/2022-23/131, 157 and 163 aggregating ₹3,46,92,000 remain unpaid save for ₹60,00,000 received on 12.04.2023. Your CFO acknowledged the dues by e-mail dated 05.04.2023. You are called upon to pay ₹2,86,92,000 with interest at 18% per annum under clause 7.4 of the MSA within 15 days of receipt of this notice, failing which our client will initiate proceedings, including pre-institution mediation under Section 12A of the Commercial Courts Act, 2015.", pages: 3, india: P(17), coding: code({ issues: ["DUE-01", "ACK-01"] }), tags: ["notice"] },
  { id: D("p18"), source: "plaintiff", date: "2023-05-22", type: "Other", subject: "Postal acknowledgement — service of legal notice on 22.05.2023", body: "India Post acknowledgement card for RPAD article EK 4431 2210 9IN delivered to Tungabhadra Retail Solutions Pvt. Ltd., Jayanagar 4th Block, Bengaluru on 22.05.2023, received with company seal.", pages: 1, india: P(18), coding: code({ issues: ["DUE-01"] }) },
  { id: D("p19"), source: "plaintiff", date: "2023-06-02", type: "Letter", subject: "Defendant's reply notice denying liability", from: "S. Venkatesh Murthy", to: ["Kavya Hegde"], body: "REPLY dated 02.06.2023 on behalf of Tungabhadra Retail Solutions Pvt. Ltd. Our client denies that milestones M4 and M5 were completed in accordance with the SOW. The pilot was delayed by 53 days and the platform failed in several stores on 22.03.2023, causing loss of festival sales. Our client is entitled to liquidated damages under clause 11.2 and damages for loss of sales, which exceed the amounts claimed. The e-mail dated 05.04.2023 was a commercial courtesy and not an admission of liability.", pages: 3, india: P(19), coding: code({ issues: ["DLY-01", "DEF-01", "ACK-01"], hot: true }), tags: ["notice"] },
  { id: D("p20"), source: "plaintiff", date: "2023-04-12", type: "Spreadsheet", subject: "Bank statement extract — receipt of ₹60,00,000 from the defendant on 12.04.2023", body: "Statement of account (extract), current account of Nimbus Cloudworks Pvt. Ltd.\n12.04.2023 | NEFT CR | TUNGABHADRA RETAIL SOL | ₹60,00,000.00 | Ref: PART PMT INV 131", pages: 1, india: P(20), coding: code({ issues: ["DUE-01", "ACK-01", "LIM-01"] }) },
  { id: D("p21"), source: "plaintiff", date: "2023-08-14", type: "Report", subject: "Non-starter report — pre-institution mediation under Section 12A, Commercial Courts Act", body: "NON-STARTER REPORT. Pre-institution mediation application of Nimbus Cloudworks Pvt. Ltd. against Tungabhadra Retail Solutions Pvt. Ltd. The opposite party did not appear despite notice on 11.07.2023 and 02.08.2023. The mediation is closed as a non-starter on 14.08.2023.", pages: 1, india: P(21), coding: code({ issues: ["DUE-01"] }) },
  { id: D("p22"), source: "plaintiff", date: "2023-08-20", type: "Spreadsheet", subject: "Ledger account of the defendant in the plaintiff's books (01.04.2022 to 20.08.2023)", body: "Ledger: Tungabhadra Retail Solutions Pvt. Ltd.\nINV/2022-23/102 M1 ₹49,56,000 — paid 30.05.2022\nINV/2022-23/118 M2 ₹99,12,000 — paid 28.09.2022\nINV/2022-23/131 M3 ₹1,23,90,000 — part paid ₹60,00,000 on 12.04.2023\nINV/2022-23/157 M4 ₹99,12,000 — unpaid\nINV/2022-23/163 M5 ₹1,23,90,000 — unpaid\nBalance due: ₹2,86,92,000", pages: 2, india: P(22), coding: code({ issues: ["DUE-01"] }) },
  { id: D("p23"), source: "plaintiff", date: "2023-04-11", type: "Spreadsheet", subject: "GSTR-1 extract showing invoices 131, 157 and 163", body: "GSTR-1 (outward supplies) extract, GSTIN 29AAXCN0000X1Z0 (demo). B2B invoices to GSTIN 29AAXCT0000X1Z0 (demo): INV/2022-23/131 (Nov 2022), INV/2022-23/157 (Feb 2023), INV/2022-23/163 (Mar 2023). The recipient's GSTR-2B reflects each invoice.", pages: 2, india: P(23), coding: code({ issues: ["DUE-01"] }) },
  { id: D("p24"), source: "plaintiff", date: "2023-08-25", type: "Other", subject: "Certificate under Section 65B of the Indian Evidence Act for e-mails and WhatsApp export", body: "CERTIFICATE UNDER SECTION 65B(4) OF THE INDIAN EVIDENCE ACT, 1872. I, Raghavendra S. Bhat, state that the e-mails produced as Ex.P8, Ex.P9, Ex.P13 and Ex.P14 and the WhatsApp export produced as Ex.P16 were printed from the Company's Microsoft 365 mailboxes and a Company-issued phone in the regular course of activities, and that the computer systems were operating properly during the relevant period.", pages: 2, india: P(24), coding: code({ issues: ["DUE-01"] }), tags: ["electronic evidence"] },
  { id: D("p25"), source: "plaintiff", date: "2023-08-26", type: "Spreadsheet", subject: "Statement of claim and interest computation at 18% per annum", body: "Principal due: ₹2,86,92,000. Interest at 18% p.a. under MSA clause 7.4 from the respective due dates to 28.08.2023: ₹22,41,690. Total claimed in the suit: ₹3,09,33,690, with future interest at 18% p.a. until realisation. [Demo figures]", pages: 1, india: P(25), coding: code({ issues: ["DUE-01"] }) },
];
